// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#include "Packet/StaticData/RewardGroup/RewardGroupDocLookup.h"

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"
#include "Packet/StaticDataAccessor/StaticDataAccessor.h"
#include "Packet/StaticDataCatalog/StaticDataCatalog.h"
#include "Packet/StaticData/RewardGroup/RewardGroupDoc.h"
#include "Packet/StaticData/Item/ItemDocLookup.h"


RewardGroupDocLookup::~RewardGroupDocLookup()
{
	Clear();
}
void RewardGroupDocLookup::Clear()
{
	for (auto& [_, doc] : mRewardGroupDocMap)
	{
		_DELETE(doc);
	}
	mRewardGroupDocMap.clear();
}

void RewardGroupDocLookup::Load()
{
	for (const auto& it : gStaticDataCatalog->GetList<STATIC_REWARD_GROUP>())
	{		
		auto key = it->Get_c_reward_sid();
		auto found = mRewardGroupDocMap.find(key);
		RewardGroupDoc* doc = (mRewardGroupDocMap.end() != found) ? found->second : _NEW<RewardGroupDoc>();
		mRewardGroupDocMap.emplace(key, doc);
	}

	for (auto& [_, doc] : mRewardGroupDocMap)
	{
		doc->mStaticRewardGroupList.clear();
		doc->mRewardGroupTable.Clear();
	}

	for (const auto& it : gStaticDataCatalog->GetList<STATIC_REWARD_GROUP>())
	{
		auto key = it->Get_c_reward_sid();
		auto found = mRewardGroupDocMap.find(key);
		_ASSERT_CRASH(mRewardGroupDocMap.end() != found);
		RewardGroupDoc* doc = found->second;
		doc->mStaticRewardGroupList.emplace_back(*it);
		_TODO("mStaticRewardGroupList를 기반으로 mRewardGroupTable(조회용 테이블) 구성 로직 추가");
	}
}

void RewardGroupDocLookup::Link()
{
	const std::shared_ptr<ItemDocLookup> itemDocLookup = gStaticDataAccessor->Get<ItemDocLookup>();

	for (auto& [_, doc] : mRewardGroupDocMap)
	{
		doc->mItemDocList.reserve(doc->mStaticRewardGroupList.size());

		for (const STATIC_REWARD_GROUP* staticRewardGroup : doc->mStaticRewardGroupList)
		{
			auto key = staticRewardGroup->Get_c_item_sid();
			const ItemDoc* itemDoc = itemDocLookup->Find(key);
			_ASSERT_CRASH(nullptr != itemDoc);
			doc->mItemDocList.emplace_back(itemDoc);
		}
	}
}

const RewardGroupDoc* RewardGroupDocLookup::Find(RewardSid rewardSid) const
{
	const auto it = mRewardGroupDocMap.find(rewardSid);

	if (mRewardGroupDocMap.end() == it)
	{
		_DEBUG_BREAK;
		_DEBUG_RED;
		return nullptr;
	}

	return it->second;
}
