// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

// ServerEnginePacket.ixx
// Packet/StaticData 관련 모듈
// 클라이언트는 기존 #include 방식, 서버는 import ServerEnginePacket; 으로 사용
//
// 내용: StaticData 관리 클래스 + Doc/DocLookup + UserCache 타입

module;

// GMF - pch_packet.h 필요 (PacketKeep, Checksum, StaticDataIndex 등 정의됨)
#include "Packet/PCH/pch_packet.h"

// StaticData 관리 클래스
#include "Packet/StaticDataDocLookupBase/StaticDataDocLookupBase.h"
#include "Packet/StaticDataCatalog/StaticDataCatalog.h"
#include "Packet/StaticDataAccessor/StaticDataAccessor.h"

// StaticData Doc/DocLookup
#include "Packet/StaticData/Achievement/AchievementDoc.h"
#include "Packet/StaticData/Achievement/AchievementDocLookup.h"
#include "Packet/StaticData/Building/BuildingDoc.h"
#include "Packet/StaticData/Building/BuildingDocLookup.h"
#include "Packet/StaticData/Character/CharacterDoc.h"
#include "Packet/StaticData/Character/CharacterDocLookup.h"
#include "Packet/StaticData/CharacterSkill/CharacterSkillDoc.h"
#include "Packet/StaticData/CharacterSkill/CharacterSkillDocLookup.h"
#include "Packet/StaticData/Game/GameDoc.h"
#include "Packet/StaticData/Game/GameDocLookup.h"
#include "Packet/StaticData/Item/ItemDoc.h"
#include "Packet/StaticData/Item/ItemDocLookup.h"
#include "Packet/StaticData/ItemStat/ItemStatDoc.h"
#include "Packet/StaticData/ItemStat/ItemStatDocLookup.h"
#include "Packet/StaticData/Map/MapDoc.h"
#include "Packet/StaticData/Map/MapDocLookup.h"
#include "Packet/StaticData/Mission/MissionDoc.h"
#include "Packet/StaticData/Mission/MissionDocLookup.h"
#include "Packet/StaticData/Quest/QuestDoc.h"
#include "Packet/StaticData/Quest/QuestDocLookup.h"
#include "Packet/StaticData/Reward/RewardDoc.h"
#include "Packet/StaticData/Reward/RewardDocLookup.h"
#include "Packet/StaticData/RewardGroup/RewardGroupDoc.h"
#include "Packet/StaticData/RewardGroup/RewardGroupDocLookup.h"
#include "Packet/StaticData/Stat/StatDoc.h"
#include "Packet/StaticData/Stat/StatDocLookup.h"
#include "Packet/StaticData/UserExp/UserExpDoc.h"
#include "Packet/StaticData/UserExp/UserExpDocLookup.h"

// UserCache 테이블류
#include "Packet/UserCache/UserAchievement/UserAchievementRow.h"
#include "Packet/UserCache/UserAchievement/UserAchievementTable.h"
#include "Packet/UserCache/UserCharacter/UserCharacterRow.h"
#include "Packet/UserCache/UserCharacter/UserCharacterTable.h"
#include "Packet/UserCache/UserItem/UserItemRow.h"
#include "Packet/UserCache/UserItem/UserItemTable.h"
#include "Packet/UserCache/UserItemStat/UserItemStatRow.h"
#include "Packet/UserCache/UserItemStat/UserItemStatTable.h"
#include "Packet/UserCache/UserMission/UserMissionRow.h"
#include "Packet/UserCache/UserMission/UserMissionTable.h"
#include "Packet/UserCache/UserQuest/UserQuestRow.h"
#include "Packet/UserCache/UserQuest/UserQuestTable.h"

// UserCacheAccessor
#include "Packet/UserCacheAccessor/UserCacheAccessor.h"
#include "Packet/UserCacheDiff/UserCacheDiff.h"

export module ServerEnginePacket;

// ============= 자동 생성된 패킷 모듈 re-export =============
export import ServerEnginePacketAutoGenerated;

// ============= StaticData 관리 클래스 =============
export using ::StaticDataDocLookupBase;
export using ::StaticDataCatalog;
export using ::StaticDataAccessor;
export using ::gStaticDataCatalog;
export using ::gStaticDataAccessor;

// ============= StaticData Doc =============
export using ::AchievementDoc;
export using ::BuildingDoc;
export using ::CharacterDoc;
export using ::CharacterSkillDoc;
export using ::GameDoc;
export using ::ItemDoc;
export using ::ItemStatDoc;
export using ::MapDoc;
export using ::MissionDoc;
export using ::QuestDoc;
export using ::RewardDoc;
export using ::RewardGroupDoc;
export using ::StatDoc;
export using ::UserExpDoc;

// ============= StaticData DocLookup =============
export using ::AchievementDocLookup;
export using ::BuildingDocLookup;
export using ::CharacterDocLookup;
export using ::CharacterSkillDocLookup;
export using ::GameDocLookup;
export using ::ItemDocLookup;
export using ::ItemStatDocLookup;
export using ::MapDocLookup;
export using ::MissionDocLookup;
export using ::QuestDocLookup;
export using ::RewardDocLookup;
export using ::RewardGroupDocLookup;
export using ::StatDocLookup;
export using ::UserExpDocLookup;

// ============= UserCache 테이블 =============
export using ::UserAchievementRow;
export using ::UserAchievementTable;
export using ::UserCharacterRow;
export using ::UserCharacterTable;
export using ::UserItemRow;
export using ::UserItemTable;
export using ::UserItemStatRow;
export using ::UserItemStatTable;
export using ::UserMissionRow;
export using ::UserMissionTable;
export using ::UserQuestRow;
export using ::UserQuestTable;

// ============= UserCacheAccessor =============
export using ::UserCacheAccessor;
export using ::UserCacheDiff;

