// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================


#pragma once

#include "CoreMinimal.h"
#include "Components/Button.h"

#include "UiEvent/AutoGenerated/UiEvent.h"

#include "UiButton.generated.h"


/**
 * UI 이벤트를 발생시키는 버튼 위젯.
 */
UCLASS()
class UUiButton : public UButton
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	UiEventType mUiEventClicked;

public:
	void SetupButton(UiEventType uiEventTypeClicked);

protected:
	TSharedRef<SWidget> RebuildWidget() override;
	
protected:
	UFUNCTION(BlueprintCallable)
	void OnButtonClicked();
};
