// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Widget/Base/WidgetBase.h"
#include "GameCameraController/Internal/GameCameraAutoCenter.h"
#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"
#include "ViewportWidgetBase.generated.h"

class FUiServiceGame;
class FMapRenderer;
struct WorldUser;
class Entity;
class PacketTemp;

UCLASS(Abstract, Blueprintable)
class UViewportWidgetBase : public UWidgetBase
{
	GENERATED_BODY()

protected:
	FGameCameraAutoCenter mCameraAutoCenter;

protected:
	FReply NativeOnMouseButtonDown(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent) override;
	FReply NativeOnMouseButtonUp(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent) override;
	FReply NativeOnMouseMove(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent) override;
	void NativeOnMouseEnter(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent) override;
	void NativeOnMouseLeave(const FPointerEvent& InMouseEvent) override;
	FReply NativeOnMouseWheel(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent) override;
	bool NativeSupportsKeyboardFocus() const override { return true; }

	FVector2D GetCursorPos(const FPointerEvent& pointerEvent);
	void TryAutoCameraCenter(float deltaTime, WorldUserId worldUserId);

	// 파생 클래스에서 마우스 클릭 시 추가 처리 (키보드 커맨드 전송 등)
	virtual void OnMouseButtonDownExtra(TSharedPtr<FUiServiceGame> gameService, const Entity* selectedEntity, const Scalar x, const Scalar y) {}

	virtual WorldUserId GetMyWorldUserId() const { return WorldUserId(0); }

public:
	void OnDispatchUiEvent(UUiEventBase* uiEvent) override;
	void OnUiEvent(UUiEventBase& uiEvent) {}
};
