// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

import BridgeServer;
import ServerEnginePacketAutoGenerated;


void SocketBridgeToMain::OnAppAdded(IN OUT MAYBE_UNUSED AppInfo& appInfo)
{
	// [WHY] MainServer로부터 다른 앱 정보를 수신했을 때 필요한 초기화 수행
	// 현재는 별도 처리 없음
}

bool SocketBridgeToMain::OnDispatchPacket(NetworkPacket& rp)
{
	DispatchPacket(rp);
	return true;
}

void SocketBridgeToMain::DispatchPacket(NetworkPacket& rp)
{
	// [WHY] Worker 스레드가 아닌 경우 비동기로 Worker에게 디스패치 위임
	if (tThreadId == INVALID_THREAD_ID)
		PacketUtil::DispatchPacketOnAnyThread(this, &SocketBridgeToMain::DispatchPacket_async, rp);
	else
		DispatchPacketToHandler(rp);
}

void SocketBridgeToMain::DispatchPacket_async(MAYBE_UNUSED SocketPtrType& ptr, PacketTemp tp)
{
	DispatchPacketToHandler(**tp);
}

void SocketBridgeToMain::DispatchPacketToHandler(NetworkPacket& rp)
{
	if (DispatchPacketMB<MainPeerSocket>(mSocket, this, rp) != HandleResult::NOT_EXISTS)
		return;

	// [WHY] 처리되지 않은 패킷은 로그로 기록 (디버깅 용도)
	_DEBUG_LOG(RED, L"{}", GetPacketTypeString(rp.GetPacketType()));
}
