// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

import MainServer;
import ServerEnginePacketAutoGenerated;

#include "Transactor_DM_REQ_GAME_USER_ENTER.h"


Transactor_DM_REQ_GAME_USER_ENTER::Transactor_DM_REQ_GAME_USER_ENTER(
	SocketMainFromDb& dbSocket,
	DM_REQ_GAME_USER_ENTER& rp
)
	:
	mDbSocket(dbSocket),
	mRp(rp)
{
}
Result Transactor_DM_REQ_GAME_USER_ENTER::OnUpdate()
{
	const UserId userId = mRp.GetHeader().GetUserId();
	const GameId gameId = mRp.Get_gameId();
	const bool result = gGameListManager->AddUserToGame(userId, gameId);
	if (false == result)
		return Result::RETRY_LATER;

	const AppId gameAppId = gGameListManager->GetGameAppId(gameId);
	auto gameSocket = MainSocketUtil::GetGameSocket(gameAppId);
	if (!gameSocket)
		return Result::RETRY_LATER;

	mRp.GetHeader().SetAppId(AppType::GAME_SERVER, gameAppId);
	mRp.GetHeader().SetGameId(gameId);

	SocketUtil::Request<MG_REQ_GAME_USER_ENTER::Writer> wp(**gameSocket, REQ, mRp);

	if (!wp.Wait(mRp.GetHeader(), OUT mAck))
	{
		mRp.GetHeader().SetGameId(INVALID_UUID);
		return Result::FATAL_ERROR;
	}

	if (Result::SUCCEEDED != mAck->GetHeader().GetPacketResult())
	{
		mRp.GetHeader().SetGameId(INVALID_UUID);
		return mAck->GetHeader().GetPacketResult();
	}

	return Result::SUCCEEDED;
}

void Transactor_DM_REQ_GAME_USER_ENTER::OnFinish()
{
	SocketUtil::Send<MD_ACK_GAME_USER_ENTER::Writer> wp(mDbSocket, ACK, mRp, GetResult());
}

void Transactor_DM_REQ_GAME_USER_ENTER::OnError()
{
	SocketUtil::Send<MD_ACK_GAME_USER_ENTER::Writer> wp(mDbSocket, ACK, mRp, GetResult());
}

void Transactor_DM_REQ_GAME_USER_ENTER::OnLog()
{

}

