// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

import MainServer;
import ServerEnginePacketAutoGenerated;

#include "Transactor_CM_REQ_SERVER_LIST.h"

// [WHY] Server는 import MainServer를 통해 모듈에서 이미 export됨


Transactor_CM_REQ_SERVER_LIST::Transactor_CM_REQ_SERVER_LIST(
	SocketMainFromFront& frontSocket,
	CM_REQ_SERVER_LIST& rp
)
	:
	mFrontSocket(frontSocket),
	mRp(rp)
{
}

Result Transactor_CM_REQ_SERVER_LIST::OnUpdate()
{
	return Result::SUCCEEDED;
}

void Transactor_CM_REQ_SERVER_LIST::OnFinish()
{
	MainSocketUtil::SendToClient<MC_ACK_SERVER_LIST::Writer> wp(mFrontSocket, ACK, mRp, GetResult());	
	for (const auto& [serverId, server] : gServerListManager->GetServerMap())
	{
		wp.Write_serverList(server->GetData());
	}
}

void Transactor_CM_REQ_SERVER_LIST::OnError()
{
	MainSocketUtil::SendToClient<MC_ACK_SERVER_LIST::Writer> wp(mFrontSocket, ACK, mRp, GetResult());
}

void Transactor_CM_REQ_SERVER_LIST::OnLog()
{

}
