// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#include "MainPeerSocket.h"

#include "Common/UsageMeter/UsageMeter.h"
#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"

import ServerEngineNetwork;
import ServerEngineUtil;
import ServerEngineWorker;
import ServerEngineApp;


MainPeerSocket::MainPeerSocket()
{
}
void MainPeerSocket::OnHandshakeCompleted(MAYBE_UNUSED bool reconnected)
{
	SocketUtil::Send<REQ_GLOBAL_NOW::Writer> wp(*this, REQ);
	wp.SetValues(
		false, 
		tClock.GetLocalNowMs()
	);
}

HandleResult MainPeerSocket::OnPacket(MAYBE_UNUSED NetworkPacket& rp)
{
	_DEBUG_LOG(RED, L"{}", GetPacketTypeString(rp.GetPacketType()));

	return HandleResult::NOT_EXISTS;
}

HandleResult MainPeerSocket::OnPacket(MAYBE_UNUSED SYNC_TIME& rp)
{
	SocketUtil::Send<REQ_GLOBAL_NOW::Writer> wp(*this, REQ);
	wp.SetValues(
		true, 
		tClock.GetLocalNowMs()
	);

	return HandleResult::OK;
}

HandleResult MainPeerSocket::OnPacket(ACK_GLOBAL_NOW& rp)
{
	if (Result::SUCCEEDED != rp.GetHeader().GetPacketResult())
		return HandleResult::FAILED;
	
	const ClockMs nowMs = tClock.GetLocalNowMs();
	const ClockMs reqMs = rp.Get_reqMs();
	const ClockMs delta = (nowMs > reqMs) ? (nowMs - reqMs) : 0ms;
	if (MAX_TIME_SYNC_DELTA < delta)
	{
		SocketUtil::Send<REQ_GLOBAL_NOW::Writer> wp(*this, REQ);
		wp.SetValues(
			rp.Get_onlySyncTime(), 
			nowMs
		);

		return HandleResult::OK;
	}
	
	gNetworkManager->SetupGlobalNow(rp.Get_ackNow());


	if (false == rp.Get_onlySyncTime())
	{
		//auto lock = gAppListManager->ClearAppInfoAll();

		SocketUtil::Send<REQ_APP_JOIN::Writer> wp(*this, REQ);
		wp.SetValues(
			APP_DATA::Writer(PARAM, TEMP_BUF,
				gMyAppId,
				gMyAppType,
				gAppConfigManager->mMyIp.c_str()
			)
		);
	}

	return HandleResult::OK;
}

HandleResult MainPeerSocket::OnPacket(ACK_APP_JOIN& rp)
{
	if (Result::APP_JOIN_RETRY_LATER == rp.GetHeader().GetPacketResult())
		return HandleResult::FAILED;

	if (Result::APP_JOIN_COUNT_OVERFLOW == rp.GetHeader().GetPacketResult())
		return HandleResult::FAILED;

	for (const APP_DATA* appData : rp.Get_appDataList())
	{
		auto [appInfo, lock] = gAppListManager->AddAppInfo(*appData);
		if (appInfo && !appInfo->GetSocket())
		{
			OnAppAdded(IN OUT *appInfo);
		}
	}

	return HandleResult::OK;
}

HandleResult MainPeerSocket::OnPacket(APP_ADD& rp)
{
	auto [appInfo, lock] = gAppListManager->AddAppInfo(rp.Get_appData());
	if (appInfo && !appInfo->GetSocket())
	{
		OnAppAdded(IN OUT *appInfo);
	}

	return HandleResult::OK;
}

HandleResult MainPeerSocket::OnPacket(APP_REMOVE& rp)
{
	const bool result = gAppListManager->RemoveAppInfo(rp.Get_appId());
	if (false == result)
	{
		_ASSERT_CRASH(false);
		return HandleResult::OK;
	}

	OnAppRemoved(rp.Get_appId());

	return HandleResult::OK;
}

HandleResult MainPeerSocket::OnPacket(REQ_SHELL_COMMAND& rp)
{
	std::wstring result = OnShellCommand(rp.Get_command());

	result += mCommonShellCommandHandler.Dispatch(GetSocketPtr(), rp.Get_command());

	SocketUtil::Send<ACK_SHELL_COMMAND::Writer> wp(*this, ACK, rp, Result::SUCCEEDED);
	wp.SetValues(
		result.data()
	);

	return HandleResult::OK;
}

HandleResult MainPeerSocket::OnPacket(SHELL_NOTIFY& rp)
{
	std::wstring result = OnShellCommand(rp.Get_command());

	result += mCommonShellCommandHandler.Dispatch(GetSocketPtr(), rp.Get_command());

	return HandleResult::OK;
}
