// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "UiEvent/UiEventType.h"
#include "UiEvent/AutoGenerated/UiEvent.h"


class NetworkPacket;
class UUiEventBase;

class FUiServiceBase
{
public:
	static inline size_t mServiceIdx = 0;

public:
	virtual ~FUiServiceBase() = default;

public:
	virtual void OnDispatchUiEvent(UUiEventBase* uiEvent) {}
	virtual void OnDispatchPacket(NetworkPacket& rp) {}
};
