// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#include "Packet/StaticData/Game/GameDocLookup.h"

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"
#include "Packet/StaticDataAccessor/StaticDataAccessor.h"
#include "Packet/StaticDataCatalog/StaticDataCatalog.h"
#include "Packet/StaticData/Game/GameDoc.h"
#include "Packet/StaticData/Map/MapDocLookup.h"


GameDocLookup::~GameDocLookup()
{
	Clear();
}
void GameDocLookup::Clear()
{
	for (auto& [_, doc] : mGameDocMap)
	{
		_DELETE(doc);
	}
	mGameDocMap.clear();
}

void GameDocLookup::Load()
{
	for (auto& it : gStaticDataCatalog->GetList<STATIC_GAME>())
	{
		auto key = it->Get_c_game_sid();
		auto found = mGameDocMap.find(key);
		GameDoc* doc = (mGameDocMap.end() != found) ?
			found->second : _NEW<GameDoc>();
		doc->mStaticGame = *it;
		mGameDocMap.emplace(key, doc);

		doc->mMapDoc = nullptr;
	}
}

void GameDocLookup::Link()
{
	const std::shared_ptr<MapDocLookup> mapDocLookup = gStaticDataAccessor->Get<MapDocLookup>();

	for (auto& [_, doc] : mGameDocMap)
	{;
		auto key = doc->mStaticGame->Get_c_map_sid();
		const MapDoc* mapDoc = mapDocLookup->Find(key);
		_ASSERT_CRASH(nullptr != mapDoc);
		doc->mMapDoc = mapDoc;
	}
}

const GameDoc* GameDocLookup::Find(GameSid gameSid) const
{
	const auto it = mGameDocMap.find(gameSid);

	if (mGameDocMap.end() == it)
	{
		// [WHY] 테스트/에디터 환경에서는 일부 GameSid가 정의되지 않을 수 있으므로 nullptr 반환을 허용한다.
		//_DEBUG_BREAK;
		//_DEBUG_RED;
		return nullptr;
	}

	return it->second;
}
