// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"
#include "Packet/NetworkPacket/NetworkPacket.h"
#include "Packet/NetworkPacket/NetworkPacketWriter.h"
#include "Packet/BasePacket/PacketWriter.h"
#include "Packet/PacketDataList/PacketDataList.h"
#include "Packet/PacketFuncs/PacketValidator.h"
#include "Packet/PacketFuncs/PacketDispatcher.h"

#pragma pack(push, 1)

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class DC_ERROR;

class DC_ERROR_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::DC_ERROR;

public:
   // (7)
   explicit DC_ERROR_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ERROR, buf)
   {
   }

   // (9)
   explicit DC_ERROR_WRITER(
       PacketTraitParam trait, uint8_t* buf,
       PacketType packetType
   )
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ERROR, buf)
   {
       WriteValue(packetType);


   }

   // (8)
   explicit DC_ERROR_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       PacketType packetType
   )
   {
       WriteValue(packetType);


   }

   DC_ERROR& GetPacket() const noexcept { return *reinterpret_cast<DC_ERROR*>(GetPacketBufPtr()); }
   DC_ERROR* GetPacketPtr() const noexcept { return reinterpret_cast<DC_ERROR*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class DC_ERROR : public NetworkPacket
{
   public:
      using Writer = DC_ERROR_WRITER;


private:
   PacketType m_packetType;

public:
   DC_ERROR()
   {
       memset(this, 0, sizeof(DC_ERROR));
       mPacketSize = static_cast<PacketSize>(sizeof(DC_ERROR));
   }
   DC_ERROR(const DC_ERROR&) = delete;
   DC_ERROR(DC_ERROR &&) = delete;
   DC_ERROR& operator = (const DC_ERROR&) = delete;
   DC_ERROR& operator = (DC_ERROR &&) = delete;

   PacketType Get_packetType() const noexcept { return m_packetType; }
   PacketType& Ref_packetType() noexcept { return m_packetType; }
   const PacketType& ConstRef_packetType() const noexcept { return m_packetType; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(DC_ERROR) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(DC_ERROR) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(DC_ERROR); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(DC_ERROR))
           {
               size += sizeof(DC_ERROR);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(PacketType);
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, DC_ERROR>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}packetType: {}", tTabStr, t->Get_packetType());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class DC_ACK_CHEAT;

class DC_ACK_CHEAT_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::DC_ACK_CHEAT;

public:
   // (4)
   explicit DC_ACK_CHEAT_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_CHEAT, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (5)
   explicit DC_ACK_CHEAT_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_CHEAT, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (6)
   explicit DC_ACK_CHEAT_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_CHEAT, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);
   }

   // (8)
   explicit DC_ACK_CHEAT_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       const USER_CACHE_DIFF& userCacheDiff,
       const USER_DATA& userData,
       uint8_t isCompleted
   )
   {
       PacketSize& userCacheDiffOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       PacketSize& userDataOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(isCompleted);


       userCacheDiffOffset = GetPacketSize();
       WriteBinary((uint8_t*)&userCacheDiff, userCacheDiff.GetPacketSize());

       userDataOffset = GetPacketSize();
       WriteBinary((uint8_t*)&userData, userData.GetPacketSize());

   }

   void SetValues(
       const USER_CACHE_DIFF::Writer& userCacheDiff,
       const USER_DATA::Writer& userData,
       uint8_t isCompleted
   )
   {
       PacketSize& userCacheDiffOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       PacketSize& userDataOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(isCompleted);


       userCacheDiffOffset = GetPacketSize();
       WriteBinary(userCacheDiff.GetPacketBufPtr(), userCacheDiff.GetPacketSize());

       userDataOffset = GetPacketSize();
       WriteBinary(userData.GetPacketBufPtr(), userData.GetPacketSize());

   }

   DC_ACK_CHEAT& GetPacket() const noexcept { return *reinterpret_cast<DC_ACK_CHEAT*>(GetPacketBufPtr()); }
   DC_ACK_CHEAT* GetPacketPtr() const noexcept { return reinterpret_cast<DC_ACK_CHEAT*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class DC_ACK_CHEAT : public NetworkPacket
{
   public:
      using Writer = DC_ACK_CHEAT_WRITER;


private:
   PacketSize m_userCacheDiff_offset = 0;

   PacketSize m_userData_offset = 0;

   uint8_t m_isCompleted;

public:
   DC_ACK_CHEAT()
   {
       memset(this, 0, sizeof(DC_ACK_CHEAT));
       mPacketSize = static_cast<PacketSize>(sizeof(DC_ACK_CHEAT));
   }
   DC_ACK_CHEAT(const DC_ACK_CHEAT&) = delete;
   DC_ACK_CHEAT(DC_ACK_CHEAT &&) = delete;
   DC_ACK_CHEAT& operator = (const DC_ACK_CHEAT&) = delete;
   DC_ACK_CHEAT& operator = (DC_ACK_CHEAT &&) = delete;

   const USER_CACHE_DIFF& Get_userCacheDiff() const noexcept { return *(USER_CACHE_DIFF*)((uint8_t*)this + m_userCacheDiff_offset); }
   USER_CACHE_DIFF* Get_userCacheDiff_ptr() const noexcept { return (USER_CACHE_DIFF*)((uint8_t*)this + m_userCacheDiff_offset); }

   const USER_DATA& Get_userData() const noexcept { return *(USER_DATA*)((uint8_t*)this + m_userData_offset); }
   USER_DATA* Get_userData_ptr() const noexcept { return (USER_DATA*)((uint8_t*)this + m_userData_offset); }

   uint8_t Get_isCompleted() const noexcept { return m_isCompleted; }
   uint8_t& Ref_isCompleted() noexcept { return m_isCompleted; }
   const uint8_t& ConstRef_isCompleted() const noexcept { return m_isCompleted; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(DC_ACK_CHEAT) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(DC_ACK_CHEAT) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(DC_ACK_CHEAT); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(DC_ACK_CHEAT))
           {
               size += sizeof(DC_ACK_CHEAT);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           if (GetPacketSize() < m_userCacheDiff_offset)
               return false;

           const USER_CACHE_DIFF* _packet = reinterpret_cast<const USER_CACHE_DIFF*>(GetPacketBufPtr() + m_userCacheDiff_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       {
           if (GetPacketSize() < m_userData_offset)
               return false;

           const USER_DATA* _packet = reinterpret_cast<const USER_DATA*>(GetPacketBufPtr() + m_userData_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       {
           thisSize += sizeof(uint8_t);
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, DC_ACK_CHEAT>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}userCacheDiff: {}", tTabStr, t->Get_userCacheDiff_ptr());
       result += std::format(L"\n{}userData: {}", tTabStr, t->Get_userData_ptr());
       result += std::format(L"\n{}isCompleted: {}", tTabStr, t->Get_isCompleted());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class DC_ACK_STATIC_DATA_CHECKSUM;

class DC_ACK_STATIC_DATA_CHECKSUM_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::DC_ACK_STATIC_DATA_CHECKSUM;

public:
   // (4)
   explicit DC_ACK_STATIC_DATA_CHECKSUM_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_STATIC_DATA_CHECKSUM, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (5)
   explicit DC_ACK_STATIC_DATA_CHECKSUM_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_STATIC_DATA_CHECKSUM, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (6)
   explicit DC_ACK_STATIC_DATA_CHECKSUM_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_STATIC_DATA_CHECKSUM, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);
   }

   // (8)
   explicit DC_ACK_STATIC_DATA_CHECKSUM_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       Checksum staticDataChecksum,
       const StaticDataSize* staticDataSizeList,
       PacketSize staticDataSizeListSize,
       const Checksum* checksumList,
       PacketSize checksumListSize
   )
   {
       WriteValue(staticDataChecksum);

       PacketSize& staticDataSizeListOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(staticDataSizeListSize);

       PacketSize& checksumListOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(checksumListSize);


       staticDataSizeListOffset = GetPacketSize();
       WriteBinary((uint8_t*)staticDataSizeList, sizeof(StaticDataSize) * staticDataSizeListSize);

       checksumListOffset = GetPacketSize();
       WriteBinary((uint8_t*)checksumList, sizeof(Checksum) * checksumListSize);

   }

   DC_ACK_STATIC_DATA_CHECKSUM& GetPacket() const noexcept { return *reinterpret_cast<DC_ACK_STATIC_DATA_CHECKSUM*>(GetPacketBufPtr()); }
   DC_ACK_STATIC_DATA_CHECKSUM* GetPacketPtr() const noexcept { return reinterpret_cast<DC_ACK_STATIC_DATA_CHECKSUM*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class DC_ACK_STATIC_DATA_CHECKSUM : public NetworkPacket
{
   public:
      using Writer = DC_ACK_STATIC_DATA_CHECKSUM_WRITER;


private:
   Checksum m_staticDataChecksum;

   PacketSize m_staticDataSizeList_offset = 0;
   PacketSize m_staticDataSizeList_size = 0;

   PacketSize m_checksumList_offset = 0;
   PacketSize m_checksumList_size = 0;

public:
   DC_ACK_STATIC_DATA_CHECKSUM()
   {
       memset(this, 0, sizeof(DC_ACK_STATIC_DATA_CHECKSUM));
       mPacketSize = static_cast<PacketSize>(sizeof(DC_ACK_STATIC_DATA_CHECKSUM));
   }
   DC_ACK_STATIC_DATA_CHECKSUM(const DC_ACK_STATIC_DATA_CHECKSUM&) = delete;
   DC_ACK_STATIC_DATA_CHECKSUM(DC_ACK_STATIC_DATA_CHECKSUM &&) = delete;
   DC_ACK_STATIC_DATA_CHECKSUM& operator = (const DC_ACK_STATIC_DATA_CHECKSUM&) = delete;
   DC_ACK_STATIC_DATA_CHECKSUM& operator = (DC_ACK_STATIC_DATA_CHECKSUM &&) = delete;

   Checksum Get_staticDataChecksum() const noexcept { return m_staticDataChecksum; }
   Checksum& Ref_staticDataChecksum() noexcept { return m_staticDataChecksum; }
   const Checksum& ConstRef_staticDataChecksum() const noexcept { return m_staticDataChecksum; }

   const StaticDataSize* Get_staticDataSizeList() const noexcept { return (StaticDataSize*)((uint8_t*)this + m_staticDataSizeList_offset); }
   PacketSize Get_staticDataSizeList_size() const noexcept { return m_staticDataSizeList_size; }

   const Checksum* Get_checksumList() const noexcept { return (Checksum*)((uint8_t*)this + m_checksumList_offset); }
   PacketSize Get_checksumList_size() const noexcept { return m_checksumList_size; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(DC_ACK_STATIC_DATA_CHECKSUM) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(DC_ACK_STATIC_DATA_CHECKSUM) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(DC_ACK_STATIC_DATA_CHECKSUM); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(DC_ACK_STATIC_DATA_CHECKSUM))
           {
               size += sizeof(DC_ACK_STATIC_DATA_CHECKSUM);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(Checksum);
       }

       {
           thisSize += sizeof(StaticDataSize) * m_staticDataSizeList_size;
           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       {
           thisSize += sizeof(Checksum) * m_checksumList_size;
           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, DC_ACK_STATIC_DATA_CHECKSUM>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}staticDataChecksum: {}", tTabStr, t->Get_staticDataChecksum());
       if (0 == t->Get_staticDataSizeList_size())
       {
           result += std::format(L"\n{}staticDataSizeList: ARRAY[{}]", tTabStr, t->Get_staticDataSizeList_size());
       }
       else
       {
           result += std::format(L"\n{}staticDataSizeList: ARRAY[{}], ", tTabStr, t->Get_staticDataSizeList_size());
           //tTabStr += std::wstring(L"\t");
           for (size_t i = 0; i < t->Get_staticDataSizeList_size(); ++i)
           {
               result += std::format(L"\n{}{}", tTabStr, t->Get_staticDataSizeList()[i]);
           }
           //tTabStr.pop_back();
       }
       if (0 == t->Get_checksumList_size())
       {
           result += std::format(L"\n{}checksumList: ARRAY[{}]", tTabStr, t->Get_checksumList_size());
       }
       else
       {
           result += std::format(L"\n{}checksumList: ARRAY[{}], ", tTabStr, t->Get_checksumList_size());
           //tTabStr += std::wstring(L"\t");
           for (size_t i = 0; i < t->Get_checksumList_size(); ++i)
           {
               result += std::format(L"\n{}{}", tTabStr, t->Get_checksumList()[i]);
           }
           //tTabStr.pop_back();
       }
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class DC_ACK_STATIC_DATA;

class DC_ACK_STATIC_DATA_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::DC_ACK_STATIC_DATA;

public:
   // (4)
   explicit DC_ACK_STATIC_DATA_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_STATIC_DATA, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (5)
   explicit DC_ACK_STATIC_DATA_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_STATIC_DATA, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (6)
   explicit DC_ACK_STATIC_DATA_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_STATIC_DATA, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);
   }

   // (8)
   explicit DC_ACK_STATIC_DATA_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       StaticDataIndex index,
       uint8_t isCompleted,
       StaticDataSize offset,
       const uint8_t* staticDataBin,
       PacketSize staticDataBinSize
   )
   {
       WriteValue(index);

       WriteValue(isCompleted);

       WriteValue(offset);

       PacketSize& staticDataBinOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(staticDataBinSize);


       staticDataBinOffset = GetPacketSize();
       WriteBinary(staticDataBin, staticDataBinSize);

   }

   DC_ACK_STATIC_DATA& GetPacket() const noexcept { return *reinterpret_cast<DC_ACK_STATIC_DATA*>(GetPacketBufPtr()); }
   DC_ACK_STATIC_DATA* GetPacketPtr() const noexcept { return reinterpret_cast<DC_ACK_STATIC_DATA*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class DC_ACK_STATIC_DATA : public NetworkPacket
{
   public:
      using Writer = DC_ACK_STATIC_DATA_WRITER;


private:
   StaticDataIndex m_index;

   uint8_t m_isCompleted;

   StaticDataSize m_offset;

   PacketSize m_staticDataBin_offset = 0;
   PacketSize m_staticDataBin_size = 0;

public:
   DC_ACK_STATIC_DATA()
   {
       memset(this, 0, sizeof(DC_ACK_STATIC_DATA));
       mPacketSize = static_cast<PacketSize>(sizeof(DC_ACK_STATIC_DATA));
   }
   DC_ACK_STATIC_DATA(const DC_ACK_STATIC_DATA&) = delete;
   DC_ACK_STATIC_DATA(DC_ACK_STATIC_DATA &&) = delete;
   DC_ACK_STATIC_DATA& operator = (const DC_ACK_STATIC_DATA&) = delete;
   DC_ACK_STATIC_DATA& operator = (DC_ACK_STATIC_DATA &&) = delete;

   StaticDataIndex Get_index() const noexcept { return m_index; }
   StaticDataIndex& Ref_index() noexcept { return m_index; }
   const StaticDataIndex& ConstRef_index() const noexcept { return m_index; }

   uint8_t Get_isCompleted() const noexcept { return m_isCompleted; }
   uint8_t& Ref_isCompleted() noexcept { return m_isCompleted; }
   const uint8_t& ConstRef_isCompleted() const noexcept { return m_isCompleted; }

   StaticDataSize Get_offset() const noexcept { return m_offset; }
   StaticDataSize& Ref_offset() noexcept { return m_offset; }
   const StaticDataSize& ConstRef_offset() const noexcept { return m_offset; }

   const uint8_t* Get_staticDataBin() const noexcept { return ((uint8_t*)this + m_staticDataBin_offset); }
   PacketSize Get_staticDataBin_size() const noexcept { return m_staticDataBin_size; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(DC_ACK_STATIC_DATA) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(DC_ACK_STATIC_DATA) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(DC_ACK_STATIC_DATA); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(DC_ACK_STATIC_DATA))
           {
               size += sizeof(DC_ACK_STATIC_DATA);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(StaticDataIndex);
       }

       {
           thisSize += sizeof(uint8_t);
       }

       {
           thisSize += sizeof(StaticDataSize);
       }

       {
           if (GetPacketSize() < m_staticDataBin_offset)
               return false;

           thisSize += m_staticDataBin_size;
           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, DC_ACK_STATIC_DATA>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}index: {}", tTabStr, t->Get_index());
       result += std::format(L"\n{}isCompleted: {}", tTabStr, t->Get_isCompleted());
       result += std::format(L"\n{}offset: {}", tTabStr, t->Get_offset());
       result += std::format(L"\n{}staticDataBin: BIN[{}]", tTabStr, t->Get_staticDataBin_size());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class DC_ACK_USER_DATA;

class DC_ACK_USER_DATA_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::DC_ACK_USER_DATA;

public:
   // (4)
   explicit DC_ACK_USER_DATA_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_USER_DATA, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (5)
   explicit DC_ACK_USER_DATA_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_USER_DATA, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (6)
   explicit DC_ACK_USER_DATA_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_USER_DATA, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);
   }

   // (8)
   explicit DC_ACK_USER_DATA_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       const USER_DATA& userData,
       uint8_t isCompleted
   )
   {
       PacketSize& userDataOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(isCompleted);


       userDataOffset = GetPacketSize();
       WriteBinary((uint8_t*)&userData, userData.GetPacketSize());

   }

   void SetValues(
       const USER_DATA::Writer& userData,
       uint8_t isCompleted
   )
   {
       PacketSize& userDataOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(isCompleted);


       userDataOffset = GetPacketSize();
       WriteBinary(userData.GetPacketBufPtr(), userData.GetPacketSize());

   }

   DC_ACK_USER_DATA& GetPacket() const noexcept { return *reinterpret_cast<DC_ACK_USER_DATA*>(GetPacketBufPtr()); }
   DC_ACK_USER_DATA* GetPacketPtr() const noexcept { return reinterpret_cast<DC_ACK_USER_DATA*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class DC_ACK_USER_DATA : public NetworkPacket
{
   public:
      using Writer = DC_ACK_USER_DATA_WRITER;


private:
   PacketSize m_userData_offset = 0;

   uint8_t m_isCompleted;

public:
   DC_ACK_USER_DATA()
   {
       memset(this, 0, sizeof(DC_ACK_USER_DATA));
       mPacketSize = static_cast<PacketSize>(sizeof(DC_ACK_USER_DATA));
   }
   DC_ACK_USER_DATA(const DC_ACK_USER_DATA&) = delete;
   DC_ACK_USER_DATA(DC_ACK_USER_DATA &&) = delete;
   DC_ACK_USER_DATA& operator = (const DC_ACK_USER_DATA&) = delete;
   DC_ACK_USER_DATA& operator = (DC_ACK_USER_DATA &&) = delete;

   const USER_DATA& Get_userData() const noexcept { return *(USER_DATA*)((uint8_t*)this + m_userData_offset); }
   USER_DATA* Get_userData_ptr() const noexcept { return (USER_DATA*)((uint8_t*)this + m_userData_offset); }

   uint8_t Get_isCompleted() const noexcept { return m_isCompleted; }
   uint8_t& Ref_isCompleted() noexcept { return m_isCompleted; }
   const uint8_t& ConstRef_isCompleted() const noexcept { return m_isCompleted; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(DC_ACK_USER_DATA) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(DC_ACK_USER_DATA) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(DC_ACK_USER_DATA); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(DC_ACK_USER_DATA))
           {
               size += sizeof(DC_ACK_USER_DATA);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           if (GetPacketSize() < m_userData_offset)
               return false;

           const USER_DATA* _packet = reinterpret_cast<const USER_DATA*>(GetPacketBufPtr() + m_userData_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       {
           thisSize += sizeof(uint8_t);
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, DC_ACK_USER_DATA>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}userData: {}", tTabStr, t->Get_userData_ptr());
       result += std::format(L"\n{}isCompleted: {}", tTabStr, t->Get_isCompleted());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class DC_ACK_USER_LEVEL_UP;

class DC_ACK_USER_LEVEL_UP_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::DC_ACK_USER_LEVEL_UP;

public:
   // (4)
   explicit DC_ACK_USER_LEVEL_UP_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_USER_LEVEL_UP, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (5)
   explicit DC_ACK_USER_LEVEL_UP_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_USER_LEVEL_UP, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (6)
   explicit DC_ACK_USER_LEVEL_UP_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_USER_LEVEL_UP, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);
   }

   // (8)
   explicit DC_ACK_USER_LEVEL_UP_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       UserLevel userLevel
   )
   {
       WriteValue(userLevel);


   }

   DC_ACK_USER_LEVEL_UP& GetPacket() const noexcept { return *reinterpret_cast<DC_ACK_USER_LEVEL_UP*>(GetPacketBufPtr()); }
   DC_ACK_USER_LEVEL_UP* GetPacketPtr() const noexcept { return reinterpret_cast<DC_ACK_USER_LEVEL_UP*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class DC_ACK_USER_LEVEL_UP : public NetworkPacket
{
   public:
      using Writer = DC_ACK_USER_LEVEL_UP_WRITER;


private:
   UserLevel m_userLevel;

public:
   DC_ACK_USER_LEVEL_UP()
   {
       memset(this, 0, sizeof(DC_ACK_USER_LEVEL_UP));
       mPacketSize = static_cast<PacketSize>(sizeof(DC_ACK_USER_LEVEL_UP));
   }
   DC_ACK_USER_LEVEL_UP(const DC_ACK_USER_LEVEL_UP&) = delete;
   DC_ACK_USER_LEVEL_UP(DC_ACK_USER_LEVEL_UP &&) = delete;
   DC_ACK_USER_LEVEL_UP& operator = (const DC_ACK_USER_LEVEL_UP&) = delete;
   DC_ACK_USER_LEVEL_UP& operator = (DC_ACK_USER_LEVEL_UP &&) = delete;

   UserLevel Get_userLevel() const noexcept { return m_userLevel; }
   UserLevel& Ref_userLevel() noexcept { return m_userLevel; }
   const UserLevel& ConstRef_userLevel() const noexcept { return m_userLevel; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(DC_ACK_USER_LEVEL_UP) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(DC_ACK_USER_LEVEL_UP) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(DC_ACK_USER_LEVEL_UP); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(DC_ACK_USER_LEVEL_UP))
           {
               size += sizeof(DC_ACK_USER_LEVEL_UP);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(UserLevel);
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, DC_ACK_USER_LEVEL_UP>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}userLevel: {}", tTabStr, t->Get_userLevel());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class DC_ACK_ITEM_USE;

class DC_ACK_ITEM_USE_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::DC_ACK_ITEM_USE;

public:
   // (4)
   explicit DC_ACK_ITEM_USE_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_ITEM_USE, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (5)
   explicit DC_ACK_ITEM_USE_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_ITEM_USE, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (6)
   explicit DC_ACK_ITEM_USE_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_ITEM_USE, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);
   }

   // (8)
   explicit DC_ACK_ITEM_USE_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       ItemId itemId,
       ItemQuantity itemQuantity,
       const USER_CACHE_DIFF& userCacheDiff
   )
   {
       WriteValue(itemId);

       WriteValue(itemQuantity);

       PacketSize& userCacheDiffOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       userCacheDiffOffset = GetPacketSize();
       WriteBinary((uint8_t*)&userCacheDiff, userCacheDiff.GetPacketSize());

   }

   void SetValues(
       ItemId itemId,
       ItemQuantity itemQuantity,
       const USER_CACHE_DIFF::Writer& userCacheDiff
   )
   {
       WriteValue(itemId);

       WriteValue(itemQuantity);

       PacketSize& userCacheDiffOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       userCacheDiffOffset = GetPacketSize();
       WriteBinary(userCacheDiff.GetPacketBufPtr(), userCacheDiff.GetPacketSize());

   }

   DC_ACK_ITEM_USE& GetPacket() const noexcept { return *reinterpret_cast<DC_ACK_ITEM_USE*>(GetPacketBufPtr()); }
   DC_ACK_ITEM_USE* GetPacketPtr() const noexcept { return reinterpret_cast<DC_ACK_ITEM_USE*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class DC_ACK_ITEM_USE : public NetworkPacket
{
   public:
      using Writer = DC_ACK_ITEM_USE_WRITER;


private:
   ItemId m_itemId;

   ItemQuantity m_itemQuantity;

   PacketSize m_userCacheDiff_offset = 0;

public:
   DC_ACK_ITEM_USE()
   {
       memset(this, 0, sizeof(DC_ACK_ITEM_USE));
       mPacketSize = static_cast<PacketSize>(sizeof(DC_ACK_ITEM_USE));
   }
   DC_ACK_ITEM_USE(const DC_ACK_ITEM_USE&) = delete;
   DC_ACK_ITEM_USE(DC_ACK_ITEM_USE &&) = delete;
   DC_ACK_ITEM_USE& operator = (const DC_ACK_ITEM_USE&) = delete;
   DC_ACK_ITEM_USE& operator = (DC_ACK_ITEM_USE &&) = delete;

   ItemId Get_itemId() const noexcept { return m_itemId; }
   ItemId& Ref_itemId() noexcept { return m_itemId; }
   const ItemId& ConstRef_itemId() const noexcept { return m_itemId; }

   ItemQuantity Get_itemQuantity() const noexcept { return m_itemQuantity; }
   ItemQuantity& Ref_itemQuantity() noexcept { return m_itemQuantity; }
   const ItemQuantity& ConstRef_itemQuantity() const noexcept { return m_itemQuantity; }

   const USER_CACHE_DIFF& Get_userCacheDiff() const noexcept { return *(USER_CACHE_DIFF*)((uint8_t*)this + m_userCacheDiff_offset); }
   USER_CACHE_DIFF* Get_userCacheDiff_ptr() const noexcept { return (USER_CACHE_DIFF*)((uint8_t*)this + m_userCacheDiff_offset); }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(DC_ACK_ITEM_USE) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(DC_ACK_ITEM_USE) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(DC_ACK_ITEM_USE); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(DC_ACK_ITEM_USE))
           {
               size += sizeof(DC_ACK_ITEM_USE);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(ItemId);
       }

       {
           thisSize += sizeof(ItemQuantity);
       }

       {
           if (GetPacketSize() < m_userCacheDiff_offset)
               return false;

           const USER_CACHE_DIFF* _packet = reinterpret_cast<const USER_CACHE_DIFF*>(GetPacketBufPtr() + m_userCacheDiff_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, DC_ACK_ITEM_USE>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}itemId: {}", tTabStr, t->Get_itemId());
       result += std::format(L"\n{}itemQuantity: {}", tTabStr, t->Get_itemQuantity());
       result += std::format(L"\n{}userCacheDiff: {}", tTabStr, t->Get_userCacheDiff_ptr());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class DC_ACK_GAME_CREATE;

class DC_ACK_GAME_CREATE_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::DC_ACK_GAME_CREATE;

public:
   // (4)
   explicit DC_ACK_GAME_CREATE_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_GAME_CREATE, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (5)
   explicit DC_ACK_GAME_CREATE_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_GAME_CREATE, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (6)
   explicit DC_ACK_GAME_CREATE_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_GAME_CREATE, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);
   }

   // (8)
   explicit DC_ACK_GAME_CREATE_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       ItemId itemId,
       const USER_CACHE_DIFF& userCacheDiff,
       const GAME& game
   )
   {
       WriteValue(itemId);

       PacketSize& userCacheDiffOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       PacketSize& gameOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       userCacheDiffOffset = GetPacketSize();
       WriteBinary((uint8_t*)&userCacheDiff, userCacheDiff.GetPacketSize());

       gameOffset = GetPacketSize();
       WriteBinary((uint8_t*)&game, game.GetPacketSize());

   }

   void SetValues(
       ItemId itemId,
       const USER_CACHE_DIFF::Writer& userCacheDiff,
       const GAME::Writer& game
   )
   {
       WriteValue(itemId);

       PacketSize& userCacheDiffOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       PacketSize& gameOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       userCacheDiffOffset = GetPacketSize();
       WriteBinary(userCacheDiff.GetPacketBufPtr(), userCacheDiff.GetPacketSize());

       gameOffset = GetPacketSize();
       WriteBinary(game.GetPacketBufPtr(), game.GetPacketSize());

   }

   DC_ACK_GAME_CREATE& GetPacket() const noexcept { return *reinterpret_cast<DC_ACK_GAME_CREATE*>(GetPacketBufPtr()); }
   DC_ACK_GAME_CREATE* GetPacketPtr() const noexcept { return reinterpret_cast<DC_ACK_GAME_CREATE*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class DC_ACK_GAME_CREATE : public NetworkPacket
{
   public:
      using Writer = DC_ACK_GAME_CREATE_WRITER;


private:
   ItemId m_itemId;

   PacketSize m_userCacheDiff_offset = 0;

   PacketSize m_game_offset = 0;

public:
   DC_ACK_GAME_CREATE()
   {
       memset(this, 0, sizeof(DC_ACK_GAME_CREATE));
       mPacketSize = static_cast<PacketSize>(sizeof(DC_ACK_GAME_CREATE));
   }
   DC_ACK_GAME_CREATE(const DC_ACK_GAME_CREATE&) = delete;
   DC_ACK_GAME_CREATE(DC_ACK_GAME_CREATE &&) = delete;
   DC_ACK_GAME_CREATE& operator = (const DC_ACK_GAME_CREATE&) = delete;
   DC_ACK_GAME_CREATE& operator = (DC_ACK_GAME_CREATE &&) = delete;

   ItemId Get_itemId() const noexcept { return m_itemId; }
   ItemId& Ref_itemId() noexcept { return m_itemId; }
   const ItemId& ConstRef_itemId() const noexcept { return m_itemId; }

   const USER_CACHE_DIFF& Get_userCacheDiff() const noexcept { return *(USER_CACHE_DIFF*)((uint8_t*)this + m_userCacheDiff_offset); }
   USER_CACHE_DIFF* Get_userCacheDiff_ptr() const noexcept { return (USER_CACHE_DIFF*)((uint8_t*)this + m_userCacheDiff_offset); }

   const GAME& Get_game() const noexcept { return *(GAME*)((uint8_t*)this + m_game_offset); }
   GAME* Get_game_ptr() const noexcept { return (GAME*)((uint8_t*)this + m_game_offset); }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(DC_ACK_GAME_CREATE) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(DC_ACK_GAME_CREATE) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(DC_ACK_GAME_CREATE); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(DC_ACK_GAME_CREATE))
           {
               size += sizeof(DC_ACK_GAME_CREATE);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(ItemId);
       }

       {
           if (GetPacketSize() < m_userCacheDiff_offset)
               return false;

           const USER_CACHE_DIFF* _packet = reinterpret_cast<const USER_CACHE_DIFF*>(GetPacketBufPtr() + m_userCacheDiff_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       {
           if (GetPacketSize() < m_game_offset)
               return false;

           const GAME* _packet = reinterpret_cast<const GAME*>(GetPacketBufPtr() + m_game_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, DC_ACK_GAME_CREATE>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}itemId: {}", tTabStr, t->Get_itemId());
       result += std::format(L"\n{}userCacheDiff: {}", tTabStr, t->Get_userCacheDiff_ptr());
       result += std::format(L"\n{}game: {}", tTabStr, t->Get_game_ptr());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class DC_ACK_GAME_USER_ENTER;

class DC_ACK_GAME_USER_ENTER_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::DC_ACK_GAME_USER_ENTER;

public:
   // (4)
   explicit DC_ACK_GAME_USER_ENTER_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_GAME_USER_ENTER, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);

   }

   // (5)
   explicit DC_ACK_GAME_USER_ENTER_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_GAME_USER_ENTER, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);

   }

   // (6)
   explicit DC_ACK_GAME_USER_ENTER_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_GAME_USER_ENTER, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);

   }

   // (8)
   explicit DC_ACK_GAME_USER_ENTER_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   DC_ACK_GAME_USER_ENTER& GetPacket() const noexcept { return *reinterpret_cast<DC_ACK_GAME_USER_ENTER*>(GetPacketBufPtr()); }
   DC_ACK_GAME_USER_ENTER* GetPacketPtr() const noexcept { return reinterpret_cast<DC_ACK_GAME_USER_ENTER*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class DC_ACK_GAME_USER_ENTER : public NetworkPacket
{
   public:
      using Writer = DC_ACK_GAME_USER_ENTER_WRITER;


private:
public:
   DC_ACK_GAME_USER_ENTER()
   {
       memset(this, 0, sizeof(DC_ACK_GAME_USER_ENTER));
       mPacketSize = static_cast<PacketSize>(sizeof(DC_ACK_GAME_USER_ENTER));
   }
   DC_ACK_GAME_USER_ENTER(const DC_ACK_GAME_USER_ENTER&) = delete;
   DC_ACK_GAME_USER_ENTER(DC_ACK_GAME_USER_ENTER &&) = delete;
   DC_ACK_GAME_USER_ENTER& operator = (const DC_ACK_GAME_USER_ENTER&) = delete;
   DC_ACK_GAME_USER_ENTER& operator = (DC_ACK_GAME_USER_ENTER &&) = delete;


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(DC_ACK_GAME_USER_ENTER) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(DC_ACK_GAME_USER_ENTER) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(DC_ACK_GAME_USER_ENTER); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(DC_ACK_GAME_USER_ENTER))
           {
               size += sizeof(DC_ACK_GAME_USER_ENTER);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, DC_ACK_GAME_USER_ENTER>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class DC_ACK_GAME_USER_LEAVE;

class DC_ACK_GAME_USER_LEAVE_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::DC_ACK_GAME_USER_LEAVE;

public:
   // (4)
   explicit DC_ACK_GAME_USER_LEAVE_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_GAME_USER_LEAVE, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);

   }

   // (5)
   explicit DC_ACK_GAME_USER_LEAVE_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_GAME_USER_LEAVE, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);

   }

   // (6)
   explicit DC_ACK_GAME_USER_LEAVE_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_GAME_USER_LEAVE, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);

   }

   // (8)
   explicit DC_ACK_GAME_USER_LEAVE_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   DC_ACK_GAME_USER_LEAVE& GetPacket() const noexcept { return *reinterpret_cast<DC_ACK_GAME_USER_LEAVE*>(GetPacketBufPtr()); }
   DC_ACK_GAME_USER_LEAVE* GetPacketPtr() const noexcept { return reinterpret_cast<DC_ACK_GAME_USER_LEAVE*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class DC_ACK_GAME_USER_LEAVE : public NetworkPacket
{
   public:
      using Writer = DC_ACK_GAME_USER_LEAVE_WRITER;


private:
public:
   DC_ACK_GAME_USER_LEAVE()
   {
       memset(this, 0, sizeof(DC_ACK_GAME_USER_LEAVE));
       mPacketSize = static_cast<PacketSize>(sizeof(DC_ACK_GAME_USER_LEAVE));
   }
   DC_ACK_GAME_USER_LEAVE(const DC_ACK_GAME_USER_LEAVE&) = delete;
   DC_ACK_GAME_USER_LEAVE(DC_ACK_GAME_USER_LEAVE &&) = delete;
   DC_ACK_GAME_USER_LEAVE& operator = (const DC_ACK_GAME_USER_LEAVE&) = delete;
   DC_ACK_GAME_USER_LEAVE& operator = (DC_ACK_GAME_USER_LEAVE &&) = delete;


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(DC_ACK_GAME_USER_LEAVE) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(DC_ACK_GAME_USER_LEAVE) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(DC_ACK_GAME_USER_LEAVE); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(DC_ACK_GAME_USER_LEAVE))
           {
               size += sizeof(DC_ACK_GAME_USER_LEAVE);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, DC_ACK_GAME_USER_LEAVE>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class DC_ACK_MAIL_LIST;

class DC_ACK_MAIL_LIST_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::DC_ACK_MAIL_LIST;

public:
   // (4)
   explicit DC_ACK_MAIL_LIST_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_MAIL_LIST, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);

   }

   // (5)
   explicit DC_ACK_MAIL_LIST_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_MAIL_LIST, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);

   }

   // (6)
   explicit DC_ACK_MAIL_LIST_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_MAIL_LIST, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);

   }

   // (8)
   explicit DC_ACK_MAIL_LIST_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   DC_ACK_MAIL_LIST& GetPacket() const noexcept { return *reinterpret_cast<DC_ACK_MAIL_LIST*>(GetPacketBufPtr()); }
   DC_ACK_MAIL_LIST* GetPacketPtr() const noexcept { return reinterpret_cast<DC_ACK_MAIL_LIST*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class DC_ACK_MAIL_LIST : public NetworkPacket
{
   public:
      using Writer = DC_ACK_MAIL_LIST_WRITER;


private:
public:
   DC_ACK_MAIL_LIST()
   {
       memset(this, 0, sizeof(DC_ACK_MAIL_LIST));
       mPacketSize = static_cast<PacketSize>(sizeof(DC_ACK_MAIL_LIST));
   }
   DC_ACK_MAIL_LIST(const DC_ACK_MAIL_LIST&) = delete;
   DC_ACK_MAIL_LIST(DC_ACK_MAIL_LIST &&) = delete;
   DC_ACK_MAIL_LIST& operator = (const DC_ACK_MAIL_LIST&) = delete;
   DC_ACK_MAIL_LIST& operator = (DC_ACK_MAIL_LIST &&) = delete;


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(DC_ACK_MAIL_LIST) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(DC_ACK_MAIL_LIST) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(DC_ACK_MAIL_LIST); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(DC_ACK_MAIL_LIST))
           {
               size += sizeof(DC_ACK_MAIL_LIST);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, DC_ACK_MAIL_LIST>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class DC_ACK_MAIL_READ;

class DC_ACK_MAIL_READ_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::DC_ACK_MAIL_READ;

public:
   // (4)
   explicit DC_ACK_MAIL_READ_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_MAIL_READ, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (5)
   explicit DC_ACK_MAIL_READ_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_MAIL_READ, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (6)
   explicit DC_ACK_MAIL_READ_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::DC_ACK_MAIL_READ, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);
   }

   // (8)
   explicit DC_ACK_MAIL_READ_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       const MailId* MailIdList,
       PacketSize MailIdListSize,
       const USER_CACHE_DIFF& userCacheDiff
   )
   {
       PacketSize& MailIdListOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(MailIdListSize);

       PacketSize& userCacheDiffOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       MailIdListOffset = GetPacketSize();
       WriteBinary((uint8_t*)MailIdList, sizeof(MailId) * MailIdListSize);

       userCacheDiffOffset = GetPacketSize();
       WriteBinary((uint8_t*)&userCacheDiff, userCacheDiff.GetPacketSize());

   }

   void SetValues(
       const MailId* MailIdList,
       PacketSize MailIdListSize,
       const USER_CACHE_DIFF::Writer& userCacheDiff
   )
   {
       PacketSize& MailIdListOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(MailIdListSize);

       PacketSize& userCacheDiffOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       MailIdListOffset = GetPacketSize();
       WriteBinary((uint8_t*)MailIdList, sizeof(MailId) * MailIdListSize);

       userCacheDiffOffset = GetPacketSize();
       WriteBinary(userCacheDiff.GetPacketBufPtr(), userCacheDiff.GetPacketSize());

   }

   DC_ACK_MAIL_READ& GetPacket() const noexcept { return *reinterpret_cast<DC_ACK_MAIL_READ*>(GetPacketBufPtr()); }
   DC_ACK_MAIL_READ* GetPacketPtr() const noexcept { return reinterpret_cast<DC_ACK_MAIL_READ*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class DC_ACK_MAIL_READ : public NetworkPacket
{
   public:
      using Writer = DC_ACK_MAIL_READ_WRITER;


private:
   PacketSize m_MailIdList_offset = 0;
   PacketSize m_MailIdList_size = 0;

   PacketSize m_userCacheDiff_offset = 0;

public:
   DC_ACK_MAIL_READ()
   {
       memset(this, 0, sizeof(DC_ACK_MAIL_READ));
       mPacketSize = static_cast<PacketSize>(sizeof(DC_ACK_MAIL_READ));
   }
   DC_ACK_MAIL_READ(const DC_ACK_MAIL_READ&) = delete;
   DC_ACK_MAIL_READ(DC_ACK_MAIL_READ &&) = delete;
   DC_ACK_MAIL_READ& operator = (const DC_ACK_MAIL_READ&) = delete;
   DC_ACK_MAIL_READ& operator = (DC_ACK_MAIL_READ &&) = delete;

   const MailId* Get_MailIdList() const noexcept { return (MailId*)((uint8_t*)this + m_MailIdList_offset); }
   PacketSize Get_MailIdList_size() const noexcept { return m_MailIdList_size; }

   const USER_CACHE_DIFF& Get_userCacheDiff() const noexcept { return *(USER_CACHE_DIFF*)((uint8_t*)this + m_userCacheDiff_offset); }
   USER_CACHE_DIFF* Get_userCacheDiff_ptr() const noexcept { return (USER_CACHE_DIFF*)((uint8_t*)this + m_userCacheDiff_offset); }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(DC_ACK_MAIL_READ) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(DC_ACK_MAIL_READ) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(DC_ACK_MAIL_READ); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(DC_ACK_MAIL_READ))
           {
               size += sizeof(DC_ACK_MAIL_READ);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(MailId) * m_MailIdList_size;
           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       {
           if (GetPacketSize() < m_userCacheDiff_offset)
               return false;

           const USER_CACHE_DIFF* _packet = reinterpret_cast<const USER_CACHE_DIFF*>(GetPacketBufPtr() + m_userCacheDiff_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, DC_ACK_MAIL_READ>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       if (0 == t->Get_MailIdList_size())
       {
           result += std::format(L"\n{}MailIdList: ARRAY[{}]", tTabStr, t->Get_MailIdList_size());
       }
       else
       {
           result += std::format(L"\n{}MailIdList: ARRAY[{}], ", tTabStr, t->Get_MailIdList_size());
           //tTabStr += std::wstring(L"\t");
           for (size_t i = 0; i < t->Get_MailIdList_size(); ++i)
           {
               result += std::format(L"\n{}{}", tTabStr, t->Get_MailIdList()[i]);
           }
           //tTabStr.pop_back();
       }
       result += std::format(L"\n{}userCacheDiff: {}", tTabStr, t->Get_userCacheDiff_ptr());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

#pragma pack(pop)

inline bool ValidatePacketDC(const Packet& rp)
{
   static constexpr bool(*ValidatePacketFuncArray[PacketTypes::DC_PACKET_END - PacketTypes::DC_PACKET_START - 1])(const Packet&) =
   {
       &ValidatePacketFunc<DC_ERROR>,
       &ValidatePacketFunc<DC_ACK_CHEAT>,
       &ValidatePacketFunc<DC_ACK_STATIC_DATA_CHECKSUM>,
       &ValidatePacketFunc<DC_ACK_STATIC_DATA>,
       &ValidatePacketFunc<DC_ACK_USER_DATA>,
       &ValidatePacketFunc<DC_ACK_USER_LEVEL_UP>,
       &ValidatePacketFunc<DC_ACK_ITEM_USE>,
       &ValidatePacketFunc<DC_ACK_GAME_CREATE>,
       &ValidatePacketFunc<DC_ACK_GAME_USER_ENTER>,
       &ValidatePacketFunc<DC_ACK_GAME_USER_LEAVE>,
       &ValidatePacketFunc<DC_ACK_MAIL_LIST>,
       &ValidatePacketFunc<DC_ACK_MAIL_READ>
   };

   if ((PacketTypes::DC_PACKET_START >= rp.GetPacketType()) ||
       (PacketTypes::DC_PACKET_END <= rp.GetPacketType()))
   {
       return true;
   }

   return ValidatePacketFuncArray[rp.GetPacketType() - PacketTypes::DC_PACKET_START - 1](rp);
}

template <typename _Owner, typename... _Args>
HandleResult DispatchPacketDC(uint64_t socket, _Owner* owner, NetworkPacket& rp, _Args&&... args)
{
   HandleResult handleResult = DispatchPacketCOMMON(socket, owner, rp, std::forward<_Args>(args)...);
   if (handleResult != HandleResult::NOT_EXISTS)
       return handleResult;
   
   static constexpr HandleResult(*DispatchPacketFuncArray[PacketTypes::DC_PACKET_END - PacketTypes::DC_PACKET_START - 1])(uint64_t, _Owner*, NetworkPacket&, _Args&&...) =
   {
       &DispatchPacketFunc<_Owner, DC_ERROR, _Args&&...>,
       &DispatchPacketFunc<_Owner, DC_ACK_CHEAT, _Args&&...>,
       &DispatchPacketFunc<_Owner, DC_ACK_STATIC_DATA_CHECKSUM, _Args&&...>,
       &DispatchPacketFunc<_Owner, DC_ACK_STATIC_DATA, _Args&&...>,
       &DispatchPacketFunc<_Owner, DC_ACK_USER_DATA, _Args&&...>,
       &DispatchPacketFunc<_Owner, DC_ACK_USER_LEVEL_UP, _Args&&...>,
       &DispatchPacketFunc<_Owner, DC_ACK_ITEM_USE, _Args&&...>,
       &DispatchPacketFunc<_Owner, DC_ACK_GAME_CREATE, _Args&&...>,
       &DispatchPacketFunc<_Owner, DC_ACK_GAME_USER_ENTER, _Args&&...>,
       &DispatchPacketFunc<_Owner, DC_ACK_GAME_USER_LEAVE, _Args&&...>,
       &DispatchPacketFunc<_Owner, DC_ACK_MAIL_LIST, _Args&&...>,
       &DispatchPacketFunc<_Owner, DC_ACK_MAIL_READ, _Args&&...>
   };

   if ((PacketTypes::DC_PACKET_START >= rp.GetPacketType()) ||
       (PacketTypes::DC_PACKET_END <= rp.GetPacketType()))
   {
       return HandleResult::NOT_EXISTS;
   }

   if (auto func = DispatchPacketFuncArray[rp.GetPacketType() - PacketTypes::DC_PACKET_START - 1])
       return func(socket, owner, rp, std::forward<_Args>(args)...);
   else
       return HandleResult::NOT_EXISTS;
}

