// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"
#include "Packet/NetworkPacket/NetworkPacket.h"
#include "Packet/NetworkPacket/NetworkPacketWriter.h"
#include "Packet/BasePacket/PacketWriter.h"
#include "Packet/PacketDataList/PacketDataList.h"
#include "Packet/PacketFuncs/PacketValidator.h"
#include "Packet/PacketFuncs/PacketDispatcher.h"

#pragma pack(push, 1)

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class GF_GC_BYPASS;

class GF_GC_BYPASS_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::GF_GC_BYPASS;

public:
   // (7)
   explicit GF_GC_BYPASS_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::GF_GC_BYPASS, buf)
   {
   }

   // (9)
   explicit GF_GC_BYPASS_WRITER(
       PacketTraitParam trait, uint8_t* buf,
       const UserId* userIdList,
       PacketSize userIdListSize,
       const uint8_t* nestedPacket,
       PacketSize nestedPacketSize
   )
       :
       NetworkPacketWriter(trait, PacketTypes::GF_GC_BYPASS, buf)
   {
       PacketSize& userIdListOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(userIdListSize);

       PacketSize& nestedPacketOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(nestedPacketSize);


       userIdListOffset = GetPacketSize();
       WriteBinary((uint8_t*)userIdList, sizeof(UserId) * userIdListSize);

       nestedPacketOffset = GetPacketSize();
       WriteBinary(nestedPacket, nestedPacketSize);

   }

   // (8)
   explicit GF_GC_BYPASS_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       const UserId* userIdList,
       PacketSize userIdListSize,
       const uint8_t* nestedPacket,
       PacketSize nestedPacketSize
   )
   {
       PacketSize& userIdListOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(userIdListSize);

       PacketSize& nestedPacketOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(nestedPacketSize);


       userIdListOffset = GetPacketSize();
       WriteBinary((uint8_t*)userIdList, sizeof(UserId) * userIdListSize);

       nestedPacketOffset = GetPacketSize();
       WriteBinary(nestedPacket, nestedPacketSize);

   }

   GF_GC_BYPASS& GetPacket() const noexcept { return *reinterpret_cast<GF_GC_BYPASS*>(GetPacketBufPtr()); }
   GF_GC_BYPASS* GetPacketPtr() const noexcept { return reinterpret_cast<GF_GC_BYPASS*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class GF_GC_BYPASS : public NetworkPacket
{
   public:
      using Writer = GF_GC_BYPASS_WRITER;


private:
   PacketSize m_userIdList_offset = 0;
   PacketSize m_userIdList_size = 0;

   PacketSize m_nestedPacket_offset = 0;
   PacketSize m_nestedPacket_size = 0;

public:
   GF_GC_BYPASS()
   {
       memset(this, 0, sizeof(GF_GC_BYPASS));
       mPacketSize = static_cast<PacketSize>(sizeof(GF_GC_BYPASS));
   }
   GF_GC_BYPASS(const GF_GC_BYPASS&) = delete;
   GF_GC_BYPASS(GF_GC_BYPASS &&) = delete;
   GF_GC_BYPASS& operator = (const GF_GC_BYPASS&) = delete;
   GF_GC_BYPASS& operator = (GF_GC_BYPASS &&) = delete;

   const UserId* Get_userIdList() const noexcept { return (UserId*)((uint8_t*)this + m_userIdList_offset); }
   PacketSize Get_userIdList_size() const noexcept { return m_userIdList_size; }

   const uint8_t* Get_nestedPacket() const noexcept { return ((uint8_t*)this + m_nestedPacket_offset); }
   PacketSize Get_nestedPacket_size() const noexcept { return m_nestedPacket_size; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(GF_GC_BYPASS) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(GF_GC_BYPASS) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(GF_GC_BYPASS); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(GF_GC_BYPASS))
           {
               size += sizeof(GF_GC_BYPASS);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(UserId) * m_userIdList_size;
           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       {
           if (GetPacketSize() < m_nestedPacket_offset)
               return false;

           thisSize += m_nestedPacket_size;
           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, GF_GC_BYPASS>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       if (0 == t->Get_userIdList_size())
       {
           result += std::format(L"\n{}userIdList: ARRAY[{}]", tTabStr, t->Get_userIdList_size());
       }
       else
       {
           result += std::format(L"\n{}userIdList: ARRAY[{}], ", tTabStr, t->Get_userIdList_size());
           //tTabStr += std::wstring(L"\t");
           for (size_t i = 0; i < t->Get_userIdList_size(); ++i)
           {
               result += std::format(L"\n{}{}", tTabStr, t->Get_userIdList()[i]);
           }
           //tTabStr.pop_back();
       }
       result += std::format(L"\n{}nestedPacket: BIN[{}]", tTabStr, t->Get_nestedPacket_size());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class GF_GC_BYPASS_GAME;

class GF_GC_BYPASS_GAME_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::GF_GC_BYPASS_GAME;

public:
   // (7)
   explicit GF_GC_BYPASS_GAME_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::GF_GC_BYPASS_GAME, buf)
   {
   }

   // (9)
   explicit GF_GC_BYPASS_GAME_WRITER(
       PacketTraitParam trait, uint8_t* buf,
       const uint8_t* nestedPacket,
       PacketSize nestedPacketSize
   )
       :
       NetworkPacketWriter(trait, PacketTypes::GF_GC_BYPASS_GAME, buf)
   {
       PacketSize& nestedPacketOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(nestedPacketSize);


       nestedPacketOffset = GetPacketSize();
       WriteBinary(nestedPacket, nestedPacketSize);

   }

   // (8)
   explicit GF_GC_BYPASS_GAME_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       const uint8_t* nestedPacket,
       PacketSize nestedPacketSize
   )
   {
       PacketSize& nestedPacketOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(nestedPacketSize);


       nestedPacketOffset = GetPacketSize();
       WriteBinary(nestedPacket, nestedPacketSize);

   }

   GF_GC_BYPASS_GAME& GetPacket() const noexcept { return *reinterpret_cast<GF_GC_BYPASS_GAME*>(GetPacketBufPtr()); }
   GF_GC_BYPASS_GAME* GetPacketPtr() const noexcept { return reinterpret_cast<GF_GC_BYPASS_GAME*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class GF_GC_BYPASS_GAME : public NetworkPacket
{
   public:
      using Writer = GF_GC_BYPASS_GAME_WRITER;


private:
   PacketSize m_nestedPacket_offset = 0;
   PacketSize m_nestedPacket_size = 0;

public:
   GF_GC_BYPASS_GAME()
   {
       memset(this, 0, sizeof(GF_GC_BYPASS_GAME));
       mPacketSize = static_cast<PacketSize>(sizeof(GF_GC_BYPASS_GAME));
   }
   GF_GC_BYPASS_GAME(const GF_GC_BYPASS_GAME&) = delete;
   GF_GC_BYPASS_GAME(GF_GC_BYPASS_GAME &&) = delete;
   GF_GC_BYPASS_GAME& operator = (const GF_GC_BYPASS_GAME&) = delete;
   GF_GC_BYPASS_GAME& operator = (GF_GC_BYPASS_GAME &&) = delete;

   const uint8_t* Get_nestedPacket() const noexcept { return ((uint8_t*)this + m_nestedPacket_offset); }
   PacketSize Get_nestedPacket_size() const noexcept { return m_nestedPacket_size; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(GF_GC_BYPASS_GAME) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(GF_GC_BYPASS_GAME) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(GF_GC_BYPASS_GAME); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(GF_GC_BYPASS_GAME))
           {
               size += sizeof(GF_GC_BYPASS_GAME);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           if (GetPacketSize() < m_nestedPacket_offset)
               return false;

           thisSize += m_nestedPacket_size;
           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, GF_GC_BYPASS_GAME>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}nestedPacket: BIN[{}]", tTabStr, t->Get_nestedPacket_size());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class GF_ACK_GAME_CHANNEL_USER_ENTER;

class GF_ACK_GAME_CHANNEL_USER_ENTER_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::GF_ACK_GAME_CHANNEL_USER_ENTER;

public:
   // (4)
   explicit GF_ACK_GAME_CHANNEL_USER_ENTER_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::GF_ACK_GAME_CHANNEL_USER_ENTER, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);

   }

   // (5)
   explicit GF_ACK_GAME_CHANNEL_USER_ENTER_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::GF_ACK_GAME_CHANNEL_USER_ENTER, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);

   }

   // (6)
   explicit GF_ACK_GAME_CHANNEL_USER_ENTER_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::GF_ACK_GAME_CHANNEL_USER_ENTER, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);

   }

   // (8)
   explicit GF_ACK_GAME_CHANNEL_USER_ENTER_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   GF_ACK_GAME_CHANNEL_USER_ENTER& GetPacket() const noexcept { return *reinterpret_cast<GF_ACK_GAME_CHANNEL_USER_ENTER*>(GetPacketBufPtr()); }
   GF_ACK_GAME_CHANNEL_USER_ENTER* GetPacketPtr() const noexcept { return reinterpret_cast<GF_ACK_GAME_CHANNEL_USER_ENTER*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class GF_ACK_GAME_CHANNEL_USER_ENTER : public NetworkPacket
{
   public:
      using Writer = GF_ACK_GAME_CHANNEL_USER_ENTER_WRITER;


private:
public:
   GF_ACK_GAME_CHANNEL_USER_ENTER()
   {
       memset(this, 0, sizeof(GF_ACK_GAME_CHANNEL_USER_ENTER));
       mPacketSize = static_cast<PacketSize>(sizeof(GF_ACK_GAME_CHANNEL_USER_ENTER));
   }
   GF_ACK_GAME_CHANNEL_USER_ENTER(const GF_ACK_GAME_CHANNEL_USER_ENTER&) = delete;
   GF_ACK_GAME_CHANNEL_USER_ENTER(GF_ACK_GAME_CHANNEL_USER_ENTER &&) = delete;
   GF_ACK_GAME_CHANNEL_USER_ENTER& operator = (const GF_ACK_GAME_CHANNEL_USER_ENTER&) = delete;
   GF_ACK_GAME_CHANNEL_USER_ENTER& operator = (GF_ACK_GAME_CHANNEL_USER_ENTER &&) = delete;


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(GF_ACK_GAME_CHANNEL_USER_ENTER) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(GF_ACK_GAME_CHANNEL_USER_ENTER) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(GF_ACK_GAME_CHANNEL_USER_ENTER); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(GF_ACK_GAME_CHANNEL_USER_ENTER))
           {
               size += sizeof(GF_ACK_GAME_CHANNEL_USER_ENTER);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, GF_ACK_GAME_CHANNEL_USER_ENTER>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class GF_GAME_CHANNEL_USER_LEAVE;

class GF_GAME_CHANNEL_USER_LEAVE_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::GF_GAME_CHANNEL_USER_LEAVE;

public:
   // (7)
   explicit GF_GAME_CHANNEL_USER_LEAVE_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::GF_GAME_CHANNEL_USER_LEAVE, buf)
   {

   }

   // (8)
   explicit GF_GAME_CHANNEL_USER_LEAVE_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   GF_GAME_CHANNEL_USER_LEAVE& GetPacket() const noexcept { return *reinterpret_cast<GF_GAME_CHANNEL_USER_LEAVE*>(GetPacketBufPtr()); }
   GF_GAME_CHANNEL_USER_LEAVE* GetPacketPtr() const noexcept { return reinterpret_cast<GF_GAME_CHANNEL_USER_LEAVE*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class GF_GAME_CHANNEL_USER_LEAVE : public NetworkPacket
{
   public:
      using Writer = GF_GAME_CHANNEL_USER_LEAVE_WRITER;


private:
public:
   GF_GAME_CHANNEL_USER_LEAVE()
   {
       memset(this, 0, sizeof(GF_GAME_CHANNEL_USER_LEAVE));
       mPacketSize = static_cast<PacketSize>(sizeof(GF_GAME_CHANNEL_USER_LEAVE));
   }
   GF_GAME_CHANNEL_USER_LEAVE(const GF_GAME_CHANNEL_USER_LEAVE&) = delete;
   GF_GAME_CHANNEL_USER_LEAVE(GF_GAME_CHANNEL_USER_LEAVE &&) = delete;
   GF_GAME_CHANNEL_USER_LEAVE& operator = (const GF_GAME_CHANNEL_USER_LEAVE&) = delete;
   GF_GAME_CHANNEL_USER_LEAVE& operator = (GF_GAME_CHANNEL_USER_LEAVE &&) = delete;


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(GF_GAME_CHANNEL_USER_LEAVE) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(GF_GAME_CHANNEL_USER_LEAVE) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(GF_GAME_CHANNEL_USER_LEAVE); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(GF_GAME_CHANNEL_USER_LEAVE))
           {
               size += sizeof(GF_GAME_CHANNEL_USER_LEAVE);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, GF_GAME_CHANNEL_USER_LEAVE>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class GF_GAME_FINISHED;

class GF_GAME_FINISHED_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::GF_GAME_FINISHED;

public:
   // (7)
   explicit GF_GAME_FINISHED_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::GF_GAME_FINISHED, buf)
   {

   }

   // (8)
   explicit GF_GAME_FINISHED_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   GF_GAME_FINISHED& GetPacket() const noexcept { return *reinterpret_cast<GF_GAME_FINISHED*>(GetPacketBufPtr()); }
   GF_GAME_FINISHED* GetPacketPtr() const noexcept { return reinterpret_cast<GF_GAME_FINISHED*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class GF_GAME_FINISHED : public NetworkPacket
{
   public:
      using Writer = GF_GAME_FINISHED_WRITER;


private:
public:
   GF_GAME_FINISHED()
   {
       memset(this, 0, sizeof(GF_GAME_FINISHED));
       mPacketSize = static_cast<PacketSize>(sizeof(GF_GAME_FINISHED));
   }
   GF_GAME_FINISHED(const GF_GAME_FINISHED&) = delete;
   GF_GAME_FINISHED(GF_GAME_FINISHED &&) = delete;
   GF_GAME_FINISHED& operator = (const GF_GAME_FINISHED&) = delete;
   GF_GAME_FINISHED& operator = (GF_GAME_FINISHED &&) = delete;


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(GF_GAME_FINISHED) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(GF_GAME_FINISHED) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(GF_GAME_FINISHED); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(GF_GAME_FINISHED))
           {
               size += sizeof(GF_GAME_FINISHED);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, GF_GAME_FINISHED>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

#pragma pack(pop)

inline bool ValidatePacketGF(const Packet& rp)
{
   static constexpr bool(*ValidatePacketFuncArray[PacketTypes::GF_PACKET_END - PacketTypes::GF_PACKET_START - 1])(const Packet&) =
   {
       &ValidatePacketFunc<GF_GC_BYPASS>,
       &ValidatePacketFunc<GF_GC_BYPASS_GAME>,
       &ValidatePacketFunc<GF_ACK_GAME_CHANNEL_USER_ENTER>,
       &ValidatePacketFunc<GF_GAME_CHANNEL_USER_LEAVE>,
       &ValidatePacketFunc<GF_GAME_FINISHED>
   };

   if ((PacketTypes::GF_PACKET_START >= rp.GetPacketType()) ||
       (PacketTypes::GF_PACKET_END <= rp.GetPacketType()))
   {
       return true;
   }

   return ValidatePacketFuncArray[rp.GetPacketType() - PacketTypes::GF_PACKET_START - 1](rp);
}

template <typename _Owner, typename... _Args>
HandleResult DispatchPacketGF(uint64_t socket, _Owner* owner, NetworkPacket& rp, _Args&&... args)
{
   HandleResult handleResult = DispatchPacketCOMMON(socket, owner, rp, std::forward<_Args>(args)...);
   if (handleResult != HandleResult::NOT_EXISTS)
       return handleResult;
   
   static constexpr HandleResult(*DispatchPacketFuncArray[PacketTypes::GF_PACKET_END - PacketTypes::GF_PACKET_START - 1])(uint64_t, _Owner*, NetworkPacket&, _Args&&...) =
   {
       &DispatchPacketFunc<_Owner, GF_GC_BYPASS, _Args&&...>,
       &DispatchPacketFunc<_Owner, GF_GC_BYPASS_GAME, _Args&&...>,
       &DispatchPacketFunc<_Owner, GF_ACK_GAME_CHANNEL_USER_ENTER, _Args&&...>,
       &DispatchPacketFunc<_Owner, GF_GAME_CHANNEL_USER_LEAVE, _Args&&...>,
       &DispatchPacketFunc<_Owner, GF_GAME_FINISHED, _Args&&...>
   };

   if ((PacketTypes::GF_PACKET_START >= rp.GetPacketType()) ||
       (PacketTypes::GF_PACKET_END <= rp.GetPacketType()))
   {
       return HandleResult::NOT_EXISTS;
   }

   if (auto func = DispatchPacketFuncArray[rp.GetPacketType() - PacketTypes::GF_PACKET_START - 1])
       return func(socket, owner, rp, std::forward<_Args>(args)...);
   else
       return HandleResult::NOT_EXISTS;
}

