// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"
#include "Packet/NetworkPacket/NetworkPacket.h"
#include "Packet/NetworkPacket/NetworkPacketWriter.h"
#include "Packet/BasePacket/PacketWriter.h"
#include "Packet/PacketDataList/PacketDataList.h"
#include "Packet/PacketFuncs/PacketValidator.h"
#include "Packet/PacketFuncs/PacketDispatcher.h"

#pragma pack(push, 1)

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class MF;

class MF_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::MF;

public:
   // (7)
   explicit MF_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::MF, buf)
   {

   }

   // (8)
   explicit MF_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   MF& GetPacket() const noexcept { return *reinterpret_cast<MF*>(GetPacketBufPtr()); }
   MF* GetPacketPtr() const noexcept { return reinterpret_cast<MF*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class MF : public NetworkPacket
{
   public:
      using Writer = MF_WRITER;


private:
public:
   MF()
   {
       memset(this, 0, sizeof(MF));
       mPacketSize = static_cast<PacketSize>(sizeof(MF));
   }
   MF(const MF&) = delete;
   MF(MF &&) = delete;
   MF& operator = (const MF&) = delete;
   MF& operator = (MF &&) = delete;


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(MF) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(MF) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(MF); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(MF))
           {
               size += sizeof(MF);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, MF>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class MF_ACK_MC_BYPASS;

class MF_ACK_MC_BYPASS_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::MF_ACK_MC_BYPASS;

public:
   // (4)
   explicit MF_ACK_MC_BYPASS_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacket& rp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::MF_ACK_MC_BYPASS, buf)
   {
       SetReadPacket(rp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (5)
   explicit MF_ACK_MC_BYPASS_WRITER(PacketTraitAck trait, uint8_t* buf, const NetworkPacketWriter& wp, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::MF_ACK_MC_BYPASS, buf)
   {
       SetWritePacket(wp);
       GetHeader().SetPacketResult(packetResult);
   }

   // (6)
   explicit MF_ACK_MC_BYPASS_WRITER(PacketTraitAck trait, uint8_t* buf, const PacketHeader& header, Result packetResult)
       :
       NetworkPacketWriter(trait, PacketTypes::MF_ACK_MC_BYPASS, buf)
   {
       SetHeader(header);
       GetHeader().SetPacketResult(packetResult);
   }

   // (8)
   explicit MF_ACK_MC_BYPASS_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       const uint8_t* nestedPacket,
       PacketSize nestedPacketSize
   )
   {
       PacketSize& nestedPacketOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(nestedPacketSize);


       nestedPacketOffset = GetPacketSize();
       WriteBinary(nestedPacket, nestedPacketSize);

   }

   MF_ACK_MC_BYPASS& GetPacket() const noexcept { return *reinterpret_cast<MF_ACK_MC_BYPASS*>(GetPacketBufPtr()); }
   MF_ACK_MC_BYPASS* GetPacketPtr() const noexcept { return reinterpret_cast<MF_ACK_MC_BYPASS*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class MF_ACK_MC_BYPASS : public NetworkPacket
{
   public:
      using Writer = MF_ACK_MC_BYPASS_WRITER;


private:
   PacketSize m_nestedPacket_offset = 0;
   PacketSize m_nestedPacket_size = 0;

public:
   MF_ACK_MC_BYPASS()
   {
       memset(this, 0, sizeof(MF_ACK_MC_BYPASS));
       mPacketSize = static_cast<PacketSize>(sizeof(MF_ACK_MC_BYPASS));
   }
   MF_ACK_MC_BYPASS(const MF_ACK_MC_BYPASS&) = delete;
   MF_ACK_MC_BYPASS(MF_ACK_MC_BYPASS &&) = delete;
   MF_ACK_MC_BYPASS& operator = (const MF_ACK_MC_BYPASS&) = delete;
   MF_ACK_MC_BYPASS& operator = (MF_ACK_MC_BYPASS &&) = delete;

   const uint8_t* Get_nestedPacket() const noexcept { return ((uint8_t*)this + m_nestedPacket_offset); }
   PacketSize Get_nestedPacket_size() const noexcept { return m_nestedPacket_size; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(MF_ACK_MC_BYPASS) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(MF_ACK_MC_BYPASS) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(MF_ACK_MC_BYPASS); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(MF_ACK_MC_BYPASS))
           {
               size += sizeof(MF_ACK_MC_BYPASS);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           if (GetPacketSize() < m_nestedPacket_offset)
               return false;

           thisSize += m_nestedPacket_size;
           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, MF_ACK_MC_BYPASS>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}nestedPacket: BIN[{}]", tTabStr, t->Get_nestedPacket_size());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class MF_ROOM_USER_ENTER;

class MF_ROOM_USER_ENTER_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::MF_ROOM_USER_ENTER;

public:
   // (7)
   explicit MF_ROOM_USER_ENTER_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::MF_ROOM_USER_ENTER, buf)
   {
   }

   // (9)
   explicit MF_ROOM_USER_ENTER_WRITER(
       PacketTraitParam trait, uint8_t* buf,
       RoomId roomId,
       RoomType roomType,
       const USER& enterUser
   )
       :
       NetworkPacketWriter(trait, PacketTypes::MF_ROOM_USER_ENTER, buf)
   {
       WriteValue(roomId);

       WriteValue(roomType);

       PacketSize& enterUserOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       enterUserOffset = GetPacketSize();
       WriteBinary((uint8_t*)&enterUser, enterUser.GetPacketSize());

   }

   // (9)
   explicit MF_ROOM_USER_ENTER_WRITER(
       PacketTraitParam trait, uint8_t* buf,
       RoomId roomId,
       RoomType roomType,
       const USER::Writer& enterUser
   )
       :
       NetworkPacketWriter(trait, PacketTypes::MF_ROOM_USER_ENTER, buf)
   {
       WriteValue(roomId);

       WriteValue(roomType);

       PacketSize& enterUserOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       enterUserOffset = GetPacketSize();
       WriteBinary(enterUser.GetPacketBufPtr(), enterUser.GetPacketSize());

   }

   // (8)
   explicit MF_ROOM_USER_ENTER_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       RoomId roomId,
       RoomType roomType,
       const USER& enterUser
   )
   {
       WriteValue(roomId);

       WriteValue(roomType);

       PacketSize& enterUserOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       enterUserOffset = GetPacketSize();
       WriteBinary((uint8_t*)&enterUser, enterUser.GetPacketSize());

   }

   void SetValues(
       RoomId roomId,
       RoomType roomType,
       const USER::Writer& enterUser
   )
   {
       WriteValue(roomId);

       WriteValue(roomType);

       PacketSize& enterUserOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       enterUserOffset = GetPacketSize();
       WriteBinary(enterUser.GetPacketBufPtr(), enterUser.GetPacketSize());

   }

   MF_ROOM_USER_ENTER& GetPacket() const noexcept { return *reinterpret_cast<MF_ROOM_USER_ENTER*>(GetPacketBufPtr()); }
   MF_ROOM_USER_ENTER* GetPacketPtr() const noexcept { return reinterpret_cast<MF_ROOM_USER_ENTER*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class MF_ROOM_USER_ENTER : public NetworkPacket
{
   public:
      using Writer = MF_ROOM_USER_ENTER_WRITER;


private:
   RoomId m_roomId;

   RoomType m_roomType;

   PacketSize m_enterUser_offset = 0;

public:
   MF_ROOM_USER_ENTER()
   {
       memset(this, 0, sizeof(MF_ROOM_USER_ENTER));
       mPacketSize = static_cast<PacketSize>(sizeof(MF_ROOM_USER_ENTER));
   }
   MF_ROOM_USER_ENTER(const MF_ROOM_USER_ENTER&) = delete;
   MF_ROOM_USER_ENTER(MF_ROOM_USER_ENTER &&) = delete;
   MF_ROOM_USER_ENTER& operator = (const MF_ROOM_USER_ENTER&) = delete;
   MF_ROOM_USER_ENTER& operator = (MF_ROOM_USER_ENTER &&) = delete;

   RoomId Get_roomId() const noexcept { return m_roomId; }
   RoomId& Ref_roomId() noexcept { return m_roomId; }
   const RoomId& ConstRef_roomId() const noexcept { return m_roomId; }

   RoomType Get_roomType() const noexcept { return m_roomType; }
   RoomType& Ref_roomType() noexcept { return m_roomType; }
   const RoomType& ConstRef_roomType() const noexcept { return m_roomType; }

   const USER& Get_enterUser() const noexcept { return *(USER*)((uint8_t*)this + m_enterUser_offset); }
   USER* Get_enterUser_ptr() const noexcept { return (USER*)((uint8_t*)this + m_enterUser_offset); }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(MF_ROOM_USER_ENTER) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(MF_ROOM_USER_ENTER) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(MF_ROOM_USER_ENTER); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(MF_ROOM_USER_ENTER))
           {
               size += sizeof(MF_ROOM_USER_ENTER);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(RoomId);
       }

       {
           thisSize += sizeof(RoomType);
       }

       {
           if (GetPacketSize() < m_enterUser_offset)
               return false;

           const USER* _packet = reinterpret_cast<const USER*>(GetPacketBufPtr() + m_enterUser_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, MF_ROOM_USER_ENTER>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}roomId: {}", tTabStr, t->Get_roomId());
       result += std::format(L"\n{}roomType: {}", tTabStr, t->Get_roomType());
       result += std::format(L"\n{}enterUser: {}", tTabStr, t->Get_enterUser_ptr());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class MF_ROOM_USER_LEAVE;

class MF_ROOM_USER_LEAVE_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::MF_ROOM_USER_LEAVE;

public:
   // (7)
   explicit MF_ROOM_USER_LEAVE_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::MF_ROOM_USER_LEAVE, buf)
   {
   }

   // (9)
   explicit MF_ROOM_USER_LEAVE_WRITER(
       PacketTraitParam trait, uint8_t* buf,
       RoomId roomId,
       UserId leaveUserID
   )
       :
       NetworkPacketWriter(trait, PacketTypes::MF_ROOM_USER_LEAVE, buf)
   {
       WriteValue(roomId);

       WriteValue(leaveUserID);


   }

   // (8)
   explicit MF_ROOM_USER_LEAVE_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       RoomId roomId,
       UserId leaveUserID
   )
   {
       WriteValue(roomId);

       WriteValue(leaveUserID);


   }

   MF_ROOM_USER_LEAVE& GetPacket() const noexcept { return *reinterpret_cast<MF_ROOM_USER_LEAVE*>(GetPacketBufPtr()); }
   MF_ROOM_USER_LEAVE* GetPacketPtr() const noexcept { return reinterpret_cast<MF_ROOM_USER_LEAVE*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class MF_ROOM_USER_LEAVE : public NetworkPacket
{
   public:
      using Writer = MF_ROOM_USER_LEAVE_WRITER;


private:
   RoomId m_roomId;

   UserId m_leaveUserID;

public:
   MF_ROOM_USER_LEAVE()
   {
       memset(this, 0, sizeof(MF_ROOM_USER_LEAVE));
       mPacketSize = static_cast<PacketSize>(sizeof(MF_ROOM_USER_LEAVE));
   }
   MF_ROOM_USER_LEAVE(const MF_ROOM_USER_LEAVE&) = delete;
   MF_ROOM_USER_LEAVE(MF_ROOM_USER_LEAVE &&) = delete;
   MF_ROOM_USER_LEAVE& operator = (const MF_ROOM_USER_LEAVE&) = delete;
   MF_ROOM_USER_LEAVE& operator = (MF_ROOM_USER_LEAVE &&) = delete;

   RoomId Get_roomId() const noexcept { return m_roomId; }
   RoomId& Ref_roomId() noexcept { return m_roomId; }
   const RoomId& ConstRef_roomId() const noexcept { return m_roomId; }

   UserId Get_leaveUserID() const noexcept { return m_leaveUserID; }
   UserId& Ref_leaveUserID() noexcept { return m_leaveUserID; }
   const UserId& ConstRef_leaveUserID() const noexcept { return m_leaveUserID; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(MF_ROOM_USER_LEAVE) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(MF_ROOM_USER_LEAVE) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(MF_ROOM_USER_LEAVE); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(MF_ROOM_USER_LEAVE))
           {
               size += sizeof(MF_ROOM_USER_LEAVE);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(RoomId);
       }

       {
           thisSize += sizeof(UserId);
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, MF_ROOM_USER_LEAVE>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}roomId: {}", tTabStr, t->Get_roomId());
       result += std::format(L"\n{}leaveUserID: {}", tTabStr, t->Get_leaveUserID());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class MF_CHAT;

class MF_CHAT_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::MF_CHAT;

public:
   // (7)
   explicit MF_CHAT_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::MF_CHAT, buf)
   {
   }

   // (9)
   explicit MF_CHAT_WRITER(
       PacketTraitParam trait, uint8_t* buf,
       ChatType chatType,
       RoomId roomId,
       const wchar_t* userName,
       const wchar_t* guildName,
       const wchar_t* msg
   )
       :
       NetworkPacketWriter(trait, PacketTypes::MF_CHAT, buf)
   {
       WriteValue(chatType);

       WriteValue(roomId);

       PacketSize& userNameOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 
       PacketSize& userNameLength = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 

       PacketSize& guildNameOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 
       PacketSize& guildNameLength = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 

       PacketSize& msgOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 
       PacketSize& msgLength = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 


       userNameOffset = GetPacketSize();
       userNameLength = (PacketSize)wcsnlen_s(userName, MAX_STRING_LENGTH);
       if (MAX_STRING_LENGTH == userNameLength) WriteString(L"", 0);
       else WriteString(userName, userNameLength); 

       guildNameOffset = GetPacketSize();
       guildNameLength = (PacketSize)wcsnlen_s(guildName, MAX_STRING_LENGTH);
       if (MAX_STRING_LENGTH == guildNameLength) WriteString(L"", 0);
       else WriteString(guildName, guildNameLength); 

       msgOffset = GetPacketSize();
       msgLength = (PacketSize)wcsnlen_s(msg, MAX_STRING_LENGTH);
       if (MAX_STRING_LENGTH == msgLength) WriteString(L"", 0);
       else WriteString(msg, msgLength); 

   }

   // (8)
   explicit MF_CHAT_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       ChatType chatType,
       RoomId roomId,
       const wchar_t* userName,
       const wchar_t* guildName,
       const wchar_t* msg
   )
   {
       WriteValue(chatType);

       WriteValue(roomId);

       PacketSize& userNameOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 
       PacketSize& userNameLength = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 

       PacketSize& guildNameOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 
       PacketSize& guildNameLength = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 

       PacketSize& msgOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 
       PacketSize& msgLength = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 


       userNameOffset = GetPacketSize();
       userNameLength = (PacketSize)wcsnlen_s(userName, MAX_STRING_LENGTH);
       if (MAX_STRING_LENGTH == userNameLength) WriteString(L"", 0);
       else WriteString(userName, userNameLength); 

       guildNameOffset = GetPacketSize();
       guildNameLength = (PacketSize)wcsnlen_s(guildName, MAX_STRING_LENGTH);
       if (MAX_STRING_LENGTH == guildNameLength) WriteString(L"", 0);
       else WriteString(guildName, guildNameLength); 

       msgOffset = GetPacketSize();
       msgLength = (PacketSize)wcsnlen_s(msg, MAX_STRING_LENGTH);
       if (MAX_STRING_LENGTH == msgLength) WriteString(L"", 0);
       else WriteString(msg, msgLength); 

   }

   MF_CHAT& GetPacket() const noexcept { return *reinterpret_cast<MF_CHAT*>(GetPacketBufPtr()); }
   MF_CHAT* GetPacketPtr() const noexcept { return reinterpret_cast<MF_CHAT*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class MF_CHAT : public NetworkPacket
{
   public:
      using Writer = MF_CHAT_WRITER;


private:
   ChatType m_chatType;

   RoomId m_roomId;

   PacketSize m_userName_offset = 0;
   PacketSize m_userName_length = 0;

   PacketSize m_guildName_offset = 0;
   PacketSize m_guildName_length = 0;

   PacketSize m_msg_offset = 0;
   PacketSize m_msg_length = 0;

public:
   MF_CHAT()
   {
       memset(this, 0, sizeof(MF_CHAT));
       mPacketSize = static_cast<PacketSize>(sizeof(MF_CHAT));
   }
   MF_CHAT(const MF_CHAT&) = delete;
   MF_CHAT(MF_CHAT &&) = delete;
   MF_CHAT& operator = (const MF_CHAT&) = delete;
   MF_CHAT& operator = (MF_CHAT &&) = delete;

   ChatType Get_chatType() const noexcept { return m_chatType; }
   ChatType& Ref_chatType() noexcept { return m_chatType; }
   const ChatType& ConstRef_chatType() const noexcept { return m_chatType; }

   RoomId Get_roomId() const noexcept { return m_roomId; }
   RoomId& Ref_roomId() noexcept { return m_roomId; }
   const RoomId& ConstRef_roomId() const noexcept { return m_roomId; }

   const wchar_t* Get_userName() const
   {
       if (0 != *((const wchar_t*)((uint8_t*)this + m_userName_offset) + m_userName_length))
           return L"";

       return (const wchar_t*)((uint8_t*)this + m_userName_offset);
   }

   wchar_t* Ref_userName()
   {
       if (0 != *((wchar_t*)((uint8_t*)this + m_userName_offset) + m_userName_length))
           return nullptr;

       return (wchar_t*)((uint8_t*)this + m_userName_offset);
   }

   const wchar_t* Get_guildName() const
   {
       if (0 != *((const wchar_t*)((uint8_t*)this + m_guildName_offset) + m_guildName_length))
           return L"";

       return (const wchar_t*)((uint8_t*)this + m_guildName_offset);
   }

   wchar_t* Ref_guildName()
   {
       if (0 != *((wchar_t*)((uint8_t*)this + m_guildName_offset) + m_guildName_length))
           return nullptr;

       return (wchar_t*)((uint8_t*)this + m_guildName_offset);
   }

   const wchar_t* Get_msg() const
   {
       if (0 != *((const wchar_t*)((uint8_t*)this + m_msg_offset) + m_msg_length))
           return L"";

       return (const wchar_t*)((uint8_t*)this + m_msg_offset);
   }

   wchar_t* Ref_msg()
   {
       if (0 != *((wchar_t*)((uint8_t*)this + m_msg_offset) + m_msg_length))
           return nullptr;

       return (wchar_t*)((uint8_t*)this + m_msg_offset);
   }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(MF_CHAT) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(MF_CHAT) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(MF_CHAT); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(MF_CHAT))
           {
               size += sizeof(MF_CHAT);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(ChatType);
       }

       {
           thisSize += sizeof(RoomId);
       }

       {
           if (GetPacketSize() < m_userName_offset)
               return false;

           if (0 < m_userName_offset)
               thisSize += sizeof(wchar_t) * (size_t(m_userName_length) + 1);

           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       {
           if (GetPacketSize() < m_guildName_offset)
               return false;

           if (0 < m_guildName_offset)
               thisSize += sizeof(wchar_t) * (size_t(m_guildName_length) + 1);

           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       {
           if (GetPacketSize() < m_msg_offset)
               return false;

           if (0 < m_msg_offset)
               thisSize += sizeof(wchar_t) * (size_t(m_msg_length) + 1);

           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, MF_CHAT>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}chatType: {}", tTabStr, t->Get_chatType());
       result += std::format(L"\n{}roomId: {}", tTabStr, t->Get_roomId());
       result += std::format(L"\n{}userName: {}", tTabStr, t->Get_userName());
       result += std::format(L"\n{}guildName: {}", tTabStr, t->Get_guildName());
       result += std::format(L"\n{}msg: {}", tTabStr, t->Get_msg());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

#pragma pack(pop)

inline bool ValidatePacketMF(const Packet& rp)
{
   static constexpr bool(*ValidatePacketFuncArray[PacketTypes::MF_PACKET_END - PacketTypes::MF_PACKET_START - 1])(const Packet&) =
   {
       &ValidatePacketFunc<MF>,
       &ValidatePacketFunc<MF_ACK_MC_BYPASS>,
       &ValidatePacketFunc<MF_ROOM_USER_ENTER>,
       &ValidatePacketFunc<MF_ROOM_USER_LEAVE>,
       &ValidatePacketFunc<MF_CHAT>
   };

   if ((PacketTypes::MF_PACKET_START >= rp.GetPacketType()) ||
       (PacketTypes::MF_PACKET_END <= rp.GetPacketType()))
   {
       return true;
   }

   return ValidatePacketFuncArray[rp.GetPacketType() - PacketTypes::MF_PACKET_START - 1](rp);
}

template <typename _Owner, typename... _Args>
HandleResult DispatchPacketMF(uint64_t socket, _Owner* owner, NetworkPacket& rp, _Args&&... args)
{
   HandleResult handleResult = DispatchPacketCOMMON(socket, owner, rp, std::forward<_Args>(args)...);
   if (handleResult != HandleResult::NOT_EXISTS)
       return handleResult;
   
   static constexpr HandleResult(*DispatchPacketFuncArray[PacketTypes::MF_PACKET_END - PacketTypes::MF_PACKET_START - 1])(uint64_t, _Owner*, NetworkPacket&, _Args&&...) =
   {
       &DispatchPacketFunc<_Owner, MF, _Args&&...>,
       &DispatchPacketFunc<_Owner, MF_ACK_MC_BYPASS, _Args&&...>,
       &DispatchPacketFunc<_Owner, MF_ROOM_USER_ENTER, _Args&&...>,
       &DispatchPacketFunc<_Owner, MF_ROOM_USER_LEAVE, _Args&&...>,
       &DispatchPacketFunc<_Owner, MF_CHAT, _Args&&...>
   };

   if ((PacketTypes::MF_PACKET_START >= rp.GetPacketType()) ||
       (PacketTypes::MF_PACKET_END <= rp.GetPacketType()))
   {
       return HandleResult::NOT_EXISTS;
   }

   if (auto func = DispatchPacketFuncArray[rp.GetPacketType() - PacketTypes::MF_PACKET_START - 1])
       return func(socket, owner, rp, std::forward<_Args>(args)...);
   else
       return HandleResult::NOT_EXISTS;
}

