// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"
#include "Packet/NetworkPacket/NetworkPacket.h"
#include "Packet/NetworkPacket/NetworkPacketWriter.h"
#include "Packet/BasePacket/PacketWriter.h"
#include "Packet/PacketDataList/PacketDataList.h"
#include "Packet/PacketFuncs/PacketValidator.h"
#include "Packet/PacketFuncs/PacketDispatcher.h"

#pragma pack(push, 1)

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class CM_SHELL_COMMAND;

class CM_SHELL_COMMAND_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::CM_SHELL_COMMAND;

public:
   // (7)
   explicit CM_SHELL_COMMAND_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_SHELL_COMMAND, buf)
   {
   }

   // (9)
   explicit CM_SHELL_COMMAND_WRITER(
       PacketTraitParam trait, uint8_t* buf,
       const wchar_t* command
   )
       :
       NetworkPacketWriter(trait, PacketTypes::CM_SHELL_COMMAND, buf)
   {
       PacketSize& commandOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 
       PacketSize& commandLength = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 


       commandOffset = GetPacketSize();
       commandLength = (PacketSize)wcsnlen_s(command, MAX_STRING_LENGTH);
       if (MAX_STRING_LENGTH == commandLength) WriteString(L"", 0);
       else WriteString(command, commandLength); 

   }

   // (8)
   explicit CM_SHELL_COMMAND_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       const wchar_t* command
   )
   {
       PacketSize& commandOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 
       PacketSize& commandLength = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 


       commandOffset = GetPacketSize();
       commandLength = (PacketSize)wcsnlen_s(command, MAX_STRING_LENGTH);
       if (MAX_STRING_LENGTH == commandLength) WriteString(L"", 0);
       else WriteString(command, commandLength); 

   }

   CM_SHELL_COMMAND& GetPacket() const noexcept { return *reinterpret_cast<CM_SHELL_COMMAND*>(GetPacketBufPtr()); }
   CM_SHELL_COMMAND* GetPacketPtr() const noexcept { return reinterpret_cast<CM_SHELL_COMMAND*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class CM_SHELL_COMMAND : public NetworkPacket
{
   public:
      using Writer = CM_SHELL_COMMAND_WRITER;


private:
   PacketSize m_command_offset = 0; // Shell 명령
   PacketSize m_command_length = 0;

public:
   CM_SHELL_COMMAND()
   {
       memset(this, 0, sizeof(CM_SHELL_COMMAND));
       mPacketSize = static_cast<PacketSize>(sizeof(CM_SHELL_COMMAND));
   }
   CM_SHELL_COMMAND(const CM_SHELL_COMMAND&) = delete;
   CM_SHELL_COMMAND(CM_SHELL_COMMAND &&) = delete;
   CM_SHELL_COMMAND& operator = (const CM_SHELL_COMMAND&) = delete;
   CM_SHELL_COMMAND& operator = (CM_SHELL_COMMAND &&) = delete;

   const wchar_t* Get_command() const
   {
       if (0 != *((const wchar_t*)((uint8_t*)this + m_command_offset) + m_command_length))
           return L"";

       return (const wchar_t*)((uint8_t*)this + m_command_offset);
   }

   wchar_t* Ref_command()
   {
       if (0 != *((wchar_t*)((uint8_t*)this + m_command_offset) + m_command_length))
           return nullptr;

       return (wchar_t*)((uint8_t*)this + m_command_offset);
   }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(CM_SHELL_COMMAND) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(CM_SHELL_COMMAND) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(CM_SHELL_COMMAND); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(CM_SHELL_COMMAND))
           {
               size += sizeof(CM_SHELL_COMMAND);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           if (GetPacketSize() < m_command_offset)
               return false;

           if (0 < m_command_offset)
               thisSize += sizeof(wchar_t) * (size_t(m_command_length) + 1);

           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, CM_SHELL_COMMAND>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}command: {}", tTabStr, t->Get_command());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class CM_REQ_SERVER_LIST;

class CM_REQ_SERVER_LIST_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::CM_REQ_SERVER_LIST;

public:
   // (1)
   explicit CM_REQ_SERVER_LIST_WRITER(PacketTraitReq trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_SERVER_LIST, buf)
   {

   }

   // (2)
   explicit CM_REQ_SERVER_LIST_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacket& rp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_SERVER_LIST, buf)
   {
       SetReadPacket(rp);

   }

   // (3)
   explicit CM_REQ_SERVER_LIST_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacketWriter& wp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_SERVER_LIST, buf)
   {
       SetWritePacket(wp);

   }

   // (8)
   explicit CM_REQ_SERVER_LIST_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   CM_REQ_SERVER_LIST& GetPacket() const noexcept { return *reinterpret_cast<CM_REQ_SERVER_LIST*>(GetPacketBufPtr()); }
   CM_REQ_SERVER_LIST* GetPacketPtr() const noexcept { return reinterpret_cast<CM_REQ_SERVER_LIST*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class CM_REQ_SERVER_LIST : public NetworkPacket
{
   public:
      using Writer = CM_REQ_SERVER_LIST_WRITER;


private:
public:
   CM_REQ_SERVER_LIST()
   {
       memset(this, 0, sizeof(CM_REQ_SERVER_LIST));
       mPacketSize = static_cast<PacketSize>(sizeof(CM_REQ_SERVER_LIST));
   }
   CM_REQ_SERVER_LIST(const CM_REQ_SERVER_LIST&) = delete;
   CM_REQ_SERVER_LIST(CM_REQ_SERVER_LIST &&) = delete;
   CM_REQ_SERVER_LIST& operator = (const CM_REQ_SERVER_LIST&) = delete;
   CM_REQ_SERVER_LIST& operator = (CM_REQ_SERVER_LIST &&) = delete;


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(CM_REQ_SERVER_LIST) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(CM_REQ_SERVER_LIST) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(CM_REQ_SERVER_LIST); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(CM_REQ_SERVER_LIST))
           {
               size += sizeof(CM_REQ_SERVER_LIST);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, CM_REQ_SERVER_LIST>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class CM_REQ_ACCOUNT_USER_LIST;

class CM_REQ_ACCOUNT_USER_LIST_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::CM_REQ_ACCOUNT_USER_LIST;

public:
   // (1)
   explicit CM_REQ_ACCOUNT_USER_LIST_WRITER(PacketTraitReq trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_ACCOUNT_USER_LIST, buf)
   {
   }

   // (2)
   explicit CM_REQ_ACCOUNT_USER_LIST_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacket& rp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_ACCOUNT_USER_LIST, buf)
   {
       SetReadPacket(rp);
   }

   // (3)
   explicit CM_REQ_ACCOUNT_USER_LIST_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacketWriter& wp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_ACCOUNT_USER_LIST, buf)
   {
       SetWritePacket(wp);
   }

   // (8)
   explicit CM_REQ_ACCOUNT_USER_LIST_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       const ACCOUNT& account
   )
   {
       PacketSize& accountOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       accountOffset = GetPacketSize();
       WriteBinary((uint8_t*)&account, account.GetPacketSize());

   }

   void SetValues(
       const ACCOUNT::Writer& account
   )
   {
       PacketSize& accountOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       accountOffset = GetPacketSize();
       WriteBinary(account.GetPacketBufPtr(), account.GetPacketSize());

   }

   CM_REQ_ACCOUNT_USER_LIST& GetPacket() const noexcept { return *reinterpret_cast<CM_REQ_ACCOUNT_USER_LIST*>(GetPacketBufPtr()); }
   CM_REQ_ACCOUNT_USER_LIST* GetPacketPtr() const noexcept { return reinterpret_cast<CM_REQ_ACCOUNT_USER_LIST*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class CM_REQ_ACCOUNT_USER_LIST : public NetworkPacket
{
   public:
      using Writer = CM_REQ_ACCOUNT_USER_LIST_WRITER;


private:
   PacketSize m_account_offset = 0;

public:
   CM_REQ_ACCOUNT_USER_LIST()
   {
       memset(this, 0, sizeof(CM_REQ_ACCOUNT_USER_LIST));
       mPacketSize = static_cast<PacketSize>(sizeof(CM_REQ_ACCOUNT_USER_LIST));
   }
   CM_REQ_ACCOUNT_USER_LIST(const CM_REQ_ACCOUNT_USER_LIST&) = delete;
   CM_REQ_ACCOUNT_USER_LIST(CM_REQ_ACCOUNT_USER_LIST &&) = delete;
   CM_REQ_ACCOUNT_USER_LIST& operator = (const CM_REQ_ACCOUNT_USER_LIST&) = delete;
   CM_REQ_ACCOUNT_USER_LIST& operator = (CM_REQ_ACCOUNT_USER_LIST &&) = delete;

   const ACCOUNT& Get_account() const noexcept { return *(ACCOUNT*)((uint8_t*)this + m_account_offset); }
   ACCOUNT* Get_account_ptr() const noexcept { return (ACCOUNT*)((uint8_t*)this + m_account_offset); }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(CM_REQ_ACCOUNT_USER_LIST) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(CM_REQ_ACCOUNT_USER_LIST) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(CM_REQ_ACCOUNT_USER_LIST); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(CM_REQ_ACCOUNT_USER_LIST))
           {
               size += sizeof(CM_REQ_ACCOUNT_USER_LIST);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           if (GetPacketSize() < m_account_offset)
               return false;

           const ACCOUNT* _packet = reinterpret_cast<const ACCOUNT*>(GetPacketBufPtr() + m_account_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, CM_REQ_ACCOUNT_USER_LIST>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}account: {}", tTabStr, t->Get_account_ptr());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class CM_REQ_ACCOUNT_USER_CREATE;

class CM_REQ_ACCOUNT_USER_CREATE_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::CM_REQ_ACCOUNT_USER_CREATE;

public:
   // (1)
   explicit CM_REQ_ACCOUNT_USER_CREATE_WRITER(PacketTraitReq trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_ACCOUNT_USER_CREATE, buf)
   {
   }

   // (2)
   explicit CM_REQ_ACCOUNT_USER_CREATE_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacket& rp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_ACCOUNT_USER_CREATE, buf)
   {
       SetReadPacket(rp);
   }

   // (3)
   explicit CM_REQ_ACCOUNT_USER_CREATE_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacketWriter& wp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_ACCOUNT_USER_CREATE, buf)
   {
       SetWritePacket(wp);
   }

   // (8)
   explicit CM_REQ_ACCOUNT_USER_CREATE_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       const ACCOUNT& account,
       const wchar_t* userName
   )
   {
       PacketSize& accountOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       PacketSize& userNameOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 
       PacketSize& userNameLength = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 


       accountOffset = GetPacketSize();
       WriteBinary((uint8_t*)&account, account.GetPacketSize());

       userNameOffset = GetPacketSize();
       userNameLength = (PacketSize)wcsnlen_s(userName, MAX_STRING_LENGTH);
       if (MAX_STRING_LENGTH == userNameLength) WriteString(L"", 0);
       else WriteString(userName, userNameLength); 

   }

   void SetValues(
       const ACCOUNT::Writer& account,
       const wchar_t* userName
   )
   {
       PacketSize& accountOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       PacketSize& userNameOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 
       PacketSize& userNameLength = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0)); 


       accountOffset = GetPacketSize();
       WriteBinary(account.GetPacketBufPtr(), account.GetPacketSize());

       userNameOffset = GetPacketSize();
       userNameLength = (PacketSize)wcsnlen_s(userName, MAX_STRING_LENGTH);
       if (MAX_STRING_LENGTH == userNameLength) WriteString(L"", 0);
       else WriteString(userName, userNameLength); 

   }

   CM_REQ_ACCOUNT_USER_CREATE& GetPacket() const noexcept { return *reinterpret_cast<CM_REQ_ACCOUNT_USER_CREATE*>(GetPacketBufPtr()); }
   CM_REQ_ACCOUNT_USER_CREATE* GetPacketPtr() const noexcept { return reinterpret_cast<CM_REQ_ACCOUNT_USER_CREATE*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class CM_REQ_ACCOUNT_USER_CREATE : public NetworkPacket
{
   public:
      using Writer = CM_REQ_ACCOUNT_USER_CREATE_WRITER;


private:
   PacketSize m_account_offset = 0;

   PacketSize m_userName_offset = 0;
   PacketSize m_userName_length = 0;

public:
   CM_REQ_ACCOUNT_USER_CREATE()
   {
       memset(this, 0, sizeof(CM_REQ_ACCOUNT_USER_CREATE));
       mPacketSize = static_cast<PacketSize>(sizeof(CM_REQ_ACCOUNT_USER_CREATE));
   }
   CM_REQ_ACCOUNT_USER_CREATE(const CM_REQ_ACCOUNT_USER_CREATE&) = delete;
   CM_REQ_ACCOUNT_USER_CREATE(CM_REQ_ACCOUNT_USER_CREATE &&) = delete;
   CM_REQ_ACCOUNT_USER_CREATE& operator = (const CM_REQ_ACCOUNT_USER_CREATE&) = delete;
   CM_REQ_ACCOUNT_USER_CREATE& operator = (CM_REQ_ACCOUNT_USER_CREATE &&) = delete;

   const ACCOUNT& Get_account() const noexcept { return *(ACCOUNT*)((uint8_t*)this + m_account_offset); }
   ACCOUNT* Get_account_ptr() const noexcept { return (ACCOUNT*)((uint8_t*)this + m_account_offset); }

   const wchar_t* Get_userName() const
   {
       if (0 != *((const wchar_t*)((uint8_t*)this + m_userName_offset) + m_userName_length))
           return L"";

       return (const wchar_t*)((uint8_t*)this + m_userName_offset);
   }

   wchar_t* Ref_userName()
   {
       if (0 != *((wchar_t*)((uint8_t*)this + m_userName_offset) + m_userName_length))
           return nullptr;

       return (wchar_t*)((uint8_t*)this + m_userName_offset);
   }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(CM_REQ_ACCOUNT_USER_CREATE) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(CM_REQ_ACCOUNT_USER_CREATE) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(CM_REQ_ACCOUNT_USER_CREATE); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(CM_REQ_ACCOUNT_USER_CREATE))
           {
               size += sizeof(CM_REQ_ACCOUNT_USER_CREATE);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           if (GetPacketSize() < m_account_offset)
               return false;

           const ACCOUNT* _packet = reinterpret_cast<const ACCOUNT*>(GetPacketBufPtr() + m_account_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       {
           if (GetPacketSize() < m_userName_offset)
               return false;

           if (0 < m_userName_offset)
               thisSize += sizeof(wchar_t) * (size_t(m_userName_length) + 1);

           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, CM_REQ_ACCOUNT_USER_CREATE>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}account: {}", tTabStr, t->Get_account_ptr());
       result += std::format(L"\n{}userName: {}", tTabStr, t->Get_userName());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class CM_REQ_ACCOUNT_USER_DELETE;

class CM_REQ_ACCOUNT_USER_DELETE_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::CM_REQ_ACCOUNT_USER_DELETE;

public:
   // (1)
   explicit CM_REQ_ACCOUNT_USER_DELETE_WRITER(PacketTraitReq trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_ACCOUNT_USER_DELETE, buf)
   {
   }

   // (2)
   explicit CM_REQ_ACCOUNT_USER_DELETE_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacket& rp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_ACCOUNT_USER_DELETE, buf)
   {
       SetReadPacket(rp);
   }

   // (3)
   explicit CM_REQ_ACCOUNT_USER_DELETE_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacketWriter& wp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_ACCOUNT_USER_DELETE, buf)
   {
       SetWritePacket(wp);
   }

   // (8)
   explicit CM_REQ_ACCOUNT_USER_DELETE_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       const ACCOUNT& account
   )
   {
       PacketSize& accountOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       accountOffset = GetPacketSize();
       WriteBinary((uint8_t*)&account, account.GetPacketSize());

   }

   void SetValues(
       const ACCOUNT::Writer& account
   )
   {
       PacketSize& accountOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       accountOffset = GetPacketSize();
       WriteBinary(account.GetPacketBufPtr(), account.GetPacketSize());

   }

   CM_REQ_ACCOUNT_USER_DELETE& GetPacket() const noexcept { return *reinterpret_cast<CM_REQ_ACCOUNT_USER_DELETE*>(GetPacketBufPtr()); }
   CM_REQ_ACCOUNT_USER_DELETE* GetPacketPtr() const noexcept { return reinterpret_cast<CM_REQ_ACCOUNT_USER_DELETE*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class CM_REQ_ACCOUNT_USER_DELETE : public NetworkPacket
{
   public:
      using Writer = CM_REQ_ACCOUNT_USER_DELETE_WRITER;


private:
   PacketSize m_account_offset = 0;

public:
   CM_REQ_ACCOUNT_USER_DELETE()
   {
       memset(this, 0, sizeof(CM_REQ_ACCOUNT_USER_DELETE));
       mPacketSize = static_cast<PacketSize>(sizeof(CM_REQ_ACCOUNT_USER_DELETE));
   }
   CM_REQ_ACCOUNT_USER_DELETE(const CM_REQ_ACCOUNT_USER_DELETE&) = delete;
   CM_REQ_ACCOUNT_USER_DELETE(CM_REQ_ACCOUNT_USER_DELETE &&) = delete;
   CM_REQ_ACCOUNT_USER_DELETE& operator = (const CM_REQ_ACCOUNT_USER_DELETE&) = delete;
   CM_REQ_ACCOUNT_USER_DELETE& operator = (CM_REQ_ACCOUNT_USER_DELETE &&) = delete;

   const ACCOUNT& Get_account() const noexcept { return *(ACCOUNT*)((uint8_t*)this + m_account_offset); }
   ACCOUNT* Get_account_ptr() const noexcept { return (ACCOUNT*)((uint8_t*)this + m_account_offset); }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(CM_REQ_ACCOUNT_USER_DELETE) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(CM_REQ_ACCOUNT_USER_DELETE) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(CM_REQ_ACCOUNT_USER_DELETE); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(CM_REQ_ACCOUNT_USER_DELETE))
           {
               size += sizeof(CM_REQ_ACCOUNT_USER_DELETE);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           if (GetPacketSize() < m_account_offset)
               return false;

           const ACCOUNT* _packet = reinterpret_cast<const ACCOUNT*>(GetPacketBufPtr() + m_account_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, CM_REQ_ACCOUNT_USER_DELETE>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}account: {}", tTabStr, t->Get_account_ptr());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class CM_REQ_AUTH_TICKET;

class CM_REQ_AUTH_TICKET_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::CM_REQ_AUTH_TICKET;

public:
   // (1)
   explicit CM_REQ_AUTH_TICKET_WRITER(PacketTraitReq trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_AUTH_TICKET, buf)
   {
   }

   // (2)
   explicit CM_REQ_AUTH_TICKET_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacket& rp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_AUTH_TICKET, buf)
   {
       SetReadPacket(rp);
   }

   // (3)
   explicit CM_REQ_AUTH_TICKET_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacketWriter& wp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_AUTH_TICKET, buf)
   {
       SetWritePacket(wp);
   }

   // (8)
   explicit CM_REQ_AUTH_TICKET_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       const ACCOUNT& account,
       UserId userId
   )
   {
       PacketSize& accountOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(userId);


       accountOffset = GetPacketSize();
       WriteBinary((uint8_t*)&account, account.GetPacketSize());

   }

   void SetValues(
       const ACCOUNT::Writer& account,
       UserId userId
   )
   {
       PacketSize& accountOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(userId);


       accountOffset = GetPacketSize();
       WriteBinary(account.GetPacketBufPtr(), account.GetPacketSize());

   }

   CM_REQ_AUTH_TICKET& GetPacket() const noexcept { return *reinterpret_cast<CM_REQ_AUTH_TICKET*>(GetPacketBufPtr()); }
   CM_REQ_AUTH_TICKET* GetPacketPtr() const noexcept { return reinterpret_cast<CM_REQ_AUTH_TICKET*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class CM_REQ_AUTH_TICKET : public NetworkPacket
{
   public:
      using Writer = CM_REQ_AUTH_TICKET_WRITER;


private:
   PacketSize m_account_offset = 0;

   UserId m_userId;

public:
   CM_REQ_AUTH_TICKET()
   {
       memset(this, 0, sizeof(CM_REQ_AUTH_TICKET));
       mPacketSize = static_cast<PacketSize>(sizeof(CM_REQ_AUTH_TICKET));
   }
   CM_REQ_AUTH_TICKET(const CM_REQ_AUTH_TICKET&) = delete;
   CM_REQ_AUTH_TICKET(CM_REQ_AUTH_TICKET &&) = delete;
   CM_REQ_AUTH_TICKET& operator = (const CM_REQ_AUTH_TICKET&) = delete;
   CM_REQ_AUTH_TICKET& operator = (CM_REQ_AUTH_TICKET &&) = delete;

   const ACCOUNT& Get_account() const noexcept { return *(ACCOUNT*)((uint8_t*)this + m_account_offset); }
   ACCOUNT* Get_account_ptr() const noexcept { return (ACCOUNT*)((uint8_t*)this + m_account_offset); }

   UserId Get_userId() const noexcept { return m_userId; }
   UserId& Ref_userId() noexcept { return m_userId; }
   const UserId& ConstRef_userId() const noexcept { return m_userId; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(CM_REQ_AUTH_TICKET) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(CM_REQ_AUTH_TICKET) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(CM_REQ_AUTH_TICKET); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(CM_REQ_AUTH_TICKET))
           {
               size += sizeof(CM_REQ_AUTH_TICKET);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           if (GetPacketSize() < m_account_offset)
               return false;

           const ACCOUNT* _packet = reinterpret_cast<const ACCOUNT*>(GetPacketBufPtr() + m_account_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       {
           thisSize += sizeof(UserId);
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, CM_REQ_AUTH_TICKET>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}account: {}", tTabStr, t->Get_account_ptr());
       result += std::format(L"\n{}userId: {}", tTabStr, t->Get_userId());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class CM_REQ_AUTH_MODIFY;

class CM_REQ_AUTH_MODIFY_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::CM_REQ_AUTH_MODIFY;

public:
   // (1)
   explicit CM_REQ_AUTH_MODIFY_WRITER(PacketTraitReq trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_AUTH_MODIFY, buf)
   {
   }

   // (2)
   explicit CM_REQ_AUTH_MODIFY_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacket& rp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_AUTH_MODIFY, buf)
   {
       SetReadPacket(rp);
   }

   // (3)
   explicit CM_REQ_AUTH_MODIFY_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacketWriter& wp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_AUTH_MODIFY, buf)
   {
       SetWritePacket(wp);
   }

   // (8)
   explicit CM_REQ_AUTH_MODIFY_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       const ACCOUNT& account
   )
   {
       PacketSize& accountOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       accountOffset = GetPacketSize();
       WriteBinary((uint8_t*)&account, account.GetPacketSize());

   }

   void SetValues(
       const ACCOUNT::Writer& account
   )
   {
       PacketSize& accountOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       accountOffset = GetPacketSize();
       WriteBinary(account.GetPacketBufPtr(), account.GetPacketSize());

   }

   CM_REQ_AUTH_MODIFY& GetPacket() const noexcept { return *reinterpret_cast<CM_REQ_AUTH_MODIFY*>(GetPacketBufPtr()); }
   CM_REQ_AUTH_MODIFY* GetPacketPtr() const noexcept { return reinterpret_cast<CM_REQ_AUTH_MODIFY*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class CM_REQ_AUTH_MODIFY : public NetworkPacket
{
   public:
      using Writer = CM_REQ_AUTH_MODIFY_WRITER;


private:
   PacketSize m_account_offset = 0;

public:
   CM_REQ_AUTH_MODIFY()
   {
       memset(this, 0, sizeof(CM_REQ_AUTH_MODIFY));
       mPacketSize = static_cast<PacketSize>(sizeof(CM_REQ_AUTH_MODIFY));
   }
   CM_REQ_AUTH_MODIFY(const CM_REQ_AUTH_MODIFY&) = delete;
   CM_REQ_AUTH_MODIFY(CM_REQ_AUTH_MODIFY &&) = delete;
   CM_REQ_AUTH_MODIFY& operator = (const CM_REQ_AUTH_MODIFY&) = delete;
   CM_REQ_AUTH_MODIFY& operator = (CM_REQ_AUTH_MODIFY &&) = delete;

   const ACCOUNT& Get_account() const noexcept { return *(ACCOUNT*)((uint8_t*)this + m_account_offset); }
   ACCOUNT* Get_account_ptr() const noexcept { return (ACCOUNT*)((uint8_t*)this + m_account_offset); }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(CM_REQ_AUTH_MODIFY) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(CM_REQ_AUTH_MODIFY) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(CM_REQ_AUTH_MODIFY); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(CM_REQ_AUTH_MODIFY))
           {
               size += sizeof(CM_REQ_AUTH_MODIFY);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           if (GetPacketSize() < m_account_offset)
               return false;

           const ACCOUNT* _packet = reinterpret_cast<const ACCOUNT*>(GetPacketBufPtr() + m_account_offset);
           if (!_packet->Validate(thisSize, ++depth))
               return false;

           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, CM_REQ_AUTH_MODIFY>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}account: {}", tTabStr, t->Get_account_ptr());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class CM_REQ_GAME_LIST_OVER;

class CM_REQ_GAME_LIST_OVER_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::CM_REQ_GAME_LIST_OVER;

public:
   // (1)
   explicit CM_REQ_GAME_LIST_OVER_WRITER(PacketTraitReq trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_GAME_LIST_OVER, buf)
   {
   }

   // (2)
   explicit CM_REQ_GAME_LIST_OVER_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacket& rp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_GAME_LIST_OVER, buf)
   {
       SetReadPacket(rp);
   }

   // (3)
   explicit CM_REQ_GAME_LIST_OVER_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacketWriter& wp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_GAME_LIST_OVER, buf)
   {
       SetWritePacket(wp);
   }

   // (8)
   explicit CM_REQ_GAME_LIST_OVER_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       GameId overGameId
   )
   {
       WriteValue(overGameId);


   }

   CM_REQ_GAME_LIST_OVER& GetPacket() const noexcept { return *reinterpret_cast<CM_REQ_GAME_LIST_OVER*>(GetPacketBufPtr()); }
   CM_REQ_GAME_LIST_OVER* GetPacketPtr() const noexcept { return reinterpret_cast<CM_REQ_GAME_LIST_OVER*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class CM_REQ_GAME_LIST_OVER : public NetworkPacket
{
   public:
      using Writer = CM_REQ_GAME_LIST_OVER_WRITER;


private:
   GameId m_overGameId;

public:
   CM_REQ_GAME_LIST_OVER()
   {
       memset(this, 0, sizeof(CM_REQ_GAME_LIST_OVER));
       mPacketSize = static_cast<PacketSize>(sizeof(CM_REQ_GAME_LIST_OVER));
   }
   CM_REQ_GAME_LIST_OVER(const CM_REQ_GAME_LIST_OVER&) = delete;
   CM_REQ_GAME_LIST_OVER(CM_REQ_GAME_LIST_OVER &&) = delete;
   CM_REQ_GAME_LIST_OVER& operator = (const CM_REQ_GAME_LIST_OVER&) = delete;
   CM_REQ_GAME_LIST_OVER& operator = (CM_REQ_GAME_LIST_OVER &&) = delete;

   GameId Get_overGameId() const noexcept { return m_overGameId; }
   GameId& Ref_overGameId() noexcept { return m_overGameId; }
   const GameId& ConstRef_overGameId() const noexcept { return m_overGameId; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(CM_REQ_GAME_LIST_OVER) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(CM_REQ_GAME_LIST_OVER) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(CM_REQ_GAME_LIST_OVER); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(CM_REQ_GAME_LIST_OVER))
           {
               size += sizeof(CM_REQ_GAME_LIST_OVER);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(GameId);
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, CM_REQ_GAME_LIST_OVER>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}overGameId: {}", tTabStr, t->Get_overGameId());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class CM_REQ_GAME_LIST_UNDER;

class CM_REQ_GAME_LIST_UNDER_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::CM_REQ_GAME_LIST_UNDER;

public:
   // (1)
   explicit CM_REQ_GAME_LIST_UNDER_WRITER(PacketTraitReq trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_GAME_LIST_UNDER, buf)
   {
   }

   // (2)
   explicit CM_REQ_GAME_LIST_UNDER_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacket& rp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_GAME_LIST_UNDER, buf)
   {
       SetReadPacket(rp);
   }

   // (3)
   explicit CM_REQ_GAME_LIST_UNDER_WRITER(PacketTraitReq trait, uint8_t* buf, const NetworkPacketWriter& wp)
       :
       NetworkPacketWriter(trait, PacketTypes::CM_REQ_GAME_LIST_UNDER, buf)
   {
       SetWritePacket(wp);
   }

   // (8)
   explicit CM_REQ_GAME_LIST_UNDER_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       GameId underGameId
   )
   {
       WriteValue(underGameId);


   }

   CM_REQ_GAME_LIST_UNDER& GetPacket() const noexcept { return *reinterpret_cast<CM_REQ_GAME_LIST_UNDER*>(GetPacketBufPtr()); }
   CM_REQ_GAME_LIST_UNDER* GetPacketPtr() const noexcept { return reinterpret_cast<CM_REQ_GAME_LIST_UNDER*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class CM_REQ_GAME_LIST_UNDER : public NetworkPacket
{
   public:
      using Writer = CM_REQ_GAME_LIST_UNDER_WRITER;


private:
   GameId m_underGameId;

public:
   CM_REQ_GAME_LIST_UNDER()
   {
       memset(this, 0, sizeof(CM_REQ_GAME_LIST_UNDER));
       mPacketSize = static_cast<PacketSize>(sizeof(CM_REQ_GAME_LIST_UNDER));
   }
   CM_REQ_GAME_LIST_UNDER(const CM_REQ_GAME_LIST_UNDER&) = delete;
   CM_REQ_GAME_LIST_UNDER(CM_REQ_GAME_LIST_UNDER &&) = delete;
   CM_REQ_GAME_LIST_UNDER& operator = (const CM_REQ_GAME_LIST_UNDER&) = delete;
   CM_REQ_GAME_LIST_UNDER& operator = (CM_REQ_GAME_LIST_UNDER &&) = delete;

   GameId Get_underGameId() const noexcept { return m_underGameId; }
   GameId& Ref_underGameId() noexcept { return m_underGameId; }
   const GameId& ConstRef_underGameId() const noexcept { return m_underGameId; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(CM_REQ_GAME_LIST_UNDER) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(CM_REQ_GAME_LIST_UNDER) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(CM_REQ_GAME_LIST_UNDER); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(CM_REQ_GAME_LIST_UNDER))
           {
               size += sizeof(CM_REQ_GAME_LIST_UNDER);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(GameId);
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, CM_REQ_GAME_LIST_UNDER>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}underGameId: {}", tTabStr, t->Get_underGameId());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

#pragma pack(pop)

inline bool ValidatePacketCM(const Packet& rp)
{
   static constexpr bool(*ValidatePacketFuncArray[PacketTypes::CM_PACKET_END - PacketTypes::CM_PACKET_START - 1])(const Packet&) =
   {
       &ValidatePacketFunc<CM_SHELL_COMMAND>,
       &ValidatePacketFunc<CM_REQ_SERVER_LIST>,
       &ValidatePacketFunc<CM_REQ_ACCOUNT_USER_LIST>,
       &ValidatePacketFunc<CM_REQ_ACCOUNT_USER_CREATE>,
       &ValidatePacketFunc<CM_REQ_ACCOUNT_USER_DELETE>,
       &ValidatePacketFunc<CM_REQ_AUTH_TICKET>,
       &ValidatePacketFunc<CM_REQ_AUTH_MODIFY>,
       &ValidatePacketFunc<CM_REQ_GAME_LIST_OVER>,
       &ValidatePacketFunc<CM_REQ_GAME_LIST_UNDER>
   };

   if ((PacketTypes::CM_PACKET_START >= rp.GetPacketType()) ||
       (PacketTypes::CM_PACKET_END <= rp.GetPacketType()))
   {
       return true;
   }

   return ValidatePacketFuncArray[rp.GetPacketType() - PacketTypes::CM_PACKET_START - 1](rp);
}

template <typename _Owner, typename... _Args>
HandleResult DispatchPacketCM(uint64_t socket, _Owner* owner, NetworkPacket& rp, _Args&&... args)
{
   HandleResult handleResult = DispatchPacketCOMMON(socket, owner, rp, std::forward<_Args>(args)...);
   if (handleResult != HandleResult::NOT_EXISTS)
       return handleResult;
   
   static constexpr HandleResult(*DispatchPacketFuncArray[PacketTypes::CM_PACKET_END - PacketTypes::CM_PACKET_START - 1])(uint64_t, _Owner*, NetworkPacket&, _Args&&...) =
   {
       &DispatchPacketFunc<_Owner, CM_SHELL_COMMAND, _Args&&...>,
       &DispatchPacketFunc<_Owner, CM_REQ_SERVER_LIST, _Args&&...>,
       &DispatchPacketFunc<_Owner, CM_REQ_ACCOUNT_USER_LIST, _Args&&...>,
       &DispatchPacketFunc<_Owner, CM_REQ_ACCOUNT_USER_CREATE, _Args&&...>,
       &DispatchPacketFunc<_Owner, CM_REQ_ACCOUNT_USER_DELETE, _Args&&...>,
       &DispatchPacketFunc<_Owner, CM_REQ_AUTH_TICKET, _Args&&...>,
       &DispatchPacketFunc<_Owner, CM_REQ_AUTH_MODIFY, _Args&&...>,
       &DispatchPacketFunc<_Owner, CM_REQ_GAME_LIST_OVER, _Args&&...>,
       &DispatchPacketFunc<_Owner, CM_REQ_GAME_LIST_UNDER, _Args&&...>
   };

   if ((PacketTypes::CM_PACKET_START >= rp.GetPacketType()) ||
       (PacketTypes::CM_PACKET_END <= rp.GetPacketType()))
   {
       return HandleResult::NOT_EXISTS;
   }

   if (auto func = DispatchPacketFuncArray[rp.GetPacketType() - PacketTypes::CM_PACKET_START - 1])
       return func(socket, owner, rp, std::forward<_Args>(args)...);
   else
       return HandleResult::NOT_EXISTS;
}

