// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"
#include "Packet/NetworkPacket/NetworkPacket.h"
#include "Packet/NetworkPacket/NetworkPacketWriter.h"
#include "Packet/BasePacket/PacketWriter.h"
#include "Packet/PacketDataList/PacketDataList.h"
#include "Packet/PacketFuncs/PacketValidator.h"
#include "Packet/PacketFuncs/PacketDispatcher.h"

#pragma pack(push, 1)

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class GC_ERROR;

class GC_ERROR_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::GC_ERROR;

public:
   // (7)
   explicit GC_ERROR_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::GC_ERROR, buf)
   {
   }

   // (9)
   explicit GC_ERROR_WRITER(
       PacketTraitParam trait, uint8_t* buf,
       PacketType packetType
   )
       :
       NetworkPacketWriter(trait, PacketTypes::GC_ERROR, buf)
   {
       WriteValue(packetType);


   }

   // (8)
   explicit GC_ERROR_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       PacketType packetType
   )
   {
       WriteValue(packetType);


   }

   GC_ERROR& GetPacket() const noexcept { return *reinterpret_cast<GC_ERROR*>(GetPacketBufPtr()); }
   GC_ERROR* GetPacketPtr() const noexcept { return reinterpret_cast<GC_ERROR*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class GC_ERROR : public NetworkPacket
{
   public:
      using Writer = GC_ERROR_WRITER;


private:
   PacketType m_packetType;

public:
   GC_ERROR()
   {
       memset(this, 0, sizeof(GC_ERROR));
       mPacketSize = static_cast<PacketSize>(sizeof(GC_ERROR));
   }
   GC_ERROR(const GC_ERROR&) = delete;
   GC_ERROR(GC_ERROR &&) = delete;
   GC_ERROR& operator = (const GC_ERROR&) = delete;
   GC_ERROR& operator = (GC_ERROR &&) = delete;

   PacketType Get_packetType() const noexcept { return m_packetType; }
   PacketType& Ref_packetType() noexcept { return m_packetType; }
   const PacketType& ConstRef_packetType() const noexcept { return m_packetType; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(GC_ERROR) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(GC_ERROR) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(GC_ERROR); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(GC_ERROR))
           {
               size += sizeof(GC_ERROR);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(PacketType);
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, GC_ERROR>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}packetType: {}", tTabStr, t->Get_packetType());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class GC_GAME_CHANNEL_USER_ENTER;

class GC_GAME_CHANNEL_USER_ENTER_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::GC_GAME_CHANNEL_USER_ENTER;

public:
   // (7)
   explicit GC_GAME_CHANNEL_USER_ENTER_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::GC_GAME_CHANNEL_USER_ENTER, buf)
   {

   }

   // (8)
   explicit GC_GAME_CHANNEL_USER_ENTER_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   GC_GAME_CHANNEL_USER_ENTER& GetPacket() const noexcept { return *reinterpret_cast<GC_GAME_CHANNEL_USER_ENTER*>(GetPacketBufPtr()); }
   GC_GAME_CHANNEL_USER_ENTER* GetPacketPtr() const noexcept { return reinterpret_cast<GC_GAME_CHANNEL_USER_ENTER*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class GC_GAME_CHANNEL_USER_ENTER : public NetworkPacket
{
   public:
      using Writer = GC_GAME_CHANNEL_USER_ENTER_WRITER;


private:
public:
   GC_GAME_CHANNEL_USER_ENTER()
   {
       memset(this, 0, sizeof(GC_GAME_CHANNEL_USER_ENTER));
       mPacketSize = static_cast<PacketSize>(sizeof(GC_GAME_CHANNEL_USER_ENTER));
   }
   GC_GAME_CHANNEL_USER_ENTER(const GC_GAME_CHANNEL_USER_ENTER&) = delete;
   GC_GAME_CHANNEL_USER_ENTER(GC_GAME_CHANNEL_USER_ENTER &&) = delete;
   GC_GAME_CHANNEL_USER_ENTER& operator = (const GC_GAME_CHANNEL_USER_ENTER&) = delete;
   GC_GAME_CHANNEL_USER_ENTER& operator = (GC_GAME_CHANNEL_USER_ENTER &&) = delete;


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(GC_GAME_CHANNEL_USER_ENTER) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(GC_GAME_CHANNEL_USER_ENTER) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(GC_GAME_CHANNEL_USER_ENTER); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(GC_GAME_CHANNEL_USER_ENTER))
           {
               size += sizeof(GC_GAME_CHANNEL_USER_ENTER);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, GC_GAME_CHANNEL_USER_ENTER>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class GC_GAME_CHANNEL_USER_LEAVE;

class GC_GAME_CHANNEL_USER_LEAVE_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::GC_GAME_CHANNEL_USER_LEAVE;

public:
   // (7)
   explicit GC_GAME_CHANNEL_USER_LEAVE_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::GC_GAME_CHANNEL_USER_LEAVE, buf)
   {

   }

   // (8)
   explicit GC_GAME_CHANNEL_USER_LEAVE_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   GC_GAME_CHANNEL_USER_LEAVE& GetPacket() const noexcept { return *reinterpret_cast<GC_GAME_CHANNEL_USER_LEAVE*>(GetPacketBufPtr()); }
   GC_GAME_CHANNEL_USER_LEAVE* GetPacketPtr() const noexcept { return reinterpret_cast<GC_GAME_CHANNEL_USER_LEAVE*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class GC_GAME_CHANNEL_USER_LEAVE : public NetworkPacket
{
   public:
      using Writer = GC_GAME_CHANNEL_USER_LEAVE_WRITER;


private:
public:
   GC_GAME_CHANNEL_USER_LEAVE()
   {
       memset(this, 0, sizeof(GC_GAME_CHANNEL_USER_LEAVE));
       mPacketSize = static_cast<PacketSize>(sizeof(GC_GAME_CHANNEL_USER_LEAVE));
   }
   GC_GAME_CHANNEL_USER_LEAVE(const GC_GAME_CHANNEL_USER_LEAVE&) = delete;
   GC_GAME_CHANNEL_USER_LEAVE(GC_GAME_CHANNEL_USER_LEAVE &&) = delete;
   GC_GAME_CHANNEL_USER_LEAVE& operator = (const GC_GAME_CHANNEL_USER_LEAVE&) = delete;
   GC_GAME_CHANNEL_USER_LEAVE& operator = (GC_GAME_CHANNEL_USER_LEAVE &&) = delete;


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(GC_GAME_CHANNEL_USER_LEAVE) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(GC_GAME_CHANNEL_USER_LEAVE) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(GC_GAME_CHANNEL_USER_LEAVE); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(GC_GAME_CHANNEL_USER_LEAVE))
           {
               size += sizeof(GC_GAME_CHANNEL_USER_LEAVE);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, GC_GAME_CHANNEL_USER_LEAVE>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class GC_WORLD_DATA;

class GC_WORLD_DATA_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::GC_WORLD_DATA;

public:
   // (7)
   explicit GC_WORLD_DATA_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::GC_WORLD_DATA, buf)
   {
   }

   // (9)
   explicit GC_WORLD_DATA_WRITER(
       PacketTraitParam trait, uint8_t* buf,
       uint8_t isCompleted,
       WorldDataSize offset,
       const uint8_t* worldDataBin,
       PacketSize worldDataBinSize
   )
       :
       NetworkPacketWriter(trait, PacketTypes::GC_WORLD_DATA, buf)
   {
       WriteValue(isCompleted);

       WriteValue(offset);

       PacketSize& worldDataBinOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(worldDataBinSize);


       worldDataBinOffset = GetPacketSize();
       WriteBinary(worldDataBin, worldDataBinSize);

   }

   // (8)
   explicit GC_WORLD_DATA_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       uint8_t isCompleted,
       WorldDataSize offset,
       const uint8_t* worldDataBin,
       PacketSize worldDataBinSize
   )
   {
       WriteValue(isCompleted);

       WriteValue(offset);

       PacketSize& worldDataBinOffset = *(PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       WriteValue(worldDataBinSize);


       worldDataBinOffset = GetPacketSize();
       WriteBinary(worldDataBin, worldDataBinSize);

   }

   GC_WORLD_DATA& GetPacket() const noexcept { return *reinterpret_cast<GC_WORLD_DATA*>(GetPacketBufPtr()); }
   GC_WORLD_DATA* GetPacketPtr() const noexcept { return reinterpret_cast<GC_WORLD_DATA*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class GC_WORLD_DATA : public NetworkPacket
{
   public:
      using Writer = GC_WORLD_DATA_WRITER;


private:
   uint8_t m_isCompleted;

   WorldDataSize m_offset;

   PacketSize m_worldDataBin_offset = 0;
   PacketSize m_worldDataBin_size = 0;

public:
   GC_WORLD_DATA()
   {
       memset(this, 0, sizeof(GC_WORLD_DATA));
       mPacketSize = static_cast<PacketSize>(sizeof(GC_WORLD_DATA));
   }
   GC_WORLD_DATA(const GC_WORLD_DATA&) = delete;
   GC_WORLD_DATA(GC_WORLD_DATA &&) = delete;
   GC_WORLD_DATA& operator = (const GC_WORLD_DATA&) = delete;
   GC_WORLD_DATA& operator = (GC_WORLD_DATA &&) = delete;

   uint8_t Get_isCompleted() const noexcept { return m_isCompleted; }
   uint8_t& Ref_isCompleted() noexcept { return m_isCompleted; }
   const uint8_t& ConstRef_isCompleted() const noexcept { return m_isCompleted; }

   WorldDataSize Get_offset() const noexcept { return m_offset; }
   WorldDataSize& Ref_offset() noexcept { return m_offset; }
   const WorldDataSize& ConstRef_offset() const noexcept { return m_offset; }

   const uint8_t* Get_worldDataBin() const noexcept { return ((uint8_t*)this + m_worldDataBin_offset); }
   PacketSize Get_worldDataBin_size() const noexcept { return m_worldDataBin_size; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(GC_WORLD_DATA) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(GC_WORLD_DATA) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(GC_WORLD_DATA); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(GC_WORLD_DATA))
           {
               size += sizeof(GC_WORLD_DATA);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           thisSize += sizeof(uint8_t);
       }

       {
           thisSize += sizeof(WorldDataSize);
       }

       {
           if (GetPacketSize() < m_worldDataBin_offset)
               return false;

           thisSize += m_worldDataBin_size;
           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < thisSize)
               return false;
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, GC_WORLD_DATA>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       result += std::format(L"\n{}isCompleted: {}", tTabStr, t->Get_isCompleted());
       result += std::format(L"\n{}offset: {}", tTabStr, t->Get_offset());
       result += std::format(L"\n{}worldDataBin: BIN[{}]", tTabStr, t->Get_worldDataBin_size());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class GC_GAME_UPDATE;

class GC_GAME_UPDATE_WRITER : public NetworkPacketWriter
{
public:
   static constexpr PacketType PACKET_TYPE = PacketTypes::GC_GAME_UPDATE;

private:
   PacketSize* m_worldUserStatAllList_offset = nullptr;
   PacketSize* m_worldUserStatAllList_count = nullptr;

   PacketSize* m_worldUserStatDiffList_offset = nullptr;
   PacketSize* m_worldUserStatDiffList_count = nullptr;

   PacketSize* m_worldUserCommandList_offset = nullptr;
   PacketSize* m_worldUserCommandList_count = nullptr;

public:
   // (7)
   explicit GC_GAME_UPDATE_WRITER(PacketTraitNotify trait, uint8_t* buf)
       :
       NetworkPacketWriter(trait, PacketTypes::GC_GAME_UPDATE, buf)
   {
   }

   // (9)
   explicit GC_GAME_UPDATE_WRITER(
       PacketTraitParam trait, uint8_t* buf,
       TimeStep timeStepToUpdate,
       TimeStep timeStepNow,
       uint8_t isCompleted,
       EngineUpdateChecksum checksum
   )
       :
       NetworkPacketWriter(trait, PacketTypes::GC_GAME_UPDATE, buf)
   {
       m_worldUserStatAllList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       m_worldUserStatAllList_count = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       m_worldUserStatDiffList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       m_worldUserStatDiffList_count = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       m_worldUserCommandList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       m_worldUserCommandList_count = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       WriteValue(timeStepToUpdate);

       WriteValue(timeStepNow);

       WriteValue(isCompleted);

       WriteValue(checksum);


   }

   // (8)
   explicit GC_GAME_UPDATE_WRITER(uint8_t* buf)
       :
       NetworkPacketWriter(buf) 
   {
   }

   void SetValues(
       TimeStep timeStepToUpdate,
       TimeStep timeStepNow,
       uint8_t isCompleted,
       EngineUpdateChecksum checksum
   )
   {
       m_worldUserStatAllList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       m_worldUserStatAllList_count = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       m_worldUserStatDiffList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       m_worldUserStatDiffList_count = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       m_worldUserCommandList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       m_worldUserCommandList_count = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));

       WriteValue(timeStepToUpdate);

       WriteValue(timeStepNow);

       WriteValue(isCompleted);

       WriteValue(checksum);


   }

   void Write_worldUserStatAllList(const WORLD_USER_STAT_ALL& packet)
   {
       *m_worldUserStatAllList_offset = GetPacketSize();
       WriteBinary((uint8_t*)&packet, packet.GetPacketSize());
       m_worldUserStatAllList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       ++(*m_worldUserStatAllList_count);
   }

   void Write_worldUserStatAllList(WORLD_USER_STAT_ALL&& packet)
   {
       *m_worldUserStatAllList_offset = GetPacketSize();
       WriteBinary((uint8_t*)&packet, packet.GetPacketSize());
       m_worldUserStatAllList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       ++(*m_worldUserStatAllList_count);
   }

   void Write_worldUserStatAllList(const WORLD_USER_STAT_ALL::Writer& packet)
   {
       *m_worldUserStatAllList_offset = GetPacketSize();
       WriteBinary(packet.GetPacketBufPtr(), packet.GetPacketSize());
       m_worldUserStatAllList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       ++(*m_worldUserStatAllList_count);
   }

   void Write_worldUserStatAllList(WORLD_USER_STAT_ALL::Writer&& packet)
   {
       *m_worldUserStatAllList_offset = GetPacketSize();
       WriteBinary(packet.GetPacketBufPtr(), packet.GetPacketSize());
       m_worldUserStatAllList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       ++(*m_worldUserStatAllList_count);
   }

   void Write_worldUserStatDiffList(const WORLD_USER_STAT_DIFF& packet)
   {
       *m_worldUserStatDiffList_offset = GetPacketSize();
       WriteBinary((uint8_t*)&packet, packet.GetPacketSize());
       m_worldUserStatDiffList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       ++(*m_worldUserStatDiffList_count);
   }

   void Write_worldUserStatDiffList(WORLD_USER_STAT_DIFF&& packet)
   {
       *m_worldUserStatDiffList_offset = GetPacketSize();
       WriteBinary((uint8_t*)&packet, packet.GetPacketSize());
       m_worldUserStatDiffList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       ++(*m_worldUserStatDiffList_count);
   }

   void Write_worldUserStatDiffList(const WORLD_USER_STAT_DIFF::Writer& packet)
   {
       *m_worldUserStatDiffList_offset = GetPacketSize();
       WriteBinary(packet.GetPacketBufPtr(), packet.GetPacketSize());
       m_worldUserStatDiffList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       ++(*m_worldUserStatDiffList_count);
   }

   void Write_worldUserStatDiffList(WORLD_USER_STAT_DIFF::Writer&& packet)
   {
       *m_worldUserStatDiffList_offset = GetPacketSize();
       WriteBinary(packet.GetPacketBufPtr(), packet.GetPacketSize());
       m_worldUserStatDiffList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       ++(*m_worldUserStatDiffList_count);
   }

   void Write_worldUserCommandList(const WORLD_USER_COMMAND& packet)
   {
       *m_worldUserCommandList_offset = GetPacketSize();
       WriteBinary((uint8_t*)&packet, packet.GetPacketSize());
       m_worldUserCommandList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       ++(*m_worldUserCommandList_count);
   }

   void Write_worldUserCommandList(WORLD_USER_COMMAND&& packet)
   {
       *m_worldUserCommandList_offset = GetPacketSize();
       WriteBinary((uint8_t*)&packet, packet.GetPacketSize());
       m_worldUserCommandList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       ++(*m_worldUserCommandList_count);
   }

   void Write_worldUserCommandList(const WORLD_USER_COMMAND::Writer& packet)
   {
       *m_worldUserCommandList_offset = GetPacketSize();
       WriteBinary(packet.GetPacketBufPtr(), packet.GetPacketSize());
       m_worldUserCommandList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       ++(*m_worldUserCommandList_count);
   }

   void Write_worldUserCommandList(WORLD_USER_COMMAND::Writer&& packet)
   {
       *m_worldUserCommandList_offset = GetPacketSize();
       WriteBinary(packet.GetPacketBufPtr(), packet.GetPacketSize());
       m_worldUserCommandList_offset = (PacketSize*)GetPacketBufWritingPtr();
       WriteValue(PacketSize(0));
       ++(*m_worldUserCommandList_count);
   }

   GC_GAME_UPDATE& GetPacket() const noexcept { return *reinterpret_cast<GC_GAME_UPDATE*>(GetPacketBufPtr()); }
   GC_GAME_UPDATE* GetPacketPtr() const noexcept { return reinterpret_cast<GC_GAME_UPDATE*>(GetPacketBufPtr()); }

};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class GC_GAME_UPDATE : public NetworkPacket
{
   public:
      using Writer = GC_GAME_UPDATE_WRITER;


private:
   PacketSize m_worldUserStatAllList_offset = 0;
   PacketSize m_worldUserStatAllList_count = 0;

   PacketSize m_worldUserStatDiffList_offset = 0;
   PacketSize m_worldUserStatDiffList_count = 0;

   PacketSize m_worldUserCommandList_offset = 0;
   PacketSize m_worldUserCommandList_count = 0;

   TimeStep m_timeStepToUpdate;

   TimeStep m_timeStepNow;

   uint8_t m_isCompleted;

   EngineUpdateChecksum m_checksum;

public:
   GC_GAME_UPDATE()
   {
       memset(this, 0, sizeof(GC_GAME_UPDATE));
       mPacketSize = static_cast<PacketSize>(sizeof(GC_GAME_UPDATE));
   }
   GC_GAME_UPDATE(const GC_GAME_UPDATE&) = delete;
   GC_GAME_UPDATE(GC_GAME_UPDATE &&) = delete;
   GC_GAME_UPDATE& operator = (const GC_GAME_UPDATE&) = delete;
   GC_GAME_UPDATE& operator = (GC_GAME_UPDATE &&) = delete;

   PacketDataList<GC_GAME_UPDATE, WORLD_USER_STAT_ALL> Get_worldUserStatAllList() const { return PacketDataList<GC_GAME_UPDATE, WORLD_USER_STAT_ALL>(this, m_worldUserStatAllList_offset); }
   PacketSize Get_worldUserStatAllList_count() const { return m_worldUserStatAllList_count; }

   PacketDataList<GC_GAME_UPDATE, WORLD_USER_STAT_DIFF> Get_worldUserStatDiffList() const { return PacketDataList<GC_GAME_UPDATE, WORLD_USER_STAT_DIFF>(this, m_worldUserStatDiffList_offset); }
   PacketSize Get_worldUserStatDiffList_count() const { return m_worldUserStatDiffList_count; }

   PacketDataList<GC_GAME_UPDATE, WORLD_USER_COMMAND> Get_worldUserCommandList() const { return PacketDataList<GC_GAME_UPDATE, WORLD_USER_COMMAND>(this, m_worldUserCommandList_offset); }
   PacketSize Get_worldUserCommandList_count() const { return m_worldUserCommandList_count; }

   TimeStep Get_timeStepToUpdate() const noexcept { return m_timeStepToUpdate; }
   TimeStep& Ref_timeStepToUpdate() noexcept { return m_timeStepToUpdate; }
   const TimeStep& ConstRef_timeStepToUpdate() const noexcept { return m_timeStepToUpdate; }

   TimeStep Get_timeStepNow() const noexcept { return m_timeStepNow; }
   TimeStep& Ref_timeStepNow() noexcept { return m_timeStepNow; }
   const TimeStep& ConstRef_timeStepNow() const noexcept { return m_timeStepNow; }

   uint8_t Get_isCompleted() const noexcept { return m_isCompleted; }
   uint8_t& Ref_isCompleted() noexcept { return m_isCompleted; }
   const uint8_t& ConstRef_isCompleted() const noexcept { return m_isCompleted; }

   EngineUpdateChecksum Get_checksum() const noexcept { return m_checksum; }
   EngineUpdateChecksum& Ref_checksum() noexcept { return m_checksum; }
   const EngineUpdateChecksum& ConstRef_checksum() const noexcept { return m_checksum; }


   bool Validate(IN OUT size_t& size, int32_t depth = 0) const
   {
       if (0 == GetPacketSize())
           return true;

       if (sizeof(GC_GAME_UPDATE) > GetPacketSize())
           return false;

       if (MAX_PACKET_BUFFER_SIZE < GetPacketSize())
           return false;

       if ((depth != 0) && (sizeof(GC_GAME_UPDATE) == GetPacketSize()))
       {
           size_t i = sizeof(NetworkPacket);
           for (; i < sizeof(GC_GAME_UPDATE); ++i)
               if (0 != GetPacketBufPtr()[i]) break;

           if (i == sizeof(GC_GAME_UPDATE))
           {
               size += sizeof(GC_GAME_UPDATE);
               return true;
           }
       }

       size_t thisSize = sizeof(NetworkPacket);

       {
           if (GetPacketSize() < m_worldUserStatAllList_offset)
               return false;

           PacketSize _offset = m_worldUserStatAllList_offset;
           while (0 != _offset)
           {
               const WORLD_USER_STAT_ALL* _packet = reinterpret_cast<const WORLD_USER_STAT_ALL*>(GetPacketBufPtr() + _offset);
               if (!_packet->Validate(thisSize, ++depth))
                   return false;

               if (GetPacketSize() < thisSize)
                   return false;

               _offset = *reinterpret_cast<const PacketSize*>(GetPacketBufPtr() + _offset + _packet->GetPacketSize());
               thisSize += sizeof(PacketSize);

               if (GetPacketSize() < _offset)
                   return false;
           }

           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < _offset)
               return false;
       }

       {
           if (GetPacketSize() < m_worldUserStatDiffList_offset)
               return false;

           PacketSize _offset = m_worldUserStatDiffList_offset;
           while (0 != _offset)
           {
               const WORLD_USER_STAT_DIFF* _packet = reinterpret_cast<const WORLD_USER_STAT_DIFF*>(GetPacketBufPtr() + _offset);
               if (!_packet->Validate(thisSize, ++depth))
                   return false;

               if (GetPacketSize() < thisSize)
                   return false;

               _offset = *reinterpret_cast<const PacketSize*>(GetPacketBufPtr() + _offset + _packet->GetPacketSize());
               thisSize += sizeof(PacketSize);

               if (GetPacketSize() < _offset)
                   return false;
           }

           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < _offset)
               return false;
       }

       {
           if (GetPacketSize() < m_worldUserCommandList_offset)
               return false;

           PacketSize _offset = m_worldUserCommandList_offset;
           while (0 != _offset)
           {
               const WORLD_USER_COMMAND* _packet = reinterpret_cast<const WORLD_USER_COMMAND*>(GetPacketBufPtr() + _offset);
               if (!_packet->Validate(thisSize, ++depth))
                   return false;

               if (GetPacketSize() < thisSize)
                   return false;

               _offset = *reinterpret_cast<const PacketSize*>(GetPacketBufPtr() + _offset + _packet->GetPacketSize());
               thisSize += sizeof(PacketSize);

               if (GetPacketSize() < _offset)
                   return false;
           }

           thisSize += sizeof(PacketSize);
           thisSize += sizeof(PacketSize);

           if (GetPacketSize() < _offset)
               return false;
       }

       {
           thisSize += sizeof(TimeStep);
       }

       {
           thisSize += sizeof(TimeStep);
       }

       {
           thisSize += sizeof(uint8_t);
       }

       {
           thisSize += sizeof(EngineUpdateChecksum);
       }

       if (GetPacketSize() != thisSize)
           return false;

       size += thisSize;

       return true;
   }

};

template<typename T, typename _CharType>
    requires std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, GC_GAME_UPDATE>
struct std::formatter<T, _CharType>
{
    constexpr auto parse(auto& ctx)
    {
        return ctx.end();
    }

    auto format(MAYBE_UNUSED T t, auto& ctx) const
    {
        std::wstring result;
       result += std::format(L"\n{}{}", tTabStr, t->ConstGetHeader());
       tTabStr += std::wstring(L"\t");
       if (0 == t->Get_worldUserStatAllList_count())
       {
           result += std::format(L"\n{}worldUserStatAllList: LIST[{}]", tTabStr, t->Get_worldUserStatAllList_count());
       }
       else
       {
           result += std::format(L"\n{}worldUserStatAllList: LIST[{}], ", tTabStr, t->Get_worldUserStatAllList_count());
           //tTabStr += std::wstring(L"\t");
           for (const WORLD_USER_STAT_ALL* it : t->Get_worldUserStatAllList())
           {
               result += std::format(L"\n{}{}", tTabStr, const_cast<WORLD_USER_STAT_ALL*>(it));
           }
           //tTabStr.pop_back();
       }
       if (0 == t->Get_worldUserStatDiffList_count())
       {
           result += std::format(L"\n{}worldUserStatDiffList: LIST[{}]", tTabStr, t->Get_worldUserStatDiffList_count());
       }
       else
       {
           result += std::format(L"\n{}worldUserStatDiffList: LIST[{}], ", tTabStr, t->Get_worldUserStatDiffList_count());
           //tTabStr += std::wstring(L"\t");
           for (const WORLD_USER_STAT_DIFF* it : t->Get_worldUserStatDiffList())
           {
               result += std::format(L"\n{}{}", tTabStr, const_cast<WORLD_USER_STAT_DIFF*>(it));
           }
           //tTabStr.pop_back();
       }
       if (0 == t->Get_worldUserCommandList_count())
       {
           result += std::format(L"\n{}worldUserCommandList: LIST[{}]", tTabStr, t->Get_worldUserCommandList_count());
       }
       else
       {
           result += std::format(L"\n{}worldUserCommandList: LIST[{}], ", tTabStr, t->Get_worldUserCommandList_count());
           //tTabStr += std::wstring(L"\t");
           for (const WORLD_USER_COMMAND* it : t->Get_worldUserCommandList())
           {
               result += std::format(L"\n{}{}", tTabStr, const_cast<WORLD_USER_COMMAND*>(it));
           }
           //tTabStr.pop_back();
       }
       result += std::format(L"\n{}timeStepToUpdate: {}", tTabStr, t->Get_timeStepToUpdate());
       result += std::format(L"\n{}timeStepNow: {}", tTabStr, t->Get_timeStepNow());
       result += std::format(L"\n{}isCompleted: {}", tTabStr, t->Get_isCompleted());
       result += std::format(L"\n{}checksum: {}", tTabStr, t->Get_checksum());
       tTabStr.pop_back();

       return std::ranges::copy(result, ctx.out()).out;
   }
};

#pragma pack(pop)

inline bool ValidatePacketGC(const Packet& rp)
{
   static constexpr bool(*ValidatePacketFuncArray[PacketTypes::GC_PACKET_END - PacketTypes::GC_PACKET_START - 1])(const Packet&) =
   {
       &ValidatePacketFunc<GC_ERROR>,
       &ValidatePacketFunc<GC_GAME_CHANNEL_USER_ENTER>,
       &ValidatePacketFunc<GC_GAME_CHANNEL_USER_LEAVE>,
       &ValidatePacketFunc<GC_WORLD_DATA>,
       &ValidatePacketFunc<GC_GAME_UPDATE>
   };

   if ((PacketTypes::GC_PACKET_START >= rp.GetPacketType()) ||
       (PacketTypes::GC_PACKET_END <= rp.GetPacketType()))
   {
       return true;
   }

   return ValidatePacketFuncArray[rp.GetPacketType() - PacketTypes::GC_PACKET_START - 1](rp);
}

template <typename _Owner, typename... _Args>
HandleResult DispatchPacketGC(uint64_t socket, _Owner* owner, NetworkPacket& rp, _Args&&... args)
{
   HandleResult handleResult = DispatchPacketCOMMON(socket, owner, rp, std::forward<_Args>(args)...);
   if (handleResult != HandleResult::NOT_EXISTS)
       return handleResult;
   
   static constexpr HandleResult(*DispatchPacketFuncArray[PacketTypes::GC_PACKET_END - PacketTypes::GC_PACKET_START - 1])(uint64_t, _Owner*, NetworkPacket&, _Args&&...) =
   {
       &DispatchPacketFunc<_Owner, GC_ERROR, _Args&&...>,
       &DispatchPacketFunc<_Owner, GC_GAME_CHANNEL_USER_ENTER, _Args&&...>,
       &DispatchPacketFunc<_Owner, GC_GAME_CHANNEL_USER_LEAVE, _Args&&...>,
       &DispatchPacketFunc<_Owner, GC_WORLD_DATA, _Args&&...>,
       &DispatchPacketFunc<_Owner, GC_GAME_UPDATE, _Args&&...>
   };

   if ((PacketTypes::GC_PACKET_START >= rp.GetPacketType()) ||
       (PacketTypes::GC_PACKET_END <= rp.GetPacketType()))
   {
       return HandleResult::NOT_EXISTS;
   }

   if (auto func = DispatchPacketFuncArray[rp.GetPacketType() - PacketTypes::GC_PACKET_START - 1])
       return func(socket, owner, rp, std::forward<_Args>(args)...);
   else
       return HandleResult::NOT_EXISTS;
}

