// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

Register<AbilityComponentGridBlock>(ComponentType::ABILITY_COMPONENT_GRID_BLOCK, engine);
Register<AbilityComponentGridUnblock>(ComponentType::ABILITY_COMPONENT_GRID_UNBLOCK, engine);
Register<AbilityComponentGridApplied>(ComponentType::ABILITY_COMPONENT_GRID_APPLIED, engine);
Register<AbilityComponentRecovery>(ComponentType::ABILITY_COMPONENT_RECOVERY, engine);
Register<AbilityComponentUntargetrable>(ComponentType::ABILITY_COMPONENT_UNTARGETABLE, engine);
Register<FormationComponentGroup>(ComponentType::FORMATION_COMPONENT_GROUP, engine);
Register<FormationComponentFlock>(ComponentType::FORMATION_COMPONENT_FLOCK, engine);
Register<FormationComponentCrowd>(ComponentType::FORMATION_COMPONENT_CROWD, engine);
Register<MotionComponentGroupA>(ComponentType::MOTION_COMPONENT_GROUP_A, engine);
Register<MotionComponentSkillA>(ComponentType::MOTION_COMPONENT_SKILL_A, engine);
Register<MotionComponentBleeding>(ComponentType::MOTION_COMPONENT_BLEEDING, engine);
Register<MotionComponentJuggle>(ComponentType::MOTION_COMPONENT_JUGGLE, engine);
Register<MotionComponentDash>(ComponentType::MOTION_COMPONENT_DASH, engine);
Register<MotionComponentWeb>(ComponentType::MOTION_COMPONENT_WEB, engine);
Register<MotionComponentDamage>(ComponentType::MOTION_COMPONENT_DAMAGE, engine);
Register<MotionComponentGroupB>(ComponentType::MOTION_COMPONENT_GROUP_B, engine);
Register<MotionComponentSkillB>(ComponentType::MOTION_COMPONENT_SKILL_B, engine);
Register<MotionComponentShock>(ComponentType::MOTION_COMPONENT_SHOCK, engine);
Register<MotionComponentStun>(ComponentType::MOTION_COMPONENT_STUN, engine);
Register<MotionComponentGroupC>(ComponentType::MOTION_COMPONENT_GROUP_C, engine);
Register<MotionComponentDying>(ComponentType::MOTION_COMPONENT_DYING, engine);
Register<MotionComponentDead>(ComponentType::MOTION_COMPONENT_DEAD, engine);
Register<MotionComponentDeparture>(ComponentType::MOTION_COMPONENT_DEPARTURE, engine);
Register<MotionComponentArrival>(ComponentType::MOTION_COMPONENT_ARRIVAL, engine);
Register<BuffComponentGroup>(ComponentType::BUFF_COMPONENT_GROUP, engine);
Register<BuffComponentHeal>(ComponentType::BUFF_COMPONENT_HEAL, engine);
Register<CharacterComponent>(ComponentType::CHARACTER_COMPONENT, engine);
Register<PcComponent>(ComponentType::PC_COMPONENT, engine);
Register<LeaderComponent>(ComponentType::LEADER_COMPONENT, engine);
Register<FollowerComponent>(ComponentType::FOLLOWER_COMPONENT, engine);
Register<NpcComponent>(ComponentType::NPC_COMPONENT, engine);
Register<DamageComponent>(ComponentType::DAMAGE_COMPONENT, engine);
Register<DebuffComponentGroup>(ComponentType::DEBUFF_COMPONENT_GROUP, engine);
Register<DebuffComponentExplosion>(ComponentType::DEBUFF_COMPONENT_EXPLOSION, engine);
Register<DebuffComponentHealing>(ComponentType::DEBUFF_COMPONENT_HEALING, engine);
Register<DebuffComponentParasite>(ComponentType::DEBUFF_COMPONENT_PARASITE, engine);
Register<DebuffComponentPoison>(ComponentType::DEBUFF_COMPONENT_POISON, engine);
Register<DebuffComponentVirus>(ComponentType::DEBUFF_COMPONENT_VIRUS, engine);
Register<DetectionComponentEnemy>(ComponentType::DETECTION_COMPONENT_ENEMY, engine);
Register<DetectionComponentFlock>(ComponentType::DETECTION_COMPONENT_FLOCK, engine);
Register<DetectionComponentPartner>(ComponentType::DETECTION_COMPONENT_PARTNER, engine);
Register<ImpulseComponent>(ComponentType::IMPULSE_COMPONENT, engine);
Register<PhysicsComponent>(ComponentType::PHYSICS_COMPONENT, engine);
Register<PositionComponent>(ComponentType::POSITION_COMPONENT, engine);
Register<SkillComponentAxe>(ComponentType::SKILL_COMPONENT_AXE, engine);
Register<SkillComponentBow>(ComponentType::SKILL_COMPONENT_BOW, engine);
Register<SkillComponentSpear>(ComponentType::SKILL_COMPONENT_SPEAR, engine);
Register<SkillComponentBazooka>(ComponentType::SKILL_COMPONENT_BAZOOKA, engine);
Register<SkillComponentBomb>(ComponentType::SKILL_COMPONENT_BOMB, engine);
Register<SkillComponentHammer>(ComponentType::SKILL_COMPONENT_HAMMER, engine);
Register<SkillComponentHeal>(ComponentType::SKILL_COMPONENT_HEAL, engine);
Register<SkillComponentParasite>(ComponentType::SKILL_COMPONENT_PARASITE, engine);
Register<SkillComponentPoison>(ComponentType::SKILL_COMPONENT_POISON, engine);
Register<SkillComponentWeb>(ComponentType::SKILL_COMPONENT_WEB, engine);
Register<SkillComponentSpawn>(ComponentType::SKILL_COMPONENT_SPAWN, engine);
Register<SkillComponentBlocking>(ComponentType::SKILL_COMPONENT_BLOCKING, engine);
Register<SkillComponentLaser>(ComponentType::SKILL_COMPONENT_LASER, engine);
Register<SkillComponentSword>(ComponentType::SKILL_COMPONENT_SWORD, engine);
Register<SkillComponentDash>(ComponentType::SKILL_COMPONENT_DASH, engine);
Register<SkillComponentElectric>(ComponentType::SKILL_COMPONENT_ELECTRIC, engine);
Register<SkillComponentVirus>(ComponentType::SKILL_COMPONENT_VIRUS, engine);
Register<SkillComponentVampire>(ComponentType::SKILL_COMPONENT_VAMPIRE, engine);
Register<SkillComponentBlink>(ComponentType::SKILL_COMPONENT_BLINK, engine);
Register<SkillComponentProjectile>(ComponentType::SKILL_COMPONENT_PROJECTILE, engine);
Register<SpawneeComponent>(ComponentType::SPAWNEE_COMPONENT, engine);
Register<SpawnerComponent>(ComponentType::SPAWNER_COMPONENT, engine);
Register<TacticsComponentGroup>(ComponentType::TACTICS_COMPONENT_GROUP, engine);
Register<TacticsComponentCombat>(ComponentType::TACTICS_COMPONENT_COMBAT, engine);
Register<TacticsComponentReturn>(ComponentType::TACTICS_COMPONENT_RETURN, engine);
Register<TacticsComponentIdle>(ComponentType::TACTICS_COMPONENT_IDLE, engine);
Register<TacticsComponentRoaming>(ComponentType::TACTICS_COMPONENT_ROAMING, engine);
Register<TacticsComponentFlee>(ComponentType::TACTICS_COMPONENT_FLEE, engine);
