// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

import Bot;
import ServerEnginePacketAutoGenerated;

#include "BotSceneReconnect.h"


BotSceneReconnect::BotSceneReconnect(BotPtr& bot) 
	: 
	BotScene(bot)
{
	RegisterSeq(this, &BotSceneReconnect::CF_REQ_USER_LOGIN);
	if(IsConnectedWithFront())
		NextSeq();
}
void BotSceneReconnect::OnHandshakeCompleted(MAYBE_UNUSED bool reconnected)
{
	_DEBUG_LOG(WHITE, L"[{}][{}]", GetRawSocket(), GetBotId());
	NextSeq();
}

void BotSceneReconnect::OnLostConnection()
{
	_DEBUG_LOG(WHITE, L"[{}][{}]", GetRawSocket(), GetBotId());
	TryChangeToReconnectScene();
}

bool BotSceneReconnect::OnDispatchPacket(NetworkPacket& rp)
{
	HandleResult handleResult = DispatchPacket(GetRawSocket(), this, rp);
	if (handleResult == HandleResult::NOT_EXISTS)
	{
		_DEBUG_RED;
		return true;
	}
	return (handleResult == HandleResult::OK) ? true : false;
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

HandleResult BotSceneReconnect::OnPacket(MAYBE_UNUSED NetworkPacket& rp)
{
	HandleResult handleResult = DispatchPacketToParent<BotScene>(GetRawSocket(), this, rp);
	if (handleResult == HandleResult::NOT_EXISTS)
		_DEBUG_RED;
	return handleResult;
}

// 로그인 요청
void BotSceneReconnect::CF_REQ_USER_LOGIN()
{
	// 저장된 인증(AuthTicket)으로 로그인 요청
	BotSocketUtil::SendToFront<CF_REQ_USER_LOGIN::Writer > wp(*this, REQ);
	wp.SetHeader(GetBotContext().CurrPacketHeader());
	wp.SetValues(
		GetBotContext().AuthTicket()
	);
}

// 로그인 응답 받음
HandleResult BotSceneReconnect::OnPacket(FC_ACK_USER_LOGIN& rp)
{
	const Result result = rp.GetHeader().GetPacketResult();
	ReportResultAndYield(result);

	switch (result)
	{
	case Result::SUCCEEDED:
		// [TODO] 재접속 성공 시 마지막 플레이 상태(게임/채널 등) 복구 로직 필요.
		NextSeq();
		break;
	case Result::RETRY_LATER:
		RetrySeq();
		break;
	default:
		// 재로그인 실패: 별도 재접속/종료 처리 필요.
		ReportBotEvent(BotEventType::RECONNECT_FAILED);
		break;
	}

	return HandleResult::OK;
}

