// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

import FrontServer;
import ServerEnginePacketAutoGenerated;


// 채팅 요청을 받음
HandleResult FrontPacketHandlerChat::OnPacket(CF_REQ_CHAT& rp, MAYBE_UNUSED SocketFrontFromClient& socket)
{
	Result result = Result::SUCCEEDED;

	ClockMs nextChattingDelay = DEFAULT_CHATTING_DELAY;

	do
	{
		FrontUserPtr frontUser = socket.GetFrontUser();

		if (nullptr == frontUser)
		{
			result = Result::CACHE_ERROR;
			break;
		}

		if (frontUser->GetCurrPacketHeader().ValidateState(rp.GetHeader()))
		{
			result = Result::CACHE_ERROR;
			break;
		}

		const UserId userId = frontUser->GetCurrPacketHeader().GetUserId();

		if (INVALID_UUID == userId)
		{
			result = Result::INVALID_UUID;
			break;
		}
		
		const ClockMs currentChattingTime = frontUser->GetCurrentChattingTime();		
		const ClockMs now = tClock.GetLocalNowMs();
		const ClockMs chattingTimeDelta = (now > currentChattingTime) ? (now - currentChattingTime) : 0ms;

		nextChattingDelay = frontUser->GetNextChattingDelay();

		if (chattingTimeDelta < nextChattingDelay)
		{
			result = Result::RETRY_LATER;
			break;
		}

		const ACCOUNT_USER& accountUser = frontUser->LoadAccountUser();
		//const USER& user = frontUser->GetUser();

		SocketUtil::Send<MF_CHAT::Writer> wp(*gSocketFrontToMain, NOTIFY);
		wp.SetHeader(rp.GetHeader());
		wp.SetValues(
			rp.Get_chatType(),
			rp.Ref_roomId(),
			accountUser.Get_c_user_name(),
			accountUser.Get_c_user_name(),
			rp.Get_msg()
		);

		nextChattingDelay = gChattingDelayCalculator->CalculateChattingDelay();
		frontUser->SetNextChattingDelay(nextChattingDelay);
		frontUser->SetCurrentChattingTime(tClock.GetLocalNowMs());

	} while (false);

	// 성공 or 실패 응답
	SocketUtil::Send<FC_ACK_CHAT::Writer> wp(socket, ACK, rp, result);
	wp.SetValues(
		nextChattingDelay
	);

	return HandleResult::OK;
}

HandleResult FrontPacketHandlerChat::OnPacket(MF_CHAT& rp, MAYBE_UNUSED SocketFrontToMain& socket)
{
	gChattingDelayCalculator->Update();

	FC_CHAT::Writer wp(NOTIFY, TEMP_BUF);
	wp.SetHeader(rp.GetHeader());
	wp.SetValues(
		rp.Get_chatType(),
		rp.Ref_roomId(),
		rp.Get_userName(),
		rp.Get_guildName(),
		rp.Get_msg()
	);

	RoomId roomId = rp.Ref_roomId();
	if (roomId == INVALID_UUID)
	{
		// 모든 유저들에게 채팅 전송
		gFrontDataManager->ForEachUser(
			[&wp](FrontUserPtr& frontUser)
			{
				if (auto socketFromClient = frontUser->GetClientSocket())
				{
					// 암호화를 위해 세션 별 패킷 생성
					SocketUtil::Send<NetworkPacketWriter> wpEachUser(**socketFromClient);
					std::copy_n(wp.GetPacketBufPtr(), wp.GetPacketSize(), wpEachUser.GetPacketBufPtr());
				}
			}
		);
	}
	else
	{
		// 특정 방에 있는 유저들에게 채팅 전송
		gFrontDataManager->ForEachUserInRoom(roomId,
			[&wp](FrontUserPtr& frontUser)
			{
				if (auto socketFromClient = frontUser->GetClientSocket())
				{
					// 암호화를 위해 세션 별 패킷 생성
					SocketUtil::Send<NetworkPacketWriter> wpEachUser(**socketFromClient);
					std::copy_n(wp.GetPacketBufPtr(), wp.GetPacketSize(), wpEachUser.GetPacketBufPtr());
				}
			}
		);

	}

	return HandleResult::OK;
}

