// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#include "SharedLib/WorldCreationHelper/WorldCreationHelper.h"

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"

#include "MmoSync/GameInstance/GameInstance.h"


// STATIC_MAP 데이터를 기반으로 FieldMapConfig를 생성합니다.
FieldMapConfig WorldCreationHelper::MakeGridConfig(const STATIC_MAP* staticMap)
{
	FieldMapConfig gridConfig;

	gridConfig.mGridColCountFactor = static_cast<uint8_t>(staticMap->Get_c_grid_col_count_factor());
	gridConfig.mGridRowCountFactor = static_cast<uint8_t>(staticMap->Get_c_grid_row_count_factor());
	//gridConfig.mLevelDivision[0] = static_cast<uint8_t>(staticMap->Get_c_level_division0());
	//gridConfig.mLevelDivision[1] = static_cast<uint8_t>(staticMap->Get_c_level_division1());
	//gridConfig.mLevelDivision[2] = static_cast<uint8_t>(staticMap->Get_c_level_division2());
	//gridConfig.mLevelDivision[3] = static_cast<uint8_t>(staticMap->Get_c_level_division3());
	//gridConfig.mLevelDivision[4] = static_cast<uint8_t>(staticMap->Get_c_level_division4());
	//gridConfig.mLevelDivision[5] = static_cast<uint8_t>(staticMap->Get_c_level_division5());
	//gridConfig.mLevelDivision[6] = static_cast<uint8_t>(staticMap->Get_c_level_division6());
	//gridConfig.mFractalScale[0].x = static_cast<uint8_t>(staticMap->Get_c_fractal_scale_x0());
	//gridConfig.mFractalScale[1].x = static_cast<uint8_t>(staticMap->Get_c_fractal_scale_x1());
	//gridConfig.mFractalScale[2].x = static_cast<uint8_t>(staticMap->Get_c_fractal_scale_x2());
	//gridConfig.mFractalScale[3].x = static_cast<uint8_t>(staticMap->Get_c_fractal_scale_x3());
	//gridConfig.mFractalScale[0].y = static_cast<uint8_t>(staticMap->Get_c_fractal_scale_y0());
	//gridConfig.mFractalScale[1].y = static_cast<uint8_t>(staticMap->Get_c_fractal_scale_y1());
	//gridConfig.mFractalScale[2].y = static_cast<uint8_t>(staticMap->Get_c_fractal_scale_y2());
	//gridConfig.mFractalScale[3].y = static_cast<uint8_t>(staticMap->Get_c_fractal_scale_y3());
	//gridConfig.mFractalScale[0].w = static_cast<uint8_t>(staticMap->Get_c_fractal_scale_w0());
	//gridConfig.mFractalScale[1].w = static_cast<uint8_t>(staticMap->Get_c_fractal_scale_w1());
	//gridConfig.mFractalScale[2].w = static_cast<uint8_t>(staticMap->Get_c_fractal_scale_w2());
	//gridConfig.mFractalScale[3].w = static_cast<uint8_t>(staticMap->Get_c_fractal_scale_w3());
	gridConfig.mRandomSeed = static_cast<uint64_t>(staticMap->Get_c_random_seed());

	return gridConfig;
}
