// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#include "ClientPacketFlowCommon.h"

#include "Engine/TimerHandle.h"
#include "Engine/World.h"
#include "TimerManager.h"

#include "Packet/NetworkPacketAutoGenerated/PACKET_CD.h"
#include "Packet/NetworkPacketAutoGenerated/PACKET_CG.h"
#include "Packet/NetworkPacketAutoGenerated/PACKET_CM.h"
#include "Packet/StaticDataCatalog/StaticDataCatalog.h"

#include "MmoSync/Engine/Engine.h"
#include "MmoSync/GameInstance/GameInstance.h"

#include "ClientUtil/ClientStringUtil.h"
#include "GameCore/GameCore.h"
#include "SubSystem/NetworkContext/NetworkContext.h"
#include "SubSystem/NetworkManager/NetworkManager.h"
#include "SubSystem/NetworkManager/PacketPtr/PacketPtr.h"
#include "SubSystem/UiServiceManager/UiServiceManager.h"
#include "UiService/Game/UiServiceGame.h"
#include "Util/PacketUtil/PacketUtil.h"
#include "Util/SocketUtil/SocketUtil.h"


FClientPacketFlowCommon::FClientPacketFlowCommon()
{
	mCommandDispatcher.Register(
		L"print", L"",
		std::bind(&FClientPacketFlowCommon::OnCommand_print, this, std::placeholders::_1)
	);

	mCommandDispatcher.Register(
		L"pause", L"",
		std::bind(&FClientPacketFlowCommon::OnCommand_pause, this, std::placeholders::_1)
	);

	mCommandDispatcher.Register(
		L"resume", L"",
		std::bind(&FClientPacketFlowCommon::OnCommand_resume, this, std::placeholders::_1)
	);

	mCommandDispatcher.Register(
		L"rewind", L"",
		std::bind(&FClientPacketFlowCommon::OnCommand_rewind, this, std::placeholders::_1)
	);

	mCommandDispatcher.Register(
		L"reloaded", L"",
		std::bind(&FClientPacketFlowCommon::OnCommand_reloaded, this, std::placeholders::_1)
	);

	mCommandDispatcher.Register(
		L"debug", L"",
		std::bind(&FClientPacketFlowCommon::OnCommand_debug, this, std::placeholders::_1)
	);
}

void FClientPacketFlowCommon::OnDispatchPacket(NetworkPacket& rp)
{
	const HandleResult handleResult = PacketUtil::DispatchPacket(this, rp);

	if (handleResult != HandleResult::OK)
	{
		_DEBUG_LOG(RED, L"{}[{}]", GetPacketTypeString(rp.GetPacketType()), rp.GetPacketSize());
	}
}

HandleResult FClientPacketFlowCommon::OnPacket(SHELL_NOTIFY& rp)
{
	mCommandDispatcher.Dispatch(rp.Get_command());

	return HandleResult::OK;
}

void FClientPacketFlowCommon::OnCommand_print(ArgList& argList)
{
	UUiServiceManager* uiServiceManager = UUiServiceManager::Get(this);
	if (!uiServiceManager)
		return;

	TSharedPtr<FUiServiceGame> gameService = uiServiceManager->GetService<FUiServiceGame>();
	if (!gameService)
		return;

	FGameCorePauseGuard gameCorePauseGuard(gameService);
	TSharedPtr<FGameCore> gameCore = gameCorePauseGuard.GetGameCore();
	if (!gameCore)
		return;

	TSharedPtr<GameInstance> gameInstance = gameCore->GetGameInstance();
	if (!gameInstance)
		return;

	gameInstance->PrintDebugInfo(L"OnCommand_print");
}

void FClientPacketFlowCommon::OnCommand_pause(ArgList& argList)
{
	// Engine::GetDebugStepCount 를 읽어서 파일 로그를 남기도록 셋팅하는 것
	Engine::SetDebugStepCount(0);
}

void FClientPacketFlowCommon::OnCommand_resume(ArgList& argList)
{
	Engine::SetDebugStepCount(-1);
}

void FClientPacketFlowCommon::OnCommand_rewind(ArgList& argList)
{
	UUiServiceManager* uiServiceManager = UUiServiceManager::Get(this);
	if (!uiServiceManager)
		return;

	TSharedPtr<FUiServiceGame> gameService = uiServiceManager->GetService<FUiServiceGame>();
	if (!gameService)
		return;

	FGameCorePauseGuard gameCorePauseGuard(gameService);
	TSharedPtr<FGameCore> gameCore = gameCorePauseGuard.GetGameCore();
	if (!gameCore)
		return;

	// 월드데이터를 리셋하고 
	gameService->GetWorldDataSerializer()->Reset();

	// 게임ID는 유지 시켜주고
	const GameId& currGameId = UNetworkContext::Get(this)->GetCurrGameId();
	UNetworkContext::Get(this)->SetNextGameId(currGameId);

	// 월드데이터를 되돌릴 준비가 되었다고 알림
	SocketUtil::Send<CG_REWIND_WORLD_DATA::Writer> wp(NOTIFY);
}

void FClientPacketFlowCommon::OnCommand_reloaded(ArgList& argList)
{
	FTimerHandle timerHandle;
	gCurrWorld->GetTimerManager().SetTimer(
		timerHandle,
		FTimerDelegate::CreateLambda(
			[=]() {

				// DB 정적 데이터를 다시 읽어 온다
				gStaticDataCatalog->ResetSync();
				gStaticDataCatalog->SetSyncing();

				SocketUtil::Send<CD_REQ_STATIC_DATA_CHECKSUM::Writer> wp(REQ);			
			}),
			1.0f,
			false
	);
}

void FClientPacketFlowCommon::OnCommand_debug(ArgList& argList)
{
	UUiServiceManager* uiServiceManager = UUiServiceManager::Get(this);
	if (!uiServiceManager)
		return;

	TSharedPtr<FUiServiceGame> gameService = uiServiceManager->GetService<FUiServiceGame>();
	if (!gameService)
		return;

	FGameCorePauseGuard gameCorePauseGuard(gameService);
	TSharedPtr<FGameCore> gameCore = gameCorePauseGuard.GetGameCore();
	if (!gameCore)
		return;

	TSharedPtr<GameInstance> gameInstance = gameCore->GetGameInstance();
	if (!gameInstance)
		return;

	if (gameCore->HasSyncError())
	{
		gameCore->ResetSyncError();

		gameInstance->PrintDebugInfo(L"OnCommand_debug");

		SocketUtil::Send<CM_SHELL_COMMAND::Writer> wp(REQ);
		wp.SetValues(
			*ClientStringUtil::s_to_w(TEXT("print"))
		);
	}	
	else
	{
		SocketUtil::Send<CM_SHELL_COMMAND::Writer> wp(REQ);
		wp.SetValues(
			*ClientStringUtil::s_to_w(TEXT("step"))
		);
	}
}

HandleResult FClientPacketFlowCommon::OnPacket(DC_ACK_CHEAT& rp)
{
	const Result result = rp.GetHeader().GetPacketResult();

	switch (result)
	{
	case Result::SUCCEEDED:
	{
		PacketUtil::CacheUserData(rp.Get_userData());
		break;
	}
	case Result::RETRY_LATER:
	{
		// '잠시 후 재시도 하세요' 안내 팝업.
		break;
	}
	default:
	{
		UNetworkManager::Get(this)->FatalError();
		break;
	}
	}

	return HandleResult::OK;
}
