// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"


struct MissionDoc;

class PACKET_API UserMissionRow
{
private:
	PacketKeep<MISSION> mData;
	const MissionDoc* mDoc = nullptr;

public:
	explicit UserMissionRow(PacketKeep<MISSION>&& data);

public:
	const MISSION& Data() const { return **mData; }
	const MissionDoc* GetDoc();

public:
	bool IsEmpty() const { return (nullptr == mDoc); }
};

