// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"


class Server final
{
private:
	PacketKeep<SERVER> mData;

public:
	explicit Server(const SERVER& data);

	SERVER& GetData() { return **mData; }
};
