// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"

#include "ServerEngine/PacketTransactor/PacketTransactorBase.h"


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DB와 패킷 트랜잭션 처리
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class MainDbSession;
class UserDbSession;
class PacketHeader;

class DbAndPacketTransactor : public PacketTransactorBase
{
private:
	std::shared_ptr<MainDbSession> mMainDbSession = nullptr;
	std::shared_ptr<UserDbSession> mUserDbSession = nullptr;

	PacketHeader& mCurrPacketHeader;

public:
	explicit DbAndPacketTransactor(PacketHeader& packetHeader);

protected:
	MainDbSession& GetMainDbSession() { return *mMainDbSession; }
	UserDbSession& GetUserDbSession() { return *mUserDbSession; }

	PacketHeader& GetCurrPacketHeader() { return mCurrPacketHeader; }

protected:
	bool OnCommit() override;
	bool OnRollback() override;
};
