// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#include "Packet/StaticData/Quest/QuestDocLookup.h"

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"
#include "Packet/StaticDataAccessor/StaticDataAccessor.h"
#include "Packet/StaticDataCatalog/StaticDataCatalog.h"
#include "Packet/StaticData/Quest/QuestDoc.h"


QuestDocLookup::~QuestDocLookup()
{
	Clear();
}
void QuestDocLookup::Clear()
{
	for (auto& [_, doc] : mQuestDocMap)
	{
		_DELETE(doc);
	}
	mQuestDocMap.clear();
}

void QuestDocLookup::Load()
{
	for (const auto& it : gStaticDataCatalog->GetList<STATIC_QUEST>())
	{
		auto key = it->Get_c_quest_sid();
		auto found = mQuestDocMap.find(key);
		QuestDoc* doc =
			(mQuestDocMap.end() != found) ? found->second : _NEW<QuestDoc>();
		doc->mStaticQuest = *it;
		mQuestDocMap.emplace(key, doc);
	}
}

void QuestDocLookup::Link()
{
}

const QuestDoc* QuestDocLookup::Find(QuestSid questSid) const
{
	const auto it = mQuestDocMap.find(questSid);

	if (mQuestDocMap.end() == it)
	{
		_DEBUG_BREAK;
		_DEBUG_RED;
		return nullptr;
	}

	return it->second;
}
