// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Packet/BasePacketAutoGenerated/PACKET_LOG.h"


struct PACKET_API PacketLogger
{
	// 패킷 로그 출력 타입
	enum class PacketLogType : uint8_t
	{
		LOGGING_NONE = 0,
		LOGGING_PACKET_TYPE_ONLY = 1,
		LOGGING_PACKET_TYPE_AND_ARGS = 2
	};

	// 패킷 로그 출력 타입을 얻어오기
	static PacketLogType GetPacketLogType(PacketType packetType);

	// 패킷을 재정의된 _DEBUG_LOG 로 작동해야 하기 때문에 inline 으로 처리.
	static void LogPacket(MAYBE_UNUSED const wchar_t* packetType, MAYBE_UNUSED const wchar_t* packetName, MAYBE_UNUSED uint64_t socket, NetworkPacket& packet)
	{
		MAYBE_UNUSED const unsigned short color = (packet.GetHeader().GetPacketResult() == Result::SUCCEEDED) ? WHITE : RED;

		switch (PacketLogger::GetPacketLogType(packet.GetPacketType()))
		{
		case PacketLogType::LOGGING_PACKET_TYPE_ONLY:
		{
			_DEBUG_LOG(color, L"[{}({})], {}, {} ({} byte)\n",
				packetName,
				socket,
				packetType,
				packet.GetPacketType(),
				packet.GetPacketSize()
			);
			break;
		}
		case PacketLogType::LOGGING_PACKET_TYPE_AND_ARGS:
		{
			_DEBUG_LOG(color, L"[{}({})], {}, {} ({} byte){}\n",
				packetName,
				socket,
				packetType,
				packet.GetPacketType(),
				packet.GetPacketSize(),
				GetPacketLogString(packet)
			);
			break;
		}
		default:
		{
			break;
		}
		}
	}

	static std::wstring GetLogPacketString(NetworkPacket& packet)
	{
		switch (PacketLogger::GetPacketLogType(packet.GetPacketType()))
		{
		case PacketLogType::LOGGING_PACKET_TYPE_ONLY:
			return
				std::format(L"{} ({} byte)\n",
					GetPacketTypeString(packet.GetPacketType()),
					packet.GetPacketSize()
				).data();

		case PacketLogType::LOGGING_PACKET_TYPE_AND_ARGS:
			return
				std::format(L"{} ({} byte){}\n",
					GetPacketTypeString(packet.GetPacketType()),
					packet.GetPacketSize(),
					GetPacketLogString(packet)
				).data();

		default:
			break;
		}

		return TEXT("");
	}
};
