// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"
#include "Packet/BasePacketAutoGenerated/PACKET_LOG.h"

#include "ServerEngine/DbSpBase/DbSp.h"


struct DbUtil
{
	static Result ExecuteSp(DbSp& dbSp);
	static bool ExecuteSpWithoutResult(DbSp& dbSp);
	static Result FetchSpSingleRow(DbSp& dbSp);

	template <typename _Func>
	static Result FetchSp(DbSp& dbSp, _Func func);

	// 아래 파일에 자동 생성된 코드를 활용할 것
#if 0
	#include "ServerEngine/DbSpAutoGenerated/DbUtil.hpp";
#endif

	static STATIC_ACHIEVEMENT::Writer SpToPacket(const class SP_STATIC_ACHIEVEMENT_SELECT& sp);
	static STATIC_ACHIEVEMENT::Writer SpToPacket(const class SP_STATIC_ACHIEVEMENT_SELECT_ALL& sp);
	static STATIC_ACHIEVEMENT_STEP::Writer SpToPacket(const class SP_STATIC_ACHIEVEMENT_STEP_SELECT& sp);
	static STATIC_ACHIEVEMENT_STEP::Writer SpToPacket(const class SP_STATIC_ACHIEVEMENT_STEP_SELECT_ALL& sp);
	static STATIC_BUILDING::Writer SpToPacket(const class SP_STATIC_BUILDING_SELECT& sp);
	static STATIC_BUILDING::Writer SpToPacket(const class SP_STATIC_BUILDING_SELECT_ALL& sp);
	static STATIC_CHARACTER::Writer SpToPacket(const class SP_STATIC_CHARACTER_SELECT& sp);
	static STATIC_CHARACTER::Writer SpToPacket(const class SP_STATIC_CHARACTER_SELECT_ALL& sp);
	static STATIC_CHARACTER_SKILL::Writer SpToPacket(const class SP_STATIC_CHARACTER_SKILL_SELECT& sp);
	static STATIC_CHARACTER_SKILL::Writer SpToPacket(const class SP_STATIC_CHARACTER_SKILL_SELECT_ALL& sp);
	static STATIC_GAME::Writer SpToPacket(const class SP_STATIC_GAME_SELECT& sp);
	static STATIC_GAME::Writer SpToPacket(const class SP_STATIC_GAME_SELECT_ALL& sp);
	static STATIC_ITEM::Writer SpToPacket(const class SP_STATIC_ITEM_SELECT& sp);
	static STATIC_ITEM::Writer SpToPacket(const class SP_STATIC_ITEM_SELECT_ALL& sp);
	static STATIC_ITEM_STAT::Writer SpToPacket(const class SP_STATIC_ITEM_STAT_SELECT& sp);
	static STATIC_ITEM_STAT::Writer SpToPacket(const class SP_STATIC_ITEM_STAT_SELECT_ALL& sp);
	static STATIC_MAIL::Writer SpToPacket(const class SP_STATIC_MAIL_SELECT& sp);
	static STATIC_MAIL::Writer SpToPacket(const class SP_STATIC_MAIL_SELECT_ALL& sp);
	static STATIC_MAP::Writer SpToPacket(const class SP_STATIC_MAP_SELECT& sp);
	static STATIC_MAP::Writer SpToPacket(const class SP_STATIC_MAP_SELECT_ALL& sp);
	static STATIC_MISSION::Writer SpToPacket(const class SP_STATIC_MISSION_SELECT& sp);
	static STATIC_MISSION::Writer SpToPacket(const class SP_STATIC_MISSION_SELECT_ALL& sp);
	static STATIC_PRODUCT::Writer SpToPacket(const class SP_STATIC_PRODUCT_SELECT& sp);
	static STATIC_PRODUCT::Writer SpToPacket(const class SP_STATIC_PRODUCT_SELECT_ALL& sp);
	static STATIC_QUEST::Writer SpToPacket(const class SP_STATIC_QUEST_SELECT& sp);
	static STATIC_QUEST::Writer SpToPacket(const class SP_STATIC_QUEST_SELECT_ALL& sp);
	static STATIC_REWARD_GROUP::Writer SpToPacket(const class SP_STATIC_REWARD_GROUP_SELECT& sp);
	static STATIC_REWARD_GROUP::Writer SpToPacket(const class SP_STATIC_REWARD_GROUP_SELECT_ALL& sp);
	static STATIC_REWARD_RATIO::Writer SpToPacket(const class SP_STATIC_REWARD_RATIO_SELECT& sp);
	static STATIC_REWARD_RATIO::Writer SpToPacket(const class SP_STATIC_REWARD_RATIO_SELECT_ALL& sp);
	static STATIC_REWARD::Writer SpToPacket(const class SP_STATIC_REWARD_SELECT& sp);
	static STATIC_REWARD::Writer SpToPacket(const class SP_STATIC_REWARD_SELECT_ALL& sp);
	static STATIC_SCHEDULE::Writer SpToPacket(const class SP_STATIC_SCHEDULE_SELECT& sp);
	static STATIC_SCHEDULE::Writer SpToPacket(const class SP_STATIC_SCHEDULE_SELECT_ALL& sp);
	static STATIC_STAT::Writer SpToPacket(const class SP_STATIC_STAT_SELECT& sp);
	static STATIC_STAT::Writer SpToPacket(const class SP_STATIC_STAT_SELECT_ALL& sp);
	static STATIC_STOCK::Writer SpToPacket(const class SP_STATIC_STOCK_SELECT& sp);
	static STATIC_STOCK::Writer SpToPacket(const class SP_STATIC_STOCK_SELECT_ALL& sp);
	static STATIC_TRANSLATION::Writer SpToPacket(const class SP_STATIC_TRANSLATION_SELECT& sp);
	static STATIC_TRANSLATION::Writer SpToPacket(const class SP_STATIC_TRANSLATION_SELECT_ALL& sp);
	static STATIC_USER_EXP::Writer SpToPacket(const class SP_STATIC_USER_EXP_SELECT& sp);
	static STATIC_USER_EXP::Writer SpToPacket(const class SP_STATIC_USER_EXP_SELECT_ALL& sp);
	static LOG_ACHIEVEMENT::Writer SpToPacket(const class SP_LOG_ACHIEVEMENT_SELECT& sp);
	static LOG_ACHIEVEMENT::Writer SpToPacket(const class SP_LOG_ACHIEVEMENT_SELECT_ALL& sp);
	static ACCOUNT_DELETED::Writer SpToPacket(const class SP_ACCOUNT_DELETED_SELECT& sp);
	static ACCOUNT_DELETED::Writer SpToPacket(const class SP_ACCOUNT_DELETED_SELECT_ALL& sp);
	static ACCOUNT::Writer SpToPacket(const class SP_ACCOUNT_SELECT& sp);
	static ACCOUNT::Writer SpToPacket(const class SP_ACCOUNT_SELECT_ALL& sp);
	static ACCOUNT_USER_DELETED::Writer SpToPacket(const class SP_ACCOUNT_USER_DELETED_SELECT& sp);
	static ACCOUNT_USER_DELETED::Writer SpToPacket(const class SP_ACCOUNT_USER_DELETED_SELECT_ALL& sp);
	static ACCOUNT_USER_DELETED::Writer SpToPacket(const class SP_ACCOUNT_USER_DELETED_SELECT_BY_ACCOUNT& sp);
	static ACCOUNT_USER_GAME::Writer SpToPacket(const class SP_ACCOUNT_USER_GAME_SELECT& sp);
	static ACCOUNT_USER_GAME::Writer SpToPacket(const class SP_ACCOUNT_USER_GAME_SELECT_ALL& sp);
	static ACCOUNT_USER::Writer SpToPacket(const class SP_ACCOUNT_USER_SELECT& sp);
	static ACCOUNT_USER::Writer SpToPacket(const class SP_ACCOUNT_USER_SELECT_ALL& sp);
	static ACCOUNT_USER::Writer SpToPacket(const class SP_ACCOUNT_USER_SELECT_BY_ACCOUNT& sp);
	static GAME_DELETED::Writer SpToPacket(const class SP_GAME_DELETED_SELECT& sp);
	static GAME_DELETED::Writer SpToPacket(const class SP_GAME_DELETED_SELECT_ALL& sp);
	static GAME::Writer SpToPacket(const class SP_GAME_SELECT& sp);
	static GAME::Writer SpToPacket(const class SP_GAME_SELECT_ALL& sp);
	static PURCHASE_DELETED::Writer SpToPacket(const class SP_PURCHASE_DELETED_SELECT& sp);
	static PURCHASE_DELETED::Writer SpToPacket(const class SP_PURCHASE_DELETED_SELECT_ALL& sp);
	static PURCHASE::Writer SpToPacket(const class SP_PURCHASE_SELECT& sp);
	static PURCHASE::Writer SpToPacket(const class SP_PURCHASE_SELECT_ALL& sp);
	static SERVER::Writer SpToPacket(const class SP_SERVER_SELECT& sp);
	static SERVER::Writer SpToPacket(const class SP_SERVER_SELECT_ALL& sp);
	static SERVER_STATISTICS::Writer SpToPacket(const class SP_SERVER_STATISTICS_SELECT& sp);
	static SERVER_STATISTICS::Writer SpToPacket(const class SP_SERVER_STATISTICS_SELECT_ALL& sp);
	static ACHIEVEMENT::Writer SpToPacket(const class SP_ACHIEVEMENT_SELECT& sp);
	static ACHIEVEMENT::Writer SpToPacket(const class SP_ACHIEVEMENT_SELECT_ALL& sp);
	static ACHIEVEMENT::Writer SpToPacket(const class SP_ACHIEVEMENT_SELECT_BY_USER& sp);
	static ACTIVITY::Writer SpToPacket(const class SP_ACTIVITY_SELECT& sp);
	static ACTIVITY::Writer SpToPacket(const class SP_ACTIVITY_SELECT_ALL& sp);
	static ACTIVITY::Writer SpToPacket(const class SP_ACTIVITY_SELECT_BY_USER& sp);
	static ITEM_DELETED::Writer SpToPacket(const class SP_ITEM_DELETED_SELECT& sp);
	static ITEM_DELETED::Writer SpToPacket(const class SP_ITEM_DELETED_SELECT_ALL& sp);
	static ITEM::Writer SpToPacket(const class SP_ITEM_SELECT& sp);
	static ITEM::Writer SpToPacket(const class SP_ITEM_SELECT_ALL& sp);
	static ITEM::Writer SpToPacket(const class SP_ITEM_SELECT_BY_USER& sp);
	static ITEM_STAT::Writer SpToPacket(const class SP_ITEM_STAT_SELECT& sp);
	static ITEM_STAT::Writer SpToPacket(const class SP_ITEM_STAT_SELECT_ALL& sp);
	static ITEM_STAT::Writer SpToPacket(const class SP_ITEM_STAT_SELECT_BY_USER& sp);
	static MAIL_DELETED::Writer SpToPacket(const class SP_MAIL_DELETED_SELECT& sp);
	static MAIL_DELETED::Writer SpToPacket(const class SP_MAIL_DELETED_SELECT_ALL& sp);
	static MAIL::Writer SpToPacket(const class SP_MAIL_SELECT& sp);
	static MAIL::Writer SpToPacket(const class SP_MAIL_SELECT_ALL& sp);
	static MAIL::Writer SpToPacket(const class SP_MAIL_SELECT_BY_USER& sp);
	static MISSION_DELETED::Writer SpToPacket(const class SP_MISSION_DELETED_SELECT& sp);
	static MISSION_DELETED::Writer SpToPacket(const class SP_MISSION_DELETED_SELECT_ALL& sp);
	static MISSION::Writer SpToPacket(const class SP_MISSION_SELECT& sp);
	static MISSION::Writer SpToPacket(const class SP_MISSION_SELECT_ALL& sp);
	static MISSION::Writer SpToPacket(const class SP_MISSION_SELECT_BY_USER& sp);
	static QUEST_DELETED::Writer SpToPacket(const class SP_QUEST_DELETED_SELECT& sp);
	static QUEST_DELETED::Writer SpToPacket(const class SP_QUEST_DELETED_SELECT_ALL& sp);
	static QUEST::Writer SpToPacket(const class SP_QUEST_SELECT& sp);
	static QUEST::Writer SpToPacket(const class SP_QUEST_SELECT_ALL& sp);
	static QUEST::Writer SpToPacket(const class SP_QUEST_SELECT_BY_USER& sp);
	static USER_POS::Writer SpToPacket(const class SP_USER_POS_SELECT& sp);
	static USER_POS::Writer SpToPacket(const class SP_USER_POS_SELECT_ALL& sp);
	static USER::Writer SpToPacket(const class SP_USER_SELECT& sp);
	static USER::Writer SpToPacket(const class SP_USER_SELECT_ALL& sp);
	static USER::Writer SpToPacket(const class SP_USER_SELECT_BY_ACCOUNT& sp);
};

template <typename _Func>
Result DbUtil::FetchSp(DbSp& dbSp, _Func func)
{
	if (false == dbSp.Execute())
		return Result::RETRY_LATER;

	while (true == dbSp.Fetch())
	{
		Result result = func();

		if (Result::SUCCEEDED != result)
			return result;
	}

	return Result::SUCCEEDED;
}
