// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// UserCacheAccessor
// 사용자 캐시 데이터에 대한 접근자 클래스입니다.
// 사용자별 테이블(아이템, 캐릭터, 퀘스트 등)을 관리합니다.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class UserCacheTableBase;

class PACKET_API UserCacheAccessor final
{
private:
	using UserCacheTableTypes = std::tuple<
		class UserAchievementTable,
		class UserCharacterTable,
		class UserItemTable,
		class UserItemStatTable,
		class UserMissionTable,
		class UserQuestTable
	>;

private:
	using UserCacheTablePtr = std::shared_ptr<UserCacheTableBase>;
	using UserCacheTableList = std::vector<UserCacheTablePtr>;

	UserCacheTableList mUserCacheTableList;

private:
	PacketKeep<ACCOUNT_USER> mAccountUser;
	PacketKeep<USER> mUser;

public:
	DISABLE_COPY(UserCacheAccessor);
	UserCacheAccessor();
	virtual ~UserCacheAccessor() = default;

private:
	template <typename _Table>
	void RegisterTable(size_t idx)
	{
		using _TableType = typename std::decay<_Table>::type;

		_TableType::mTableIdx = idx;

		std::shared_ptr<_TableType> ptr = std::make_shared<_TableType>();
		mUserCacheTableList.emplace_back(ptr);
	}

public:
	template <typename _Table>
	std::shared_ptr<typename std::decay<_Table>::type> Get() const
	{ 
		using _TableType = typename std::decay<_Table>::type;

		std::shared_ptr<UserCacheTableBase> ptr = mUserCacheTableList.at(_TableType::mTableIdx);
		std::shared_ptr<_TableType> castedPtr = std::static_pointer_cast<_TableType>(ptr);
		return castedPtr;
	}

public:
	bool IsEmpty() { return mUser.IsEmpty(); }
	void SetUser(const ACCOUNT_USER& accountUser, const USER& user);

public:
	ACCOUNT_USER& GetAccountUser() { return **mAccountUser; }
	USER& GetUser() { return **mUser; }

public:
	void ClearUserCacheTableList();
};
