// ============================================================================
// myungdal tech-demo project
// 
// Author: 안명달 (Myungdal Ahn)
// Email: mooondal@gmail.com
// GitHub: https://github.com/myungdal/tech_demo.git
// ============================================================================

#pragma once

#include "Packet/BasePacketAutoGenerated/PACKET_COMMON.h"


class PACKET_API UserItemStatRow
{
private:
	PacketKeep<ITEM_STAT> mData;

public:
	explicit UserItemStatRow(PacketKeep<ITEM_STAT>&& data);

public:
	const ITEM_STAT& Data() const { return **mData; }
};
